### ISSUE TITLE
`ncp-update-nc 19.0.2` from 18.0.8 fails with a CLI exception: ProgressBar::advance() must be of the type int, string given

### ISSUE THREAD

**Issue by llucax** [nextcloud/nextcloudpi#1171]
Trying to upgrade from 18.0.8 to 19.0.2 using `ncp-update-nc 19.0.2` fails with the following exception:

`TypeError: Argument 1 passed to Symfony\Component\Console\Helper\ProgressBar::advance() must be of the type int, string given, called in /var/www/nextcloud/core/Command/Upgrade.php on line 144 and defined in /var/www/nextcloud/3rdparty/symfony/console/Helper/ProgressBar.php:310`

<details>
<summary>Upgrade log</summary>

```console
$ sudo ncp-update-nc 19.0.2
Current   Nextcloud version 18.0.8.2
Available Nextcloud version 19.0.2
Download Nextcloud 19.0.2...                                                                                                                                                   
Back up current instance...
check free space...
Maintenance mode enabled
backup database...
backup files...
backup /var/www//nextcloud-bkp_20200828_1598646316.tar.gz generated
Maintenance mode disabled
Install Nextcloud 19.0.2...
Restore apps...                                                                                                                                                                
 * apporder
 * audioplayer
 * audioplayer_editor
 * calendar
 * camerarawpreviews
 * checksum
 * contacts
 * deck
 * dicomviewer
 * event_update_notification
 * extract
 * files_automatedtagging
 * files_downloadactivity
 * files_markdown
 * files_mindmap
 * files_photospheres
 * files_retention
 * flowupload
 * groupfolders
 * keeweb
 * mail
 * maps
 * metadata
 * news
 * nextcloudpi
 * notes
 * occweb
 * ocr
 * phonetrack
 * previewgenerator
 * suspicious_login
 * tasks
 * twofactor_nextcloud_notification
 * twofactor_totp
 * unsplash
 * video_converter
Fix permissions...
Upgrade...
Nextcloud or one of the apps require upgrade - only a limited number of commands are available                                                                                 
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Disabled incompatible app: dicomviewer
Disabled incompatible app: files_automatedtagging
Disabled incompatible app: files_downloadactivity
Disabled incompatible app: files_photospheres
Disabled incompatible app: files_retention
Disabled incompatible app: keeweb
Disabled incompatible app: nextcloudpi
Disabled incompatible app: occweb
Cleanup ocr app data folder.

 Starting ...
 0/1 [>---------------------------]   0%An unhandled exception has been thrown:
TypeError: Argument 1 passed to Symfony\Component\Console\Helper\ProgressBar::advance() must be of the type int, string given, called in /var/www/nextcloud/core/Command/Upgrade
.php on line 144 and defined in /var/www/nextcloud/3rdparty/symfony/console/Helper/ProgressBar.php:310                                                                         
Stack trace:
#0 /var/www/nextcloud/core/Command/Upgrade.php(144): Symfony\Component\Console\Helper\ProgressBar->advance('Deleted tessdat...')                                               
#1 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(264): OC\Core\Command\Upgrade->OC\Core\Command\{closure}(Object(Symfony\Component\EventDispatcher\Ge
nericEvent), '\\OC\\Repair::adv...', Object(Symfony\Component\EventDispatcher\EventDispatcher))                                                                                
#2 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, '\\OC\\Repair::adv...', O
bject(Symfony\Component\EventDispatcher\GenericEvent))
#3 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, '\\OC\\Repair::adv...',
 Object(Symfony\Component\EventDispatcher\GenericEvent))
#4 /var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php(70): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\EventDispatcher\G
enericEvent), Object(Symfony\Component\EventDispatcher\GenericEvent))
#5 /var/www/nextcloud/lib/private/Repair.php(201): OC\EventDispatcher\SymfonyAdapter->dispatch('\\OC\\Repair::adv...', Object(Symfony\Component\EventDispatcher\GenericEvent)) 
#6 /var/www/nextcloud/lib/private/Repair.php(232): OC\Repair->emit('\\OC\\Repair', 'advance', Array)                                                                           
#7 /var/www/nextcloud/apps/ocr/lib/Migration/CleanupTessdata.php(48): OC\Repair->advance('Deleted tessdat...')                                                                 
#8 /var/www/nextcloud/lib/private/Repair.php(103): OCA\Ocr\Migration\CleanupTessdata->run(Object(OC\Repair))                                                                   
#9 /var/www/nextcloud/lib/private/legacy/OC_App.php(976): OC\Repair->run()
#10 /var/www/nextcloud/lib/private/App/AppManager.php(412): OC_App::executeRepairSteps('ocr', Array)                                                                           
#11 /var/www/nextcloud/lib/private/Updater.php(410): OC\App\AppManager->disableApp('ocr', true)                                                                                
#12 /var/www/nextcloud/lib/private/Updater.php(253): OC\Updater->checkAppsRequirements()
#13 /var/www/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade('19.0.2.2', '18.0.8.2')                                                                             
#14 /var/www/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#15 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Com
ponent\Console\Output\ConsoleOutput))
#16 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(
Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Compon
ent\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Sym
fony\Component\Console\Output\ConsoleOutput))
#19 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Co
mponent\Console\Output\ConsoleOutput))
#20 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#21 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#22 {main}Abort
Clean up...
Rolling back to backup /var/www/nextcloud-bkp_20200828_1598646316-18.0.8.2.tar.gz...

[... ROLLBACK PROCESS ...]

Cleanup...
Rollback successful. Nothing was updated
```
</details>

**System information**

<details>
<summary>NextCloudPi diagnostics</summary>                                                                                                                                     

```

NextCloudPi version  v1.28.1                                                                                                                                                   
NextCloudPi image    NextCloudPi_03-28-20                                                                                                                                      
distribution         Raspbian GNU/Linux 10 \n \l
automount            yes
USB devices          sda sdb
datadir              /srv/nextcloud/data
data in SD           no
data filesystem      ext2/ext3
data disk usage      2.6T/4.6T
rootfs usage         2.5G/29G
swapfile             /media/usbdisk/nextcloud/swap
dbdir                /srv/nextcloud/mariadb
Nextcloud check      ok
Nextcloud version    18.0.8.2
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      down
internet check       ok
port check 80        closed
port check 443       closed
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         yes
uptime               3days

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "1": "***REMOVED SEVERAL HOSTNAMES AND IPS FOR PRIVACY***"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.8.2",
        "overwrite.cli.url": "https:\/\/192.168.2.9\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",                                                                                                                                                   [68/634]
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/srv\/nextcloud\/data\/tmp",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\SVG",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],
        "jpeg_quality": "60",
        "overwriteprotocol": "https",
        "maintenance": false,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "2",
        "log_type": "file",
        "htaccess.RewriteBase": "\/",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "theme": "",
        "updater.release.channel": "stable",
        "data-fingerprint": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>
<details>
<summary>HTTPd logs</summary>

```

[Wed Aug 26 10:49:48.862314 2020] [ssl:warn] [pid 968:tid 3066532368] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name        
[Wed Aug 26 10:49:48.892962 2020] [ssl:warn] [pid 988:tid 3066532368] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name        
[Wed Aug 26 10:49:48.897853 2020] [mpm_event:notice] [pid 988:tid 3066532368] AH00489: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1d configured -- resuming normal operations        
[Wed Aug 26 10:49:48.897927 2020] [core:notice] [pid 988:tid 3066532368] AH00094: Command line: '/usr/sbin/apache2'                                                            
[Thu Aug 27 00:00:02.456596 2020] [mpm_event:notice] [pid 988:tid 3066532368] AH00493: SIGUSR1 received.  Doing graceful restart                                               
[Thu Aug 27 00:00:02.495593 2020] [ssl:warn] [pid 988:tid 3066532368] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name        
[Thu Aug 27 00:00:02.497209 2020] [mpm_event:notice] [pid 988:tid 3066532368] AH00489: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1d configured -- resuming normal operations        
[Thu Aug 27 00:00:02.497232 2020] [core:notice] [pid 988:tid 3066532368] AH00094: Command line: '/usr/sbin/apache2'                                                            
[Fri Aug 28 00:00:02.584210 2020] [mpm_event:notice] [pid 988:tid 3066532368] AH00493: SIGUSR1 received.  Doing graceful restart                                               
[Fri Aug 28 00:00:02.643883 2020] [ssl:warn] [pid 988:tid 3066532368] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name        
[Fri Aug 28 00:00:02.651022 2020] [mpm_event:notice] [pid 988:tid 3066532368] AH00489: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1d configured -- resuming normal operations        
[Fri Aug 28 00:00:02.651042 2020] [core:notice] [pid 988:tid 3066532368] AH00094: Command line: '/usr/sbin/apache2'                                                            
[Sat Aug 29 00:00:02.703606 2020] [mpm_event:notice] [pid 988:tid 3066532368] AH00493: SIGUSR1 received.  Doing graceful restart                                               
[Sat Aug 29 00:00:02.762921 2020] [ssl:warn] [pid 988:tid 3066532368] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name        
[Sat Aug 29 00:00:02.769597 2020] [mpm_event:notice] [pid 988:tid 3066532368] AH00489: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1d configured -- resuming normal operations        
[Sat Aug 29 00:00:02.769630 2020] [core:notice] [pid 988:tid 3066532368] AH00094: Command line: '/usr/sbin/apache2'                                                            
[Sun Aug 30 00:00:01.983644 2020] [mpm_event:notice] [pid 988:tid 3066532368] AH00493: SIGUSR1 received.  Doing graceful restart                                               
[Sun Aug 30 00:00:02.052078 2020] [ssl:warn] [pid 988:tid 3066532368] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name        
[Sun Aug 30 00:00:02.056845 2020] [mpm_event:notice] [pid 988:tid 3066532368] AH00489: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1d configured -- resuming normal operations        
[Sun Aug 30 00:00:02.056868 2020] [core:notice] [pid 988:tid 3066532368] AH00094: Command line: '/usr/sbin/apache2'                                                            

```
</details>

<details>
<summary>Database logs</summary>

```

2020-08-26 10:50:22 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2020-08-26 10:50:22 0 [Note] InnoDB: Number of pools: 1
2020-08-26 10:50:22 0 [Note] InnoDB: Using generic crc32 instructions
2020-08-26 10:50:22 0 [Note] InnoDB: Initializing buffer pool, total size = 1.5G, instances = 1, chunk size = 128M                                                             
2020-08-26 10:50:22 0 [Note] InnoDB: Completed initialization of buffer pool
2020-08-26 10:50:22 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().               
2020-08-26 10:50:23 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2020-08-26 10:50:23 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2020-08-26 10:50:23 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...                                                  
2020-08-26 10:50:23 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2020-08-26 10:50:23 0 [Note] InnoDB: Waiting for purge to start
2020-08-26 10:50:23 0 [Note] InnoDB: 10.3.23 started; log sequence number 5236372079; transaction id 11567282                                                                  
2020-08-26 10:50:23 0 [Note] InnoDB: Loading buffer pool(s) from /media/usb5tb-wdy8/nextcloud/mariadb/ib_buffer_pool                                                           
2020-08-26 10:50:23 0 [Note] Plugin 'FEEDBACK' is disabled.
2020-08-26 10:50:23 0 [Note] Server socket created on IP: '127.0.0.1'.
2020-08-26 10:50:24 0 [Note] Reading of all Master_info entries succeeded
2020-08-26 10:50:24 0 [Note] Added new Master_info '' to hash table
2020-08-26 10:50:24 0 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.3.23-MariaDB-0+deb10u1'  socket: '/run/mysqld/mysqld.sock'  port: 3306  Raspbian 10                                                                               
2020-08-26 10:50:50 0 [Note] InnoDB: Buffer pool(s) load completed at 200826 10:50:50

```
</details>

<details>
<summary>Nextcloud logs</summary>

Sorry, I'm not including this because they are just normal logs with access to my files, there are no errors or anything funny and I don't want to publish details about my personal files.
</details>

**Comment by ovpc** [comment]
you are using  v1.28.1
try updating ncp to latest v1.29.0 before running nc-update-nc again
Also  disable app(s) that seems to be cause of trouble, re-enable after update complete.

**Comment by llucax** [comment]
I see v1.29.0 was released very recently, I did an `ncp-update` before running `ncp-update-nc` but didn't find any updates at the time I did it. I just upgraded to v1.29.0 and the NC update went well. Thanks!

**Comment by feutl** [comment]
I do have the same problem, already on v1.29.8 of NCP and the update process on the WebUI (also tried it on the CLI) throw the exact same error.

Right now I am restoring the database via the roll-back feature, and I do hope this is going to work out fine again.
Any clues why this happened ? I am not sure if this is something NCP could check upfront

**Comment by ovpc** [comment]
> I do have the same problem, already on v1.29.8 of NCP and the update process on the WebUI (also tried it on the CLI) throw the exact same error.
> 
> Right now I am restoring the database via the roll-back feature, and I do hope this is going to work out fine again.
> Any clues why this happened ? I am not sure if this is something NCP could check upfront

Please use the forum for help. Run ncp-report and share output via pastbin or similar.

**Comment by feutl** [comment]
will do thanks
https://help.nextcloud.com/t/an-unhandled-exception-has-been-thrown-when-upgrading-to-19-0-2-with-ncp/91020

**Comment by nachoparker** [comment]
Nextcloud bug, seems like triggered by the OCR app

https://github.com/nextcloud/server/issues/21067

**Comment by feutl** [comment]
@ovpc and @nachoparker good to know - great and thanks for any help and advice 👍
