### ISSUE TITLE
News App Error when manually updating from 19.0.3.1 to 20.0.0

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#1191]
Apologies for the formatting error linking to other issues.
```
Update app news from appstore
An unhandled exception has been thrown:
Error: Undefined class constant 'NAME' in /data/nextcloud/apps/news/lib/Migration/MigrateConfig.php:55
Stack trace:
#0 /data/nextcloud/lib/private/Repair.php(106): OCA\News\Migration\MigrateConfig->run(Object(OC\Repair))
#1 /data/nextcloud/lib/private/legacy/OC_App.php(1042): OC\Repair->run()
#2 /data/nextcloud/lib/private/legacy/OC_App.php(979): OC_App::executeRepairSteps('news', Array)
#3 /data/nextcloud/lib/private/Installer.php(206): OC_App::updateApp('news')
#4 /data/nextcloud/lib/private/Updater.php(452): OC\Installer->updateAppstoreApp('news')
#5 /data/nextcloud/lib/private/Updater.php(260): OC\Updater->upgradeAppStoreApps(Array)
#6 /data/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade('20.0.0.9', '19.0.3.1')
#7 /data/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#8 /data/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /data/nextcloud/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /data/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /data/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /data/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /data/nextcloud/console.php(100): OC\Console\Application->run()
#14 /data/nextcloud/occ(11): require_once('/data/nextcloud...')
#15 {main}Abort
Clean up...
Rolling back to backup /var/www/nextcloud-bkp_20201007_1602035230-19.0.3.1.tar.gz...
```

**Comment by sunjam** [comment]
News app was just updated and I believe this issue is addressed
