### ISSUE TITLE
letsencryt problems (symlink and hooks)

### ISSUE THREAD

**Issue by UN-pi** [nextcloud/nextcloudpi#1350]
I have 2 Problems v 1.39.16 with cerbot:

**1. Running  certbot renew --dry-run from the commandline**
    results in:
Sep 22 18:04:13 nextcloudpi.fritz.box systemd[1]: Started Run certbot twice daily.
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/XXXXXX.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/renewal.py", line 68, in _reconstitute
    renewal_candidate = storage.RenewableCert(full_path, config)
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 463, in __init__
    self._check_symlinks()
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 522, in _check_symlinks
    "expected {0} to be a symlink".format(link))
certbot.errors.CertStorageError: expected /etc/letsencrypt/live/XXXXXX.com/cert.pem to be a **symlink**
Renewal configuration file /etc/letsencrypt/renewal/XXXXXX.com.conf is broken. Skipping.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

No renewals were attempted.

Additionally, the following renewal configurations were invalid:
  /etc/letsencrypt/renewal/XXXXXX.com.conf (parsefail)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)

**2. Running letsencrypt from ncp-config doesn't respect the letsencrypt-renewal-hooks.**
    Running from the commandline with a dryrun does.
    That is important because with this hooks I enable/disable geo-filters and ports to make letsencrypt working.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**System information**

**Comment by UN-pi** [comment]
May this is helpful:
There is a bug in certbot 0.31:
[https://community.letsencrypt.org/t/auto-renewal-started-failing-with-error-missing-command-line-flag-or-config-entry-for-this-setting/111211](url)

My cerbot-version with buster 5,10.63 64 bit was also 0.31.
My conf-file was looking like this:

 renew_before_expiry = 30 days
version = 0.31.0
archive_dir = /etc/letsencrypt/archive/example.com
cert = /etc/letsencrypt/live/example.com/cert.pem
privkey = /etc/letsencrypt/live/example.com/privkey.pem
chain = /etc/letsencrypt/live/example.com/chain.pem
fullchain = /etc/letsencrypt/live/example.com/fullchain.pem

 Options used in the renewal process
[renewalparams]
account = yy
authenticator = webroot
webroot_path = /var/www/nextcloud,
server = https://acme-v02.api.letsencrypt.org/directory
[[webroot_map]]


**_Because of the missing webroot-part I added it:_**

 renew_before_expiry = 30 days
version = 0.31.0
archive_dir = /etc/letsencrypt/archive/example.com
cert = /etc/letsencrypt/live/example.com/cert.pem
privkey = /etc/letsencrypt/live/example.com/privkey.pem
chain = /etc/letsencrypt/live/example.com/chain.pem
fullchain = /etc/letsencrypt/live/example.com/fullchain.pem

 Options used in the renewal process
[renewalparams]
account = yy
authenticator = webroot
webroot_path = /var/www/nextcloud,
server = https://acme-v02.api.letsencrypt.org/directory
[[webroot_map]]
**example.com = /var/www/nextcloud
www.example.com = /var/www/nextcloud**

After doing this. Certbot was running again.
But no renewal-hooks were started.

-------------------------------

Newer cerbot-versions are delivered with snaps:
`https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-debian-10`

1. I saved the complete /etc/letsencrypt directory.
2. I deinstalled letsencrypt and cerbot.
3. Cleanup with aptitude
4. Installing the snap and cerbot
5. Restoring my letsencrypt-dir to /etc

For now it is working.

1. The snap and the cerbot-version is automatic updated.
2. The hooks are working (needed by me for port-opening)
3. cerbot installs seperate snap-cerbot-timers, which are running 2 x daily.
4. I disabled the ncp-crond-weekly-entry.

Because of the automatic updates the snap-volume is growing.
In a weekly-cleanup-script i added this:
`https://kofler.info/unter-ubuntu-alte-snap-pakete-loeschen/`

snap list --all | awk '/disabled/{print $1, $3}' |
    while read snapname revision; do
        snap remove "$snapname" --revision="$revision"
    done

For now I hope it will work.
