### ISSUE TITLE
NCP Automatic update to NC 22.2.2 - Bricked?

### ISSUE THREAD

**Issue by ZendaiOwl** [nextcloud/nextcloudpi#1395]
My Raspberry Pi 4B rev1.2 did the automatic upgrade to NCP 1.44.5 and NC 22.2.2 at midnight the day before yesterday (_29th - 30th November_) after which my server was no longer accessible in the internal network, after a reboot it is no longer accessible from anywhere giving an "Internal Server Error". 

I can still access it from SSH using the hostname as target but that is the only way I can access it now. 

**System information**

ncp.log 

```shell
Running nc-update-nc-apps
Cannot load Zend OPcache - it was already loaded
PHP Warning:  PHP Startup: Unable to load dynamic library 'smbclient.so' (tried: /usr/lib/php/20180731/smbclient.so (/usr/lib/php/20180731/smbclient.so: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/smbclient.so.so (/usr/lib/php/20180731/smbclient.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
An unhandled exception has been thrown:
OC\HintException: [0]: Memcache \OC\Memcache\Redis not available for local cache (Is the matching PHP module installed and enabled?)
```

NC-Error.log

```shell
[Wed Dec 01 12:02:23.988539 2021] [proxy_fcgi:error] [pid 1308:tid 546643624320] [client 45.134.144.108:41526] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught OC\\HintException: [0]: Memcache \\OC\\Memcache\\Redis not available for local cache (Is the matching PHP module installed and enabled?)\n\n  thrown in /var/www/nextcloud/lib/private/Memcache/Factory.php on line 89'
```

ncp-report

<--! Paste this in GitHub report -->

<details>
<summary>NextCloudPi diagnostics</summary>

```

NextCloudPi version  v1.44.5
NextCloudPi image    NextCloudPi_10-08-21
OS                   Debian GNU/Linux 10. 5.10.63-v8+ (aarch64)
automount            yes
USB devices          sda 
datadir              /media/USBdrive/ncdata
data in SD           no
data filesystem      ext2/ext3
data disk usage      381G/3.5T
rootfs usage         2.8G/123G
swapfile             /media/USBdrive/swap
dbdir                /media/USBdrive/ncdatabase
Nextcloud check      error
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
HPB service          down
Postfix service      up
internet check       ok
port check 80        closed
port check 443       open
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
uptime               16min

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

An unhandled exception has been thrown:
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: could not find driver in /var/www/nextcloud/lib/private/DB/Connection.php:87
Stack trace:
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1486): OC\DB\Connection->connect()
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1014): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /var/www/nextcloud/lib/private/DB/Connection.php(231): Doctrine\DBAL\Connection->executeQuery()
#3 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(210): OC\DB\Connection->executeQuery()
#4 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(287): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /var/www/nextcloud/lib/private/AppConfig.php(344): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /var/www/nextcloud/lib/private/AppConfig.php(109): OC\AppConfig->loadConfigValues()
#7 /var/www/nextcloud/lib/private/AppConfig.php(300): OC\AppConfig->getApps()
#8 /var/www/nextcloud/lib/private/legacy/OC_App.php(971): OC\AppConfig->getValues()
#9 /var/www/nextcloud/lib/private/Server.php(687): OC_App::getAppVersions()
#10 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(160): OC\Server->OC\{closure}()
#11 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#13 /var/www/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#14 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#15 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(182): OC\AppFramework\Utility\SimpleContainer->get()
#16 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(160): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#17 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#18 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#19 /var/www/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#20 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#21 /var/www/nextcloud/lib/private/Server.php(1064): OC\AppFramework\Utility\SimpleContainer->get()
#22 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(160): OC\Server->OC\{closure}()
#23 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#24 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#25 /var/www/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#26 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#27 /var/www/nextcloud/lib/private/Server.php(2024): OC\AppFramework\Utility\SimpleContainer->get()
#28 /var/www/nextcloud/lib/private/Files/View.php(118): OC\Server->getLockingProvider()
#29 /var/www/nextcloud/lib/private/Server.php(435): OC\Files\View->__construct()
#30 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(160): OC\Server->OC\{closure}()
#31 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#32 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#33 /var/www/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#34 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#35 /var/www/nextcloud/lib/private/Server.php(1387): OC\AppFramework\Utility\SimpleContainer->get()
#36 /var/www/nextcloud/lib/base.php(594): OC\Server->boot()
#37 /var/www/nextcloud/lib/base.php(1089): OC::init()
#38 /var/www/nextcloud/console.php(48): require_once('...')
#39 /var/www/nextcloud/occ(11): require_once('...')
#40 {main}
```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Wed Dec 01 15:37:35.811397 2021] [:notice] [pid 935] ModSecurity: LIBXML compiled version="2.9.4"
[Wed Dec 01 15:37:35.811411 2021] [:notice] [pid 935] ModSecurity: Original server signature: Apache
[Wed Dec 01 15:37:35.811552 2021] [:notice] [pid 935] ModSecurity: StatusEngine call: "2.9.3,Apache,1.6.5/1.6.5,8.39/8.44 2020-02-12,Lua 5.1,2.9.4,01"
[Wed Dec 01 15:37:35.977427 2021] [:notice] [pid 935] ModSecurity: StatusEngine call successfully sent. For more information visit: http://status.modsecurity.org/
[Wed Dec 01 15:37:36.266247 2021] [http2:warn] [pid 1309] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Wed Dec 01 15:37:36.417117 2021] [mpm_prefork:notice] [pid 1309] AH00163: Apache/2.4.38 (Debian) OpenSSL/1.1.1d   configured -- resuming normal operations
[Wed Dec 01 15:37:36.417258 2021] [core:notice] [pid 1309] AH00094: Command line: '/usr/sbin/apache2'
[Wed Dec 01 15:45:51.755907 2021] [mpm_prefork:notice] [pid 1309] AH00169: caught SIGTERM, shutting down
[Wed Dec 01 15:45:52.053831 2021] [:notice] [pid 8307:tid 548318287232] ModSecurity for Apache/2.9.3 (http://www.modsecurity.org/) configured.
[Wed Dec 01 15:45:52.054077 2021] [:notice] [pid 8307:tid 548318287232] ModSecurity: APR compiled version="1.6.5"; loaded version="1.6.5"
[Wed Dec 01 15:45:52.054105 2021] [:notice] [pid 8307:tid 548318287232] ModSecurity: PCRE compiled version="8.39 "; loaded version="8.44 2020-02-12"
[Wed Dec 01 15:45:52.054216 2021] [:warn] [pid 8307:tid 548318287232] ModSecurity: Loaded PCRE do not match with compiled!
[Wed Dec 01 15:45:52.054234 2021] [:notice] [pid 8307:tid 548318287232] ModSecurity: LUA compiled version="Lua 5.1"
[Wed Dec 01 15:45:52.054251 2021] [:notice] [pid 8307:tid 548318287232] ModSecurity: YAJL compiled version="2.1.0"
[Wed Dec 01 15:45:52.054284 2021] [:notice] [pid 8307:tid 548318287232] ModSecurity: LIBXML compiled version="2.9.4"
[Wed Dec 01 15:45:52.054303 2021] [:notice] [pid 8307:tid 548318287232] ModSecurity: Original server signature: Apache
[Wed Dec 01 15:45:52.054493 2021] [:notice] [pid 8307:tid 548318287232] ModSecurity: StatusEngine call: "2.9.3,Apache,1.6.5/1.6.5,8.39/8.44 2020-02-12,Lua 5.1,2.9.4,01"
[Wed Dec 01 15:45:52.220434 2021] [:notice] [pid 8307:tid 548318287232] ModSecurity: StatusEngine call successfully sent. For more information visit: http://status.modsecurity.org/
[Wed Dec 01 15:45:52.369361 2021] [mpm_event:notice] [pid 8308:tid 548318287232] AH00489: Apache/2.4.38 (Debian) OpenSSL/1.1.1d   configured -- resuming normal operations
[Wed Dec 01 15:45:52.369573 2021] [core:notice] [pid 8308:tid 548318287232] AH00094: Command line: '/usr/sbin/apache2'

```
</details>

<details>
<summary>Database logs</summary>

```

2021-12-01 15:38:14 0 [Note] InnoDB: Uses event mutexes
2021-12-01 15:38:14 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2021-12-01 15:38:14 0 [Note] InnoDB: Number of pools: 1
2021-12-01 15:38:14 0 [Note] InnoDB: Using generic crc32 instructions
2021-12-01 15:38:14 0 [Note] InnoDB: Initializing buffer pool, total size = 1G, instances = 1, chunk size = 128M
2021-12-01 15:38:15 0 [Note] InnoDB: Completed initialization of buffer pool
2021-12-01 15:38:15 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2021-12-01 15:38:15 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2021-12-01 15:38:15 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2021-12-01 15:38:15 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2021-12-01 15:38:15 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2021-12-01 15:38:15 0 [Note] InnoDB: 10.3.31 started; log sequence number 5297246239; transaction id 8243287
2021-12-01 15:38:15 0 [Note] InnoDB: Loading buffer pool(s) from /media/USBdrive/ncdatabase/ib_buffer_pool
2021-12-01 15:38:15 0 [Note] Plugin 'FEEDBACK' is disabled.
2021-12-01 15:38:15 0 [Note] Server socket created on IP: '127.0.0.1'.
2021-12-01 15:38:16 0 [Note] Reading of all Master_info entries succeeded
2021-12-01 15:38:16 0 [Note] Added new Master_info '' to hash table
2021-12-01 15:38:16 0 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.3.31-MariaDB-0+deb10u1'  socket: '/run/mysqld/mysqld.sock'  port: 3306  Debian 10
2021-12-01 15:38:27 0 [Note] InnoDB: Buffer pool(s) load completed at 211201 15:38:27

```
</details>

<details>
<summary>Nextcloud logs</summary>

```

{"reqId":"BzpBLHfcZuCcUCreIObw","level":1,"time":"2021-11-19T20:37:55+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAgent":"--","version":"21.0.5.1"}
{"reqId":"BzpBLHfcZuCcUCreIObw","level":1,"time":"2021-11-19T20:38:16+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"--","version":"21.0.5.1"}
{"reqId":"BzpBLHfcZuCcUCreIObw","level":1,"time":"2021-11-19T20:38:16+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"--","version":"22.2.2.0"}
{"reqId":"BzpBLHfcZuCcUCreIObw","level":1,"time":"2021-11-19T20:38:16+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"--","version":"22.2.2.0"}
{"reqId":"BzpBLHfcZuCcUCreIObw","level":1,"time":"2021-11-19T20:38:16+01:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"--","version":"22.2.2.0"}
{"reqId":"YZg9QuXTb0NDcFqQemuFKwAAAFc","level":3,"time":"2021-11-20T01:11:48+01:00","remoteAddr":"**REDACTED**","user":"**REDACTED**","app":"no app in context","method":"POST","url":"/ocs/v2.php/apps/files_sharing/api/v1/shares","message":"Password is among the 1,000,000 most common ones. Please make it unique. Password needs to be at least 10 characters long.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.18.0","version":"22.2.2.0","exception":{"Exception":"Exception","Message":"Password is among the 1,000,000 most common ones. Please make it unique. Password needs to be at least 10 characters long.","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Share20/Manager.php","line":775,"function":"verifyPassword","class":"OC\\Share20\\Manager","type":"->","args":["11223344"]},{"file":"/var/www/nextcloud/apps/files_sharing/lib/Controller/ShareAPIController.php","line":657,"function":"createShare","class":"OC\\Share20\\Manager","type":"->","args":[{"__class__":"OC\\Share20\\Share"}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"createShare","class":"OCA\\Files_Sharing\\Controller\\ShareAPIController","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},1,3,"","false","11223344",null,"",""]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareAPIController"},"createShare"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareAPIController"},"createShare"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controller\\ShareAPIController","createShare",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.files_sharing.ShareAPI.createShare"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/files_sharing/api/v1/shares"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Share20/Manager.php","Line":194,"CustomMessage":"--"}}
{"reqId":"YZg9UuXTb0NDcFqQemuFLAAAAEI","level":3,"time":"2021-11-20T01:12:03+01:00","remoteAddr":"**REDACTED**","user":"**REDACTED**","app":"no app in context","method":"POST","url":"/ocs/v2.php/apps/files_sharing/api/v1/shares","message":"Password needs to be at least 10 characters long.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.18.0","version":"22.2.2.0","exception":{"Exception":"Exception","Message":"Password needs to be at least 10 characters long.","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Share20/Manager.php","line":775,"function":"verifyPassword","class":"OC\\Share20\\Manager","type":"->","args":["1 2 3 g"]},{"file":"/var/www/nextcloud/apps/files_sharing/lib/Controller/ShareAPIController.php","line":657,"function":"createShare","class":"OC\\Share20\\Manager","type":"->","args":[{"__class__":"OC\\Share20\\Share"}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"createShare","class":"OCA\\Files_Sharing\\Controller\\ShareAPIController","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},1,3,"","false","1 2 3 g",null,"",""]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareAPIController"},"createShare"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareAPIController"},"createShare"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controller\\ShareAPIController","createShare",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.files_sharing.ShareAPI.createShare"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/files_sharing/api/v1/shares"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Share20/Manager.php","Line":194,"CustomMessage":"--"}}
{"reqId":"y4MX0C5DKtDPEDgMisLD","level":2,"time":"2021-11-20T06:26:04+01:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 28: Operation timed out after 60001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://apps.nextcloud.com/api/v1/apps.json","userAgent":"--","version":"22.2.2.0"}
{"reqId":"YZjHEOXTb0NDcFqQemuILAAAAEw","level":4,"time":"2021-11-20T10:59:45+01:00","remoteAddr":"**REDACTED**","user":"**REDACTED**","app":"webdav","method":"PUT","url":"/**REDACTED**","message":"File name contains at least one invalid character","userAgent":"Mozilla/5.0 (Linux) mirall/3.3.6git (build 7957) (Nextcloud, bunsenlabs-4.19.0-18-amd64 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"22.2.2.0","exception":{"Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\InvalidPath","Message":"File name contains at least one invalid character","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":78,"function":"getChild","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["InstaFollower-master\\cookies\\mr_fox_aroundtheworld.json"]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/LockPlugin.php","line":68,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->","args":["files/zendai/Code/Mr_Fox/Test/InstaFollower-master\\cookies\\mr_fox_aroundtheworld.json"]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"getLock","class":"OCA\\DAV\\Connector\\Sabre\\LockPlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":456,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["beforeMethod:PUT",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":333,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":166,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","Line":226,"CustomMessage":"--"}}
{"reqId":"cyrp9sruMeqNbCZDFRUv","level":2,"time":"2021-11-21T06:26:04+01:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 28: Operation timed out after 60001 milliseconds with 0 out of 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://apps.nextcloud.com/api/v1/apps.json","userAgent":"--","version":"22.2.2.0"}
{"reqId":"Cm7Wo14LnEP7ovuotSii","level":2,"time":"2021-11-25T06:25:34+01:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 7: Failed to connect to apps.nextcloud.com port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://apps.nextcloud.com/api/v1/apps.json","userAgent":"--","version":"22.2.2.0"}
{"reqId":"srpDt728eepWBv5cwDMJ","level":2,"time":"2021-11-26T06:25:34+01:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 7: Failed to connect to apps.nextcloud.com port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://apps.nextcloud.com/api/v1/apps.json","userAgent":"--","version":"22.2.2.0"}
{"reqId":"88Ltr2DeOQ9VHiLT7ZmX","level":2,"time":"2021-11-28T06:25:34+01:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 7: Failed to connect to apps.nextcloud.com port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://apps.nextcloud.com/api/v1/apps.json","userAgent":"--","version":"22.2.2.0"}
{"reqId":"K9sxr7hjArZ4ZdhjY9Fi","level":2,"time":"2021-11-28T20:55:32+01:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 7: Failed to connect to apps.nextcloud.com port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://apps.nextcloud.com/api/v1/apps.json","userAgent":"--","version":"22.2.2.0"}
{"reqId":"vkGMc5m3VamV0iFN9ZCs","level":2,"time":"2021-11-29T06:26:04+01:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 28: Operation timed out after 60000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://apps.nextcloud.com/api/v1/apps.json","userAgent":"--","version":"22.2.2.0"}
{"reqId":"YaZdnfNvqOQ9Er-QjIuRFAAAigY","level":2,"time":"2021-11-30T18:21:34+01:00","remoteAddr":"**REDACTED**","user":"**REDACTED**","app":"suspicious_login","method":"POST","url":"/index.php/login","message":"Could not predict suspiciousness: No models found","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36","version":"22.2.2.0"}
{"reqId":"YaaNKDdSxjS6FjnXI4Wo4QAACho","level":2,"time":"2021-11-30T21:44:25+01:00","remoteAddr":"**REDACTED**","user":"**REDACTED**","app":"suspicious_login","method":"POST","url":"/index.php/login","message":"Could not predict suspiciousness: No models found","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36","version":"22.2.2.0"}
{"reqId":"YaaYHJahO@yArEvjFrv5RQAAAAA","level":3,"time":"2021-11-30T22:31:28+01:00","remoteAddr":"::1","user":"--","app":"index","method":"GET","url":"/index.php/apps/notify_push/test/version","message":"Connection lost","userAgent":"--","version":"22.2.2.0","exception":{"Exception":"RedisException","Message":"Connection lost","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/notify_push/lib/Controller/TestController.php","line":88,"function":"set","class":"Redis","type":"->","args":["notify_push_app_version","0.3.0"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"version","class":"OCA\\NotifyPush\\Controller\\TestController","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\NotifyPush\\Controller\\TestController"},"version"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\NotifyPush\\Controller\\TestController"},"version"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\NotifyPush\\Controller\\TestController","version",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"notify_push.test.version"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/notify_push/test/version"]},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/notify_push/lib/Controller/TestController.php","Line":88,"CustomMessage":"--"}}
{"reqId":"Yaa92@kff1@0mn5ORF63SgAAQAI","level":2,"time":"2021-12-01T01:12:12+01:00","remoteAddr":"**REDACTED**","user":"**REDACTED**","app":"suspicious_login","method":"POST","url":"/index.php/login","message":"Could not predict suspiciousness: No models found","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36","version":"22.2.2.0"}
{"reqId":"EpMX1lwIIY8NaiLQHrIB","level":2,"time":"2021-12-01T06:26:04+01:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 28: Operation timed out after 60001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://apps.nextcloud.com/api/v1/apps.json","userAgent":"--","version":"22.2.2.0"}

```
</details>

**Comment by ZendaiOwl** [comment]
After thinking about it for awhile and seeing if I could find anything I decided I will just rescue the data via SSH and reinstall the instance plus reformat the external drive to btrfs, which was something I was planning to do anyway. So I'll close this issue for now but if anyone else encounters it they can re-open it if they want

Here is some of the information I found for those having similar issues 

https://help.nextcloud.com/t/php-startup-unable-to-load-dynamic-library-smbclient-so/121691

https://help.nextcloud.com/t/tutorial-upgrade-php-php-fmp-to-version-7-4-arbiam-20-11-nextcloudpi-20-02-no-errors-in-nextcloud-log/100415
