### ISSUE TITLE
docker image: can't connect to db

### ISSUE THREAD

**Issue by dkebler** [nextcloud/nextcloudpi#1427]
Spinning up a fresh docker container can't get by 

`nextcloudpi    | Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Permission denied in /data/nextcloud/lib/private/DB/Connection.php:85`

may be related to.  Note in the log that Apache is started before maria. 
https://github.com/nextcloud/server/issues/22119

since this is an "all in one" image I can't spin up the db separately and make the webserver depend on it.

of note:  not having any issue with ncp on bare metal install.

compose file
```
version: '3'
services:
  nextcloudpi:
    image: ownyourbits/nextcloudpi:latest
#  command: "${IP}"
    ports:
     - "8094:80"
     - "8443:443"
     - "4443:4443"
    volumes:
     - ncdata:/data
     - /etc/localtime:/etc/localtime:ro
    container_name: nextcloudpi

volumes:
  ncdata:
```

full compose log, running on amd64 host so the amd64 image
```
Initializing empty volume..
nextcloudpi    | Making /usr/local/etc/ncp-config.d persistent ...
nextcloudpi    | Making /etc/services-enabled.d persistent ...
nextcloudpi    | Making /etc/letsencrypt persistent ...
nextcloudpi    | Making /etc/shadow persistent ...
nextcloudpi    | Making /etc/cron.d persistent ...
nextcloudpi    | Making /etc/cron.daily persistent ...
nextcloudpi    | Making /etc/cron.hourly persistent ...
nextcloudpi    | Making /etc/cron.weekly persistent ...
nextcloudpi    | Making /usr/local/bin persistent ...
nextcloudpi    | Making /etc/apache2 persistent ...
nextcloudpi    | Starting PHP-fpm
nextcloudpi    | Starting Apache
nextcloudpi    | Starting mariaDB
nextcloudpi    | 2022-02-24 11:51:58 0 [Note] mysqld (mysqld 10.3.29-MariaDB-0+deb10u1) starting as process 114 ...
nextcloudpi    | Starting Redis
nextcloudpi    | Starting Cron
nextcloudpi    | Starting Postfix
nextcloudpi    | Provisioning
nextcloudpi    | Provisioning Redis password
nextcloudpi    | Updating NextCloud config with Redis password
nextcloudpi    | Provisioning MariaDB password
nextcloudpi    | Updating NextCloud config with MariaDB password
nextcloudpi    | Running nc-limits
nextcloudpi    | Using 12347993088B for PHP
nextcloudpi    | Using 8 PHP threads
nextcloudpi    | Using 4065666048 memory for the database
nextcloudpi    | Stopping MariaDB database server: mysqld.
nextcloudpi    | Starting MariaDB database server: mysqld.
nextcloudpi    | Stopping redis-server: redis-server.
nextcloudpi    | Starting redis-server: redis-server.
nextcloudpi    | Starting notify_push daemon
nextcloudpi    | Configuring Domain
nextcloudpi    | An unhandled exception has been thrown:
nextcloudpi    | Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Permission denied in /data/nextcloud/lib/private/DB/Connection.php:85
nextcloudpi    | Stack trace:
nextcloudpi    | #0 /data/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1486): OC\DB\Connection->connect()
nextcloudpi    | #1 /data/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1014): Doctrine\DBAL\Connection->getWrappedConnection()
nextcloudpi    | #2 /data/nextcloud/lib/private/DB/Connection.php(226): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM `...', Array, Array, NULL)
nextcloudpi    | #3 /data/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(210): OC\DB\Connection->executeQuery('SELECT * FROM `...', Array, Array)
nextcloudpi    | #4 /data/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(287): Doctrine\DBAL\Query\QueryBuilder->execute()
nextcloudpi    | #5 /data/nextcloud/lib/private/AppConfig.php(345): OC\DB\QueryBuilder\QueryBuilder->execute()
nextcloudpi    | #6 /data/nextcloud/lib/private/AppConfig.php(110): OC\AppConfig->loadConfigValues()
nextcloudpi    | #7 /data/nextcloud/lib/private/AppConfig.php(301): OC\AppConfig->getApps()
nextcloudpi    | #8 /data/nextcloud/lib/private/legacy/OC_App.php(965): OC\AppConfig->getValues(false, 'installed_versi...')
nextcloudpi    | #9 /data/nextcloud/lib/private/Server.php(682): OC_App::getAppVersions()
nextcloudpi    | #10 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server))
nextcloudpi    | #11 /data/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
nextcloudpi    | #12 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OC\\Memcache\\Fac...')
nextcloudpi    | #13 /data/nextcloud/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OC\\Memcache\\Fac...', false)
nextcloudpi    | #14 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OC\\Memcache\\Fac...')
nextcloudpi    | #15 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(177): OC\AppFramework\Utility\SimpleContainer->get('OC\\Memcache\\Fac...')
nextcloudpi    | #16 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
nextcloudpi    | #17 /data/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
nextcloudpi    | #18 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OCP\\ICacheFacto...')
nextcloudpi    | #19 /data/nextcloud/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OCP\\ICacheFacto...', false)
nextcloudpi    | #20 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OCP\\ICacheFacto...')
nextcloudpi    | #21 /data/nextcloud/lib/private/Server.php(1031): OC\AppFramework\Utility\SimpleContainer->get('OCP\\ICacheFacto...')
nextcloudpi    | #22 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server))
nextcloudpi    | #23 /data/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
nextcloudpi    | #24 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OCP\\Lock\\ILocki...')
nextcloudpi    | #25 /data/nextcloud/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OCP\\Lock\\ILocki...', false)
nextcloudpi    | #26 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OCP\\Lock\\ILocki...')
nextcloudpi    | #27 /data/nextcloud/lib/private/Server.php(1990): OC\AppFramework\Utility\SimpleContainer->get('OCP\\Lock\\ILocki...')
nextcloudpi    | #28 /data/nextcloud/lib/private/Files/View.php(119): OC\Server->getLockingProvider()
nextcloudpi    | #29 /data/nextcloud/lib/private/Server.php(430): OC\Files\View->__construct()
nextcloudpi    | #30 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server))
nextcloudpi    | #31 /data/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
nextcloudpi    | #32 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OC\\Files\\Node\\H...')
nextcloudpi    | #33 /data/nextcloud/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OC\\Files\\Node\\H...', false)
nextcloudpi    | #34 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OC\\Files\\Node\\H...')
nextcloudpi    | #35 /data/nextcloud/lib/private/Server.php(1353): OC\AppFramework\Utility\SimpleContainer->get('OC\\Files\\Node\\H...')
nextcloudpi    | #36 /data/nextcloud/lib/base.php(588): OC\Server->boot()
nextcloudpi    | #37 /data/nextcloud/lib/base.php(1076): OC::init()
nextcloudpi    | #38 /data/nextcloud/console.php(49): require_once('/data/nextcloud...')
nextcloudpi    | #39 /data/nextcloud/occ(11): require_once('/data/nextcloud...')
nextcloudpi    | #40 {main}An unhandled exception has been thrown:
nextcloudpi    | Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Permission denied in /data/nextcloud/lib/private/DB/Connection.php:85
nextcloudpi    | Stack trace:
nextcloudpi    | #0 /data/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1486): OC\DB\Connection->connect()
nextcloudpi    | #1 /data/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1014): Doctrine\DBAL\Connection->getWrappedConnection()
nextcloudpi    | #2 /data/nextcloud/lib/private/DB/Connection.php(226): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM `...', Array, Array, NULL)
nextcloudpi    | #3 /data/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(210): OC\DB\Connection->executeQuery('SELECT * FROM `...', Array, Array)
nextcloudpi    | #4 /data/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(287): Doctrine\DBAL\Query\QueryBuilder->execute()
nextcloudpi    | #5 /data/nextcloud/lib/private/AppConfig.php(345): OC\DB\QueryBuilder\QueryBuilder->execute()
nextcloudpi    | #6 /data/nextcloud/lib/private/AppConfig.php(110): OC\AppConfig->loadConfigValues()
nextcloudpi    | #7 /data/nextcloud/lib/private/AppConfig.php(301): OC\AppConfig->getApps()
nextcloudpi    | #8 /data/nextcloud/lib/private/legacy/OC_App.php(965): OC\AppConfig->getValues(false, 'installed_versi...')
nextcloudpi    | #9 /data/nextcloud/lib/private/Server.php(682): OC_App::getAppVersions()
nextcloudpi    | #10 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server))
nextcloudpi    | #11 /data/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
nextcloudpi    | #12 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OC\\Memcache\\Fac...')
nextcloudpi    | #13 /data/nextcloud/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OC\\Memcache\\Fac...', false)
nextcloudpi    | #14 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OC\\Memcache\\Fac...')
nextcloudpi    | #15 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(177): OC\AppFramework\Utility\SimpleContainer->get('OC\\Memcache\\Fac...')
nextcloudpi    | #16 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
nextcloudpi    | #17 /data/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
nextcloudpi    | #18 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OCP\\ICacheFacto...')
nextcloudpi    | #19 /data/nextcloud/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OCP\\ICacheFacto...', false)
nextcloudpi    | #20 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OCP\\ICacheFacto...')
nextcloudpi    | #21 /data/nextcloud/lib/private/Server.php(1031): OC\AppFramework\Utility\SimpleContainer->get('OCP\\ICacheFacto...')
nextcloudpi    | #22 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server))
nextcloudpi    | #23 /data/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
nextcloudpi    | #24 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OCP\\Lock\\ILocki...')
nextcloudpi    | #25 /data/nextcloud/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OCP\\Lock\\ILocki...', false)
nextcloudpi    | #26 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OCP\\Lock\\ILocki...')
nextcloudpi    | #27 /data/nextcloud/lib/private/Server.php(1990): OC\AppFramework\Utility\SimpleContainer->get('OCP\\Lock\\ILocki...')
nextcloudpi    | #28 /data/nextcloud/lib/private/Files/View.php(119): OC\Server->getLockingProvider()
nextcloudpi    | #29 /data/nextcloud/lib/private/Server.php(430): OC\Files\View->__construct()
nextcloudpi    | #30 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server))
nextcloudpi    | #31 /data/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
nextcloudpi    | #32 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OC\\Files\\Node\\H...')
nextcloudpi    | #33 /data/nextcloud/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OC\\Files\\Node\\H...', false)
nextcloudpi    | #34 /data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query('OC\\Files\\Node\\H...')
nextcloudpi    | #35 /data/nextcloud/lib/private/Server.php(1353): OC\AppFramework\Utility\SimpleContainer->get('OC\\Files\\Node\\H...')
nextcloudpi    | #36 /data/nextcloud/lib/base.php(588): OC\Server->boot()
nextcloudpi    | #37 /data/nextcloud/lib/base.php(1076): OC::init()
nextcloudpi    | #38 /data/nextcloud/console.php(49): require_once('/data/nextcloud...')
nextcloudpi    | #39 /data/nextcloud/occ(11): require_once('/data/nextcloud...')
```

**Comment by nachoparker** [comment]
working fine here so you must be doing something wrong. Maybe check in the forums for help
