### ISSUE TITLE
pulling docker image 1.50.2, redis service not found, unable to start mariadb service

### ISSUE THREAD

**Issue by Colfenor** [nextcloud/nextcloudpi#1636]
Hi unfortunately pulling the current docker image (v 1.50.2) & running it results in services not starting,
mariadb, redis won't start, and interestingly `nano` does not seem to be installed on this image ?

<details>
<summary>NextCloudPi diagnostics</summary>

```

NextCloudPi version  v1.50.2
NextCloudPi image    NextCloudPi_docker_09-29-22
OS                   Debian GNU/Linux 11. 5.10.103-v7l+ (armv7l)
automount            no
USB devices          sda 
datadir              /data/nextcloud/data
data in SD           no
data filesystem      btrfs
data disk usage      78G/932G
rootfs usage         5.6G/59G
swapfile             /var/swap
dbdir                /data/database
Nextcloud check      error
HTTPD service        up
PHP service          up
MariaDB service      down
Redis service        down
HPB service          down
Postfix service      down
Internet check       ok
public IP            ***REMOVED SENSITIVE VALUE***
public IP            ***REMOVED SENSITIVE VALUE***
Port check 80        open (ipv4)
Port check 443       open (ipv4)
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
Interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
Uptime               16min

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

An unhandled exception has been thrown:
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory in /data-ro/nextcloud/lib/private/DB/Connection.php:139
Stack trace:
#0 /data-ro/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1519): OC\DB\Connection->connect()
#1 /data-ro/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1041): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /data-ro/nextcloud/lib/private/DB/Connection.php(261): Doctrine\DBAL\Connection->executeQuery()
#3 /data-ro/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(345): OC\DB\Connection->executeQuery()
#4 /data-ro/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(281): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /data-ro/nextcloud/lib/private/AppConfig.php(411): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /data-ro/nextcloud/lib/private/AppConfig.php(176): OC\AppConfig->loadConfigValues()
#7 /data-ro/nextcloud/lib/private/AppConfig.php(367): OC\AppConfig->getApps()
#8 /data-ro/nextcloud/lib/private/legacy/OC_App.php(983): OC\AppConfig->getValues()
#9 /data-ro/nextcloud/lib/private/Server.php(713): OC_App::getAppVersions()
#10 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}()
#11 /data-ro/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet()
#13 /data-ro/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#14 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#15 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(184): OC\AppFramework\Utility\SimpleContainer->get()
#16 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#17 /data-ro/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#18 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet()
#19 /data-ro/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#20 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#21 /data-ro/nextcloud/lib/private/Server.php(1105): OC\AppFramework\Utility\SimpleContainer->get()
#22 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}()
#23 /data-ro/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#24 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet()
#25 /data-ro/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#26 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#27 /data-ro/nextcloud/lib/private/Server.php(2082): OC\AppFramework\Utility\SimpleContainer->get()
#28 /data-ro/nextcloud/lib/private/Files/View.php(122): OC\Server->getLockingProvider()
#29 /data-ro/nextcloud/lib/private/Server.php(454): OC\Files\View->__construct()
#30 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}()
#31 /data-ro/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#32 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet()
#33 /data-ro/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#34 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#35 /data-ro/nextcloud/lib/private/Server.php(1445): OC\AppFramework\Utility\SimpleContainer->get()
#36 /data-ro/nextcloud/lib/base.php(602): OC\Server->boot()
#37 /data-ro/nextcloud/lib/base.php(1111): OC::init()
#38 /data-ro/nextcloud/console.php(48): require_once('...')
#39 /data-ro/nextcloud/occ(11): require_once('...')
#40 {main}
```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Tue Oct 11 21:39:06.033057 2022] [ssl:warn] [pid 116:tid 3069278816] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Oct 11 21:39:06.063322 2022] [ssl:warn] [pid 117:tid 3069278816] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Oct 11 21:39:06.072756 2022] [mpm_event:notice] [pid 117:tid 3069278816] AH00489: Apache/2.4.54 (Debian) OpenSSL/1.1.1n configured -- resuming normal operations
[Tue Oct 11 21:39:06.072876 2022] [core:notice] [pid 117:tid 3069278816] AH00094: Command line: '/usr/sbin/apache2'
[Tue Oct 11 21:41:30.208913 2022] [ssl:warn] [pid 116:tid 3069807200] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Oct 11 21:41:30.240099 2022] [ssl:warn] [pid 117:tid 3069807200] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Oct 11 21:41:30.244341 2022] [core:warn] [pid 117:tid 3069807200] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Oct 11 21:41:30.250172 2022] [mpm_event:notice] [pid 117:tid 3069807200] AH00489: Apache/2.4.54 (Debian) OpenSSL/1.1.1n configured -- resuming normal operations
[Tue Oct 11 21:41:30.250295 2022] [core:notice] [pid 117:tid 3069807200] AH00094: Command line: '/usr/sbin/apache2'

```
</details>

<details>
<summary>Database logs</summary>

```

tail: cannot open '/var/log/mysql/*.log' for reading: No such file or directory

```
</details>

<details>
<summary>Nextcloud logs</summary>

```

{"reqId":"c4QWAeiErk3eHrtlF0hB","level":1,"time":"2022-08-03T10:44:00+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAgent":"--","version":"23.0.2.1"}
{"reqId":"c4QWAeiErk3eHrtlF0hB","level":1,"time":"2022-08-03T10:44:23+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"--","version":"23.0.2.1"}
{"reqId":"c4QWAeiErk3eHrtlF0hB","level":1,"time":"2022-08-03T10:44:23+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"--","version":"23.0.6.1"}
{"reqId":"c4QWAeiErk3eHrtlF0hB","level":1,"time":"2022-08-03T10:44:23+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"--","version":"23.0.6.1"}
{"reqId":"c4QWAeiErk3eHrtlF0hB","level":1,"time":"2022-08-03T10:44:23+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"--","version":"23.0.6.1"}
{"reqId":"YurWp5vJ9n2Lhwbtsvp5rwAAAFQ","level":2,"time":"2022-08-03T20:12:23+00:00","remoteAddr":"44.238.73.246","user":"--","app":"core","method":"GET","url":"/login","message":"Login failed: '8hYTSUFk' (Remote IP: '44.238.73.246')","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"23.0.6.1"}
{"reqId":"YvaW4rV@mTRA3S965u8nKwAAAAY","level":3,"time":"2022-08-12T18:07:30+00:00","remoteAddr":"143.198.136.88","user":"--","app":"index","method":"PUT","url":"/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php","message":"\"put\" can only be accessed once if not application/x-www-form-urlencoded or application/json.","userAgent":"Go-http-client/1.1","version":"23.0.6.1","exception":{"Exception":"LogicException","Message":"\"put\" can only be accessed once if not application/x-www-form-urlencoded or application/json.","Code":0,"Trace":[{"file":"/data/nextcloud/lib/private/AppFramework/Http/Request.php","line":270,"function":"getContent","class":"OC\\AppFramework\\Http\\Request","type":"->","args":[]},{"file":"/data/nextcloud/lib/private/AppFramework/Http/Request.php","line":339,"function":"__get","class":"OC\\AppFramework\\Http\\Request","type":"->","args":["parameters"]},{"file":"/data/nextcloud/apps/text/lib/Service/DocumentService.php","line":119,"function":"getParam","class":"OC\\AppFramework\\Http\\Request","type":"->","args":["token"]},{"function":"__construct","class":"OCA\\Text\\Service\\DocumentService","type":"->","args":[{"__class__":"OCA\\Text\\Db\\DocumentMapper"},{"__class__":"OCA\\Text\\Db\\StepMapper"},{"__class__":"OCA\\Text\\Db\\SessionMapper"},{"__class__":"OC\\Files\\AppData\\AppData"},null,{"__class__":"OC\\Files\\Node\\LazyRoot"},{"__class__":"OC\\Memcache\\Factory"},{"__class__":"OC\\AppFramework\\Logger"},{"__class__":"OC\\Share20\\Manager"},{"__class__":"OC\\AppFramework\\Http\\Request"},{"__class__":"OC\\DirectEditing\\Manager"},{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"/data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"newInstanceArgs","class":"ReflectionClass","type":"->","args":[[{"__class__":"OCA\\Text\\Db\\DocumentMapper"},{"__class__":"OCA\\Text\\Db\\StepMapper"},{"__class__":"OCA\\Text\\Db\\SessionMapper"},{"__class__":"OC\\Files\\AppData\\AppData"},null,"And 7 more entries, set log level to debug to see all entries"]]},{"file":"/data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"__class__":"ReflectionClass","name":"OCA\\Text\\Service\\DocumentService"}]},{"file":"/data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Text\\Service\\DocumentService"]},{"file":"/data/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":463,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Text\\Service\\DocumentService"]},{"file":"/data/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":435,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Text\\Service\\DocumentService"]},{"file":"/data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Text\\Service\\DocumentService",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},[{"__class__":"ReflectionParameter","name":"request"},{"__class__":"ReflectionParameter","name":"sessionService"},"*** sensitive parameters replaced ***",{"__class__":"ReflectionParameter","name":"logger"},{"__class__":"ReflectionParameter","name":"encodingService"}]]},{"file":"/data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"__class__":"ReflectionClass","name":"OCA\\Text\\Service\\ApiService"}]},{"file":"/data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Text\\Service\\ApiService"]},{"file":"/data/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":463,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Text\\Service\\ApiService"]},{"file":"/data/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":435,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Text\\Service\\ApiService"]},{"file":"/data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Text\\Service\\ApiService",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},[{"__class__":"ReflectionParameter","name":"l10n"},{"__class__":"ReflectionParameter","name":"initialStateService"},"*** sensitive parameters replaced ***"]]},{"file":"/data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"__class__":"ReflectionClass","name":"OCA\\Text\\DirectEditing\\TextDirectEditor"}]},{"file":"/data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Text\\DirectEditing\\TextDirectEditor"]},{"file":"/data/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":463,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Text\\DirectEditing\\TextDirectEditor"]},{"file":"/data/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":435,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Text\\DirectEditing\\TextDirectEditor"]},{"file":"/data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Text\\DirectEditing\\TextDirectEditor",true]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map","args":[{"__class__":"Closure"},["*** sensitive parameters replaced ***"]]},{"file":"/data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"__class__":"ReflectionClass","name":"OCA\\Text\\Listeners\\RegisterDirectEditorEventListener"}]},{"file":"/data/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Text\\Listeners\\RegisterDirectEditorEventListener"]},{"file":"/data/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":463,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Text\\Listeners\\RegisterDirectEditorEventListener"]},{"file":"/data/nextcloud/lib/private/ServerContainer.php","line":145,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Text\\Listeners\\RegisterDirectEditorEventListener"]},{"file":"/data/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php","line":71,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OCA\\Text\\Listeners\\RegisterDirectEditorEventListener"]},{"file":"/data/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->","args":[{"__class__":"OCP\\DirectEditing\\RegisterDirectEditorEvent"},"OCP\\DirectEditing\\RegisterDirectEditorEvent",{"__class__":"Symfony\\Component\\EventDispatcher\\EventDispatcher"}]},{"file":"/data/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"}],"OCP\\DirectEditing\\RegisterDirectEditorEvent",{"__class__":"OCP\\DirectEditing\\RegisterDirectEditorEvent"}]},{"file":"/data/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OCP\\DirectEditing\\RegisterDirectEditorEvent"},"OCP\\DirectEditing\\RegisterDirectEditorEvent"]},{"file":"/data/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":100,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["OCP\\DirectEditing\\RegisterDirectEditorEvent",{"__class__":"OCP\\DirectEditing\\RegisterDirectEditorEvent"}]},{"file":"/data/nextcloud/apps/files/lib/Service/DirectEditingService.php","line":50,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OCP\\DirectEditing\\RegisterDirectEditorEvent"}]},{"file":"/data/nextcloud/apps/files/lib/Service/DirectEditingService.php","line":46,"function":"getDirectEditingCapabilitites","class":"OCA\\Files\\Service\\DirectEditingService","type":"->","args":[]},{"file":"/data/nextcloud/apps/files/lib/Capabilities.php","line":72,"function":"getDirectEditingETag","class":"OCA\\Files\\Service\\DirectEditingService","type":"->","args":[]},{"file":"/data/nextcloud/lib/private/CapabilitiesManager.php","line":69,"function":"getCapabilities","class":"OCA\\Files\\Capabilities","type":"->","args":[]},{"file":"/data/nextcloud/lib/private/Template/JSConfigHelper.php","line":190,"function":"getCapabilities","class":"OC\\CapabilitiesManager","type":"->","args":[]},{"file":"/data/nextcloud/lib/private/TemplateLayout.php","line":234,"function":"getConfig","class":"OC\\Template\\JSConfigHelper","type":"->","args":[]},{"file":"/data/nextcloud/lib/private/legacy/OC_Template.php","line":182,"function":"__construct","class":"OC\\TemplateLayout","type":"->","args":["guest","core"]},{"file":"/data/nextcloud/lib/private/Template/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->","args":[]},{"file":"/data/nextcloud/lib/base.php","line":788,"function":"printPage","class":"OC\\Template\\Base","type":"->","args":[]},{"file":"/data/nextcloud/lib/base.php","line":1089,"function":"init","class":"OC","type":"::","args":[]},{"file":"/data/nextcloud/index.php","line":34,"args":["/data/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/data/nextcloud/lib/private/AppFramework/Http/Request.php","Line":408,"CustomMessage":"--"}}
{"reqId":"YvxUAoYFn@AhCvuMb91e1gAAABA","level":2,"time":"2022-08-17T02:35:46+00:00","remoteAddr":"61.194.228.1","user":"--","app":"core","method":"GET","url":"/login","message":"Login failed: '8hYTSUFk' (Remote IP: '61.194.228.1')","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"23.0.6.1"}
{"reqId":"YwfEj4YFn@AhCvuMb91kEQAAAAY","level":2,"time":"2022-08-25T18:50:55+00:00","remoteAddr":"185.213.175.159","user":"--","app":"core","method":"POST","url":"/","message":"Login failed: '1KRJfSQj1MTnbGaPiTnuLE5J4FkDcQURe5' (Remote IP: '185.213.175.159')","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36","version":"23.0.6.1"}
{"reqId":"YwfEkIYFn@AhCvuMb91kEgAAABc","level":2,"time":"2022-08-25T18:50:56+00:00","remoteAddr":"185.213.175.159","user":"--","app":"core","method":"POST","url":"/","message":"Login failed: '0xd5da0980d74202be44c5cab9894b4f545aa7ec54' (Remote IP: '185.213.175.159')","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36","version":"23.0.6.1"}
{"reqId":"YwowjayRxV9Izw9NYbda3QAAAFI","level":2,"time":"2022-08-27T14:56:13+00:00","remoteAddr":"85.215.209.170","user":"--","app":"core","method":"GET","url":"/login","message":"Login failed: 'afiiskc' (Remote IP: '85.215.209.170')","userAgent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.9 Safari/537.36","version":"23.0.6.1"}
{"reqId":"Ywo0l6yRxV9Izw9NYbda5QAAAEM","level":2,"time":"2022-08-27T15:13:27+00:00","remoteAddr":"85.215.209.170","user":"--","app":"core","method":"GET","url":"/manager/html","message":"Login failed: 'afiiskc' (Remote IP: '85.215.209.170')","userAgent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.9 Safari/537.36","version":"23.0.6.1"}
{"reqId":"Yw8LfqyRxV9Izw9NYbdc@AAAAEg","level":2,"time":"2022-08-31T07:19:26+00:00","remoteAddr":"51.83.75.133","user":"--","app":"core","method":"GET","url":"/login","message":"Login failed: 'afiiskc' (Remote IP: '51.83.75.133')","userAgent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.9 Safari/537.36","version":"23.0.6.1"}
{"reqId":"Yw8PRayRxV9Izw9NYbdc@gAAAFE","level":2,"time":"2022-08-31T07:35:34+00:00","remoteAddr":"51.83.75.133","user":"--","app":"core","method":"GET","url":"/manager/html","message":"Login failed: 'afiiskc' (Remote IP: '51.83.75.133')","userAgent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.9 Safari/537.36","version":"23.0.6.1"}
{"reqId":"YxKVvoYFn@AhCvuMb91pRAAAAAc","level":2,"time":"2022-09-02T23:46:06+00:00","remoteAddr":"122.54.51.70","user":"--","app":"core","method":"GET","url":"/login","message":"Login failed: '8hYTSUFk' (Remote IP: '122.54.51.70')","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"23.0.6.1"}
{"reqId":"YxSEF4YFn@AhCvuMb91p@wAAAAM","level":2,"time":"2022-09-04T10:55:19+00:00","remoteAddr":"161.246.127.29","user":"--","app":"core","method":"GET","url":"/login","message":"Login failed: '8hYTSUFk' (Remote IP: '161.246.127.29')","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"23.0.6.1"}
{"reqId":"Yxbix4YFn@AhCvuMb91q1gAAABE","level":2,"time":"2022-09-06T06:03:51+00:00","remoteAddr":"54.76.122.216","user":"--","app":"core","method":"GET","url":"/api/v3/users","message":"Login failed: 'rocketskates' (Remote IP: '54.76.122.216')","userAgent":"Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36","version":"23.0.6.1"}
{"reqId":"YyZRpqyRxV9Izw9NYbdpjAAAAEU","level":2,"time":"2022-09-17T23:00:54+00:00","remoteAddr":"45.148.120.127","user":"--","app":"core","method":"POST","url":"/","message":"Login failed: '1GP8z4phw8zuE6n2S3s1XDdyPpjPjukRUg' (Remote IP: '45.148.120.127')","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36","version":"23.0.6.1"}
{"reqId":"YyZRp6yRxV9Izw9NYbdpjQAAAFE","level":2,"time":"2022-09-17T23:00:56+00:00","remoteAddr":"45.148.120.127","user":"--","app":"core","method":"POST","url":"/","message":"Login failed: '0x53abc07f287e73670cd1714dde6c3b351e64f3cb' (Remote IP: '45.148.120.127')","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36","version":"23.0.6.1"}
{"reqId":"Yyamv6yRxV9Izw9NYbdpzgAAAEQ","level":2,"time":"2022-09-18T05:03:59+00:00","remoteAddr":"139.59.128.123","user":"--","app":"core","method":"GET","url":"/login","message":"Login failed: '8hYTSUFk' (Remote IP: '139.59.128.123')","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"23.0.6.1"}

```
</details>

**Docker logs output:**

<details>

```

Starting PHP-fpm
Starting Apache
INFO: Docker container detected.
Starting mariaDB
2022-10-14 20:49:31 0 [Note] mysqld (mysqld 10.5.15-MariaDB-0+deb11u1) starting as process 248 ...
2022-10-14 20:49:31 0 [Warning] The parameter innodb_file_format is deprecated and has no effect. It may be removed in future releases. See https://mariadb.com/kb/en/library/xtradbinnodb-file-format/
2022-10-14 20:49:31 0 [Warning] The parameter innodb_buffer_pool_instances is deprecated and has no effect.
2022-10-14 20:49:31 0 [Note] InnoDB: Uses event mutexes
2022-10-14 20:49:31 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2022-10-14 20:49:31 0 [Note] InnoDB: Number of pools: 1
2022-10-14 20:49:31 0 [Note] InnoDB: Using generic crc32 instructions
2022-10-14 20:49:31 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
2022-10-14 20:49:31 0 [Note] InnoDB: Using Linux native AIO
2022-10-14 20:49:31 0 [Note] InnoDB: Initializing buffer pool, total size = 268435456, chunk size = 134217728
2022-10-14 20:49:31 0 [Note] InnoDB: Completed initialization of buffer pool
2022-10-14 20:49:31 0 [ERROR] InnoDB: Upgrade after a crash is not supported. The redo log was created with MariaDB 10.3.36.
2022-10-14 20:49:31 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2022-10-14 20:49:31 0 [Note] InnoDB: Starting shutdown...
2022-10-14 20:49:31 0 [ERROR] Plugin 'InnoDB' init function returned error.
2022-10-14 20:49:31 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2022-10-14 20:49:31 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-10-14 20:49:31 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2022-10-14 20:49:31 0 [ERROR] Aborting

```
</details>

**Comment by theCalcaholic** [comment]
The issue is actually that your mariadb database crashed while the last container was running (or stopping). You need to fix this, before the container will start normally. You can run arbitrary commands inside the container with `docker run --rm --entrypoint '' <your usual parameters> ownyourbits/nextcloudpi:latest <command>`.

You could try the advice given here https://bbs.archlinux.org/viewtopic.php?id=259364 (e.g. `docker run --rm --entrypoint '' <your usual parameters> ownyourbits/nextcloudpi:latest mysql_upgrade`).

**Comment by Colfenor** [comment]
> The issue is actually that your mariadb database crashed while the last container was running (or stopping). You need to fix this, before the container will start normally. You can run arbitrary commands inside the container with `docker run --rm --entrypoint '' <your usual parameters> ownyourbits/nextcloudpi:latest <command>`.

Thanks a lot for your reply :) hm the problem is I cannot get mariadb to run inside the container. After pulling the docker nextcloudpi image from the hub, I started the container using this cmd: 

`docker run -d -p 4443:4443 -p 443:443 -p 80:80 -v my/media/path --name nextcloudpi --ip=my_ip ownyourbits/nextcloudpi:latest my_domain`

after that the `docker logs CONTAINER_ID` cmd reveals that mariadb (v10.5.15) failed to start properly.
Then I spawned a bash shell inside the container and tried to restart mariadb manually without success (`service mariadb start`), interestingly `ls /var/lib/` reveals that there is no mysql folder at all and running `systemctl` yields:
```
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

> You could try the advice given here https://bbs.archlinux.org/viewtopic.php?id=259364 (e.g. `docker run --rm --entrypoint '' <your usual parameters> ownyourbits/nextcloudpi:latest mysql_upgrade`).

unfortunately mysql_upgrade doesn't work since it requires mariadb to be running

**Comment by Colfenor** [comment]
I could fix the issue of the broken mariadb & redis by first backing up and then deleting the folders `ncdata` and `ncdatabase` in the nextcloudpi used mounted external drive path, removing all docker containers and starting off fresh with a new `docker run <various params> ...` command
