### ISSUE TITLE
Unable to successfully activate NextcloudPi Docker

### ISSUE THREAD

**Issue by OfficialMuffin** [nextcloud/nextcloudpi#1666]
When accessing the activation page, then activating ncp, `NextCloudPi not yet initialized, trying again in a few seconds ...` is displayed.
I followed instructions [here](https://help.nextcloud.com/t/guide-to-getting-started-with-nextcloudpi-docker-in-2020/93396). However, my server runs OpenMediaVault with already mounted data drives and NextcloudPi is running inside a docker container with the `-v` flag mounting the data drive for the docker container to use as a volume. Could this be a permissions issue? Or will the logs state that it is?

**System information**

<details>
<summary>NextCloudPi diagnostics</summary>

```

/usr/local/bin/ncp-diag: line 86: -1: substring expression < 0
/usr/local/bin/ncp-diag: line 86: -1: substring expression < 0
NextCloudPi version  v1.50.2
NextCloudPi image    NextCloudPi_docker_09-29-22
OS                   Debian GNU/Linux 11. 5.15.76-v8+ (aarch64)
automount            no
USB devices          sda sdb
datadir              /data/nextcloud/data (doesn't exist)
rootfs usage         6.2G/15G
swapfile             /var/swap
dbdir                /data/database (doesn't exist)
Nextcloud check      error
HTTPD service        up
PHP service          up
MariaDB service      down
Redis service        down
HPB service          down
Postfix service      down
Internet check       ok
public IP            ***REMOVED SENSITIVE VALUE***
public IP            ***REMOVED SENSITIVE VALUE***
Port check 80
Port check 443
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
Interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
Uptime               1day

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

An unhandled exception has been thrown:
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory in /data-ro/nextcloud/lib/private/DB/Connection.php:139
Stack trace:
#0 /data-ro/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1519): OC\DB\Connection->connect()
#1 /data-ro/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1041): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /data-ro/nextcloud/lib/private/DB/Connection.php(261): Doctrine\DBAL\Connection->executeQuery()
#3 /data-ro/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(345): OC\DB\Connection->executeQuery()
#4 /data-ro/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(281): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /data-ro/nextcloud/lib/private/AppConfig.php(411): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /data-ro/nextcloud/lib/private/AppConfig.php(176): OC\AppConfig->loadConfigValues()
#7 /data-ro/nextcloud/lib/private/AppConfig.php(367): OC\AppConfig->getApps()
#8 /data-ro/nextcloud/lib/private/legacy/OC_App.php(983): OC\AppConfig->getValues()
#9 /data-ro/nextcloud/lib/private/Server.php(713): OC_App::getAppVersions()
#10 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}()
#11 /data-ro/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet()
#13 /data-ro/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#14 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#15 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(184): OC\AppFramework\Utility\SimpleContainer->get()
#16 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#17 /data-ro/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#18 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet()
#19 /data-ro/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#20 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#21 /data-ro/nextcloud/lib/private/Server.php(1105): OC\AppFramework\Utility\SimpleContainer->get()
#22 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}()
#23 /data-ro/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#24 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet()
#25 /data-ro/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#26 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#27 /data-ro/nextcloud/lib/private/Server.php(2082): OC\AppFramework\Utility\SimpleContainer->get()
#28 /data-ro/nextcloud/lib/private/Files/View.php(122): OC\Server->getLockingProvider()
#29 /data-ro/nextcloud/lib/private/Server.php(454): OC\Files\View->__construct()
#30 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}()
#31 /data-ro/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#32 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet()
#33 /data-ro/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#34 /data-ro/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#35 /data-ro/nextcloud/lib/private/Server.php(1445): OC\AppFramework\Utility\SimpleContainer->get()
#36 /data-ro/nextcloud/lib/base.php(602): OC\Server->boot()
#37 /data-ro/nextcloud/lib/base.php(1111): OC::init()
#38 /data-ro/nextcloud/console.php(48): require_once('...')
#39 /data-ro/nextcloud/occ(11): require_once('...')
#40 {main}
```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Mon Nov 28 00:56:06.216532 2022] [authz_host:error] [pid 121:tid 548018987392] [client 10.6.0.3:13627] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 00:56:19.109891 2022] [authz_host:error] [pid 122:tid 548060950912] [client 10.6.0.3:13629] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 00:56:32.297992 2022] [authz_host:error] [pid 122:tid 548060950912] [client 10.6.0.3:13632] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 00:56:45.233308 2022] [authz_host:error] [pid 121:tid 548018987392] [client 10.6.0.3:13634] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 00:56:58.072730 2022] [authz_host:error] [pid 121:tid 548018987392] [client 10.6.0.3:13637] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 00:57:11.240435 2022] [authz_host:error] [pid 122:tid 548060950912] [client 10.6.0.3:13640] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 00:57:24.342311 2022] [authz_host:error] [pid 121:tid 548018987392] [client 10.6.0.3:13642] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 00:57:37.047757 2022] [authz_host:error] [pid 122:tid 548060950912] [client 10.6.0.3:13644] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 00:57:50.230261 2022] [authz_host:error] [pid 122:tid 548060950912] [client 10.6.0.3:13646] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 00:58:04.170640 2022] [authz_host:error] [pid 122:tid 548060950912] [client 10.6.0.3:13648] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 00:58:17.127836 2022] [authz_host:error] [pid 122:tid 548060950912] [client 10.6.0.3:13650] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 00:58:30.288097 2022] [authz_host:error] [pid 121:tid 548018987392] [client 10.6.0.3:13652] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 00:58:44.139348 2022] [authz_host:error] [pid 121:tid 548018987392] [client 10.6.0.3:13654] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 00:58:57.071183 2022] [authz_host:error] [pid 122:tid 548060950912] [client 10.6.0.3:13656] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 00:59:10.053217 2022] [authz_host:error] [pid 121:tid 548018987392] [client 10.6.0.3:13658] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 00:59:23.247786 2022] [authz_host:error] [pid 122:tid 548060950912] [client 10.6.0.3:13660] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 00:59:36.218441 2022] [authz_host:error] [pid 121:tid 548018987392] [client 10.6.0.3:13663] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 00:59:49.058623 2022] [authz_host:error] [pid 121:tid 548018987392] [client 10.6.0.3:13665] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 01:00:02.149693 2022] [authz_host:error] [pid 122:tid 548060950912] [client 10.6.0.3:13669] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Mon Nov 28 01:00:15.161908 2022] [authz_host:error] [pid 122:tid 548060950912] [client 10.6.0.3:13673] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name

```
</details>

<details>
<summary>Database logs</summary>

```

tail: cannot open '/var/log/mysql/*.log' for reading: No such file or directory

```
</details>

<details>
<summary>Nextcloud logs</summary>

```

tail: cannot open '/data/nextcloud/data/nextcloud.log' for reading: No such file or directory

```
</details>

**Comment by OfficialMuffin** [comment]
Turns out it may have been a permissions issue. I made another directory outside of the OMV shares and changed the directory in the docker run command to match this. Closing as issue solved
