### ISSUE TITLE
Nextcloud 503 error

### ISSUE THREAD

**Issue by shubham8550** [nextcloud/nextcloudpi#1774]
![image](https://user-images.githubusercontent.com/35478603/236462296-9487a543-9dd0-40d3-bb3f-df040ece3892.png)

so I installed Next Cloud using curl today  and it was running good until I logged in ncp-web on port 4443 and when I finished wizard  main web (NC on port 80) stopped working and got this err 

I have also seen 

```
Using 715339776 for PHP max memory
Installing template 'php/90-ncp.ini.sh'...
System config value trusted_domains => 3 set to string nextcloudpi
System config value overwrite.cli.url set to string https://nextcloudpi/
Using 16 PHP threads
Installing template 'php/pool.d.www.conf.sh'...
System config value trusted_proxies => 11 set to string 127.0.0.1
System config value trusted_proxies => 12 set to string ::1
System config value trusted_proxies => 13 set to string nextcloudpi
Installing template 'mysql/91-ncp.cnf.sh'...
System config value trusted_proxies => 14 set to empty string
Setup notify_push (attempt 1/5)
An unhandled exception has been thrown:
RedisException: read error on connection to /var/run/redis/redis.sock:0 in /var/www/nextcloud/lib/private/RedisFactory.php:143
Stack trace:
#0 /var/www/nextcloud/lib/private/RedisFactory.php(143): Redis->auth()
#1 /var/www/nextcloud/lib/private/RedisFactory.php(178): OC\RedisFactory->create()
#2 /var/www/nextcloud/lib/private/Memcache/Redis.php(50): OC\RedisFactory->getInstance()
#3 /var/www/nextcloud/lib/private/Memcache/Redis.php(56): OC\Memcache\Redis->getCache()
#4 /var/www/nextcloud/lib/private/App/InfoParser.php(58): OC\Memcache\Redis->get()
#5 /var/www/nextcloud/lib/private/App/AppManager.php(506): OC\App\InfoParser->parse()
#6 /var/www/nextcloud/lib/private/legacy/OC_App.php(607): OC\App\AppManager->getAppInfo()
#7 /var/www/nextcloud/lib/private/AppFramework/App.php(71): OC_App::getAppInfo()
#8 /var/www/nextcloud/lib/private/legacy/OC_App.php(291): OC\AppFramework\App::buildAppNamespace()
#9 /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php(119): OC_App::registerAutoloading()
#10 /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php(90): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#11 /var/www/nextcloud/lib/base.php(688): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#12 /var/www/nextcloud/lib/base.php(1165): OC::init()
#13 /var/www/nextcloud/console.php(48): require_once('...')
#14 /var/www/nextcloud/occ(11): require_once('...')
```
this issue in logs

### So far i tried

- reboot 
- toggling Maintenance mode
- NC re-init

**System information**

<details>
<summary>NextcloudPi diagnostics</summary>

```

NextcloudPi version  v1.52.0
NextcloudPi image    NextcloudPi_05-05-23
OS                   Debian GNU/Linux 11. 6.1.21-v8+ (aarch64)
automount            no
USB devices          none
datadir              /var/www/nextcloud/data
data in SD           yes
data filesystem      ext2/ext3
data disk usage      2.9G/59G
rootfs usage         2.9G/59G
swapfile             /var/swap
dbdir                /var/lib/mysql
Nextcloud check      ok
Nextcloud version    26.0.1.1
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
HPB service          down
Postfix service      up
Internet check       ok
Public IPv4          ***REMOVED SENSITIVE VALUE***
Public IPv6          ***REMOVED SENSITIVE VALUE***
Port 80              closed
Port 443             closed
IP                   ***REMOVED SENSITIVE VALUE***
Gateway              ***REMOVED SENSITIVE VALUE***
Interface            eth0
Certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
Uptime               4min

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "7": "nextcloudpi",
            "5": "nextcloudpi.local",
            "8": "nextcloudpi.lan",
            "3": "nextcloudpi",
            "11": "2401:4900:1c8e:2015:3286:c31b:ed0b:593e",
            "1": "192.168.1.99",
            "14": "nextcloudpi"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.1.1",
        "overwrite.cli.url": "https:\/\/nextcloudpi\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/var\/www\/nextcloud\/data\/tmp",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "overwriteprotocol": "https",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Fri May 05 17:57:47.605901 2023] [ssl:warn] [pid 520:tid 547861746752] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Fri May 05 17:57:47.685282 2023] [ssl:error] [pid 520:tid 547861746752] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=raspberrypi / issuer: CN=raspberrypi / serial: 054B52422F67EB422FC9717CB784045670524D32 / notbefore: May  5 10:37:00 2023 GMT / notafter: May  2 10:37:00 2033 GMT]
[Fri May 05 17:57:47.685413 2023] [ssl:error] [pid 520:tid 547861746752] AH02604: Unable to configure certificate localhost:4443:0 for stapling
[Fri May 05 17:57:47.880592 2023] [ssl:warn] [pid 817:tid 547861746752] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Fri May 05 17:57:47.881479 2023] [ssl:error] [pid 817:tid 547861746752] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=raspberrypi / issuer: CN=raspberrypi / serial: 054B52422F67EB422FC9717CB784045670524D32 / notbefore: May  5 10:37:00 2023 GMT / notafter: May  2 10:37:00 2033 GMT]
[Fri May 05 17:57:47.881588 2023] [ssl:error] [pid 817:tid 547861746752] AH02604: Unable to configure certificate localhost:4443:0 for stapling
[Fri May 05 17:57:47.904470 2023] [mpm_event:notice] [pid 817:tid 547861746752] AH00489: Apache/2.4.56 (Debian) OpenSSL/1.1.1n configured -- resuming normal operations
[Fri May 05 17:57:47.904777 2023] [core:notice] [pid 817:tid 547861746752] AH00094: Command line: '/usr/sbin/apache2'
[Fri May 05 17:57:52.249719 2023] [authz_host:error] [pid 818:tid 547650396544] [remote 192.168.1.7:65033] AH01753: access check of 'localhost' to /ncp-output.php failed, reason: unable to get the remote host name
[Fri May 05 17:57:52.251351 2023] [proxy:error] [pid 818:tid 547650396544] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php8.1-fpm.sock (*:80) failed
[Fri May 05 17:57:52.251533 2023] [proxy_fcgi:error] [pid 818:tid 547650396544] [remote 192.168.1.7:65033] AH01079: failed to make connection to backend: httpd-UDS
[Fri May 05 18:11:56.739355 2023] [mpm_event:notice] [pid 817:tid 547861746752] AH00492: caught SIGWINCH, shutting down gracefully
[Fri May 05 18:12:25.310872 2023] [ssl:warn] [pid 514:tid 547678635072] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Fri May 05 18:12:25.362259 2023] [ssl:error] [pid 514:tid 547678635072] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=raspberrypi / issuer: CN=raspberrypi / serial: 054B52422F67EB422FC9717CB784045670524D32 / notbefore: May  5 10:37:00 2023 GMT / notafter: May  2 10:37:00 2033 GMT]
[Fri May 05 18:12:25.362329 2023] [ssl:error] [pid 514:tid 547678635072] AH02604: Unable to configure certificate localhost:4443:0 for stapling
[Fri May 05 18:12:25.489510 2023] [ssl:warn] [pid 817:tid 547678635072] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Fri May 05 18:12:25.489906 2023] [ssl:error] [pid 817:tid 547678635072] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=raspberrypi / issuer: CN=raspberrypi / serial: 054B52422F67EB422FC9717CB784045670524D32 / notbefore: May  5 10:37:00 2023 GMT / notafter: May  2 10:37:00 2033 GMT]
[Fri May 05 18:12:25.489939 2023] [ssl:error] [pid 817:tid 547678635072] AH02604: Unable to configure certificate localhost:4443:0 for stapling
[Fri May 05 18:12:25.499083 2023] [mpm_event:notice] [pid 817:tid 547678635072] AH00489: Apache/2.4.56 (Debian) OpenSSL/1.1.1n configured -- resuming normal operations
[Fri May 05 18:12:25.499263 2023] [core:notice] [pid 817:tid 547678635072] AH00094: Command line: '/usr/sbin/apache2'

```
</details>

<details>
<summary>Database logs</summary>

```

tail: cannot open '/var/log/mysql/*.log' for reading: No such file or directory

```
</details>

<details>
<summary>Nextcloud logs</summary>

```


```
</details>

**Comment by shubham8550** [comment]
fixed (php  version got changed somehow)

used update-alternative and changed php version back and done
