### ISSUE TITLE
sudo ncp-dist-upgrade fails to dphys-swapfile

### ISSUE THREAD

**Issue by qasamppa** [nextcloud/nextcloudpi#2027]
**System information**

sudo ncp-report
<--! Paste this in GitHub report -->

<details>
<summary>NextcloudPi diagnostics</summary>

```

NextcloudPi version  v1.55.3
NextcloudPi image    NextCloudPi_11-27-20
OS                   Debian GNU/Linux 11. 6.1.21-v8+ (aarch64)
automount            yes
USB devices          sda sdb

data disk usage      115G/932G
rootfs usage         13G/59G
swapfile             /var/swap
dbdir                /var/lib/mysql/
Nextcloud check      ok
Nextcloud version    28.0.14.1
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
HPB service          down
Postfix service      up
Internet check       ok
Public IPv4          ***REMOVED SENSITIVE VALUE***
Public IPv6          ***REMOVED SENSITIVE VALUE***
Port 80              closed
Port 443             closed
IP                   ***REMOVED SENSITIVE VALUE***
Gateway              ***REMOVED SENSITIVE VALUE***
Interface            eth0
Certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
Uptime               5min

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

Nextcloud is in maintenance mode, no apps are loaded.
Commands provided by apps are unavailable.
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "5": "nextcloudpi.local",
            "7": "nextcloudpi",
            "8": "nextcloudpi.lan",
            "11": "178.75.141.165",
            "1": "192.168.68.99",
            "3": "nextcloudpi",
            "": "nextcloudpi",
            "14": "nextcloudpi",
            "21": "192.168.1.108",
            "20": "192.168.68.1"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.14.1",
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/media\/primaryDrive\/ncdata\/tmp",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "overwriteprotocol": "https",
        "loglevel": "2",
        "log_type": "file",
        "maintenance": true,
        "logfile": "\/media\/primaryDrive\/ncdata\/nextcloud.log",
        "app_install_overwrite": [
            "keeporsweep"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "data-fingerprint": "ebd7cc4d94c8602cc395e0769d09ab47",
        "theme": ""
    }
}

```
</details>

<details>
<summary>HTTPd logs</summary>

```


Apache/2.4.62 (Debian) OpenSSL/1.1.1w configured -- resuming normal operations
[Wed Dec 25 00:00:10.029041 2024] [core:notice] [pid 930:tid 930] AH00094: Command line: '/usr/sbin/apache2'
[Wed Dec 25 17:15:21.498189 2024] [mpm_event:notice] [pid 930:tid 930] AH00492: caught SIGWINCH, shutting down gracefully
[Wed Dec 25 17:15:32.554864 2024] [ssl:warn] [pid 535:tid 535] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Wed Dec 25 17:15:32.561238 2024] [ssl:error] [pid 535:tid 535] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=archlinux / issuer: CN=archlinux / serial: 0112307086B5A933D74576F54C8FD74C8207A8AF / notbefore: Nov 27 22:55:31 2020 GMT / notafter: Nov 25 22:55:31 2030 GMT]
[Wed Dec 25 17:15:32.561313 2024] [ssl:error] [pid 535:tid 535] AH02604: Unable to configure certificate localhost:4443:0 for stapling
[Wed Dec 25 17:15:32.624278 2024] [ssl:warn] [pid 926:tid 926] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Wed Dec 25 17:15:32.624622 2024] [ssl:error] [pid 926:tid 926] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=archlinux / issuer: CN=archlinux / serial: 0112307086B5A933D74576F54C8FD74C8207A8AF / notbefore: Nov 27 22:55:31 2020 GMT / notafter: Nov 25 22:55:31 2030 GMT]
[Wed Dec 25 17:15:32.624667 2024] [ssl:error] [pid 926:tid 926] AH02604: Unable to configure certificate localhost:4443:0 for stapling
[Wed Dec 25 17:15:32.632541 2024] [mpm_event:notice] [pid 926:tid 926] AH00489: Apache/2.4.62 (Debian) OpenSSL/1.1.1w configured -- resuming normal operations
[Wed Dec 25 17:15:32.632663 2024] [core:notice] [pid 926:tid 926] AH00094: Command line: '/usr/sbin/apache2'

```
</details>

<details>
<summary>Database logs</summary>

```

2022-08-17 20:04:05 0 [ERROR] mysql.user: 1 client is using or hasn't closed the table properly
2022-08-17 20:04:05 0 [ERROR] mysqld: Table './mysql/db' is marked as crashed and should be repaired
2022-08-17 20:04:05 0 [Warning] Checking table:   './mysql/db'
2022-08-17 20:04:05 0 [ERROR] mysql.db: 1 client is using or hasn't closed the table properly
2022-08-17 20:04:06 0 [Note] Reading of all Master_info entries succeeded
2022-08-17 20:04:06 0 [Note] Added new Master_info '' to hash table
2022-08-17 20:04:06 0 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.3.34-MariaDB-0+deb10u1'  socket: '/run/mysqld/mysqld.sock'  port: 3306  Debian 10
2022-08-17 20:04:06 0 [Note] InnoDB: Buffer pool(s) load completed at 220817 20:04:06
2022-08-17 20:04:18 9 [Warning] Aborted connection 9 to db: 'nextcloud' user: 'ncadmin' host: 'localhost' (Got an error reading communication packets)
2022-08-17 20:12:36 0 [Note] /usr/sbin/mysqld (initiated by: unknown): Normal shutdown
2022-08-17 20:12:36 0 [Note] Event Scheduler: Purging the queue. 0 events
2022-08-17 20:12:36 0 [Note] InnoDB: FTS optimize thread exiting.
2022-08-17 20:12:36 0 [Note] InnoDB: Starting shutdown...
2022-08-17 20:12:36 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2022-08-17 20:12:36 0 [Note] InnoDB: Buffer pool(s) dump completed at 220817 20:12:36
2022-08-17 20:12:38 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2022-08-17 20:12:38 0 [Note] InnoDB: Shutdown completed; log sequence number 8625118917; transaction id 41318906
2022-08-17 20:12:38 0 [Note] /usr/sbin/mysqld: Shutdown complete


```
</details>

<details>
<summary>Nextcloud logs</summary>

```


moteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"OC\\Repair\\Events\\RepairStepEvent: Repair step: Remove old dashboard app config data","userAgent":"--","version":"28.0.12.2","data":{"app":"updater"}}
{"reqId":"EUa4CVe94hoMjZNVf9l5","level":1,"time":"2024-12-13T06:57:47+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"OC\\Repair\\Events\\RepairStepEvent: Repair step: Add job to cleanup the bruteforce entries","userAgent":"--","version":"28.0.12.2","data":{"app":"updater"}}
{"reqId":"EUa4CVe94hoMjZNVf9l5","level":1,"time":"2024-12-13T06:57:47+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"OC\\Repair\\Events\\RepairStepEvent: Repair step: Queue a one-time job to check for user uploaded certificates","userAgent":"--","version":"28.0.12.2","data":{"app":"updater"}}
{"reqId":"EUa4CVe94hoMjZNVf9l5","level":1,"time":"2024-12-13T06:57:47+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"OC\\Repair\\Events\\RepairStepEvent: Repair step: Repair DAV shares","userAgent":"--","version":"28.0.12.2","data":{"app":"updater"}}
{"reqId":"EUa4CVe94hoMjZNVf9l5","level":1,"time":"2024-12-13T06:57:47+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"OC\\Repair\\Events\\RepairStepEvent: Repair step: Add background job to set the lookup server share state for users","userAgent":"--","version":"28.0.12.2","data":{"app":"updater"}}
{"reqId":"EUa4CVe94hoMjZNVf9l5","level":1,"time":"2024-12-13T06:57:47+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"OC\\Repair\\Eve
moteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAgent":"--","version":"28.0.12.2","data":{"app":"updater"}}
{"reqId":"EUa4CVe94hoMjZNVf9l5","level":1,"time":"2024-12-13T06:58:01+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"--","version":"28.0.12.2","data":{"app":"updater"}}
{"reqId":"EUa4CVe94hoMjZNVf9l5","level":1,"time":"2024-12-13T06:58:01+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"--","version":"28.0.14.1","data":{"app":"updater"}}
{"reqId":"EUa4CVe94hoMjZNVf9l5","level":1,"time":"2024-12-13T06:58:01+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"--","version":"28.0.14.1","data":{"app":"updater"}}
{"reqId":"EUa4CVe94hoMjZNVf9l5","level":1,"time":"2024-12-13T06:58:01+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"--","version":"28.0.14.1","data":{"app":"updater"}}
{"reqId":"NDRE6KyUL6j1Bd1ppw0D","level":3,"time":"2024-12-13T07:00:03+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\Survey_Client\\BackgroundJobs\\AdminNotification, arguments: )","userAgent":"--","version":"28.0.14.1","exception":{"Exception":"InvalidArgumentException","Message":"The given link is invalid","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/survey_client/lib/BackgroundJobs/AdminNotification.php","line":56,"function":"setLink","class":"OC\\Notification\\Action","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":81,"function":"run","class":"OCA\\Survey_Client\\BackgroundJobs\\AdminNotification","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php","line":61,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php","line":47,"function":"start","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":154,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"}],"File":"/var/www/nextcloud/lib/private/Notification/Action.php","Line":127,"message":"Error while running background job (class: OCA\\Survey_Client\\BackgroundJobs\\AdminNotification, arguments: )","exception":{},"CustomMessage":"Error while running background job (class: OCA\\Survey_Client\\BackgroundJobs\\AdminNotification, arguments: )"}}

```
</details>

root@nextcloudpi:/home/pi#
[ncp-distu0:bash*

**Comment by qasamppa** [comment]
Seems, that output of 'sudo ncp-dist-upgrade' command didn't succeeded, so here it is.

>>> ATTENTION <<<
This is a dangerous process that is only guaranteed to work properly if you
have not made manual changes in the system. Backup the SD card first and
proceed at your own risk.

Note that this is not a requirement for NCP to continue working properly.
The current distribution will keep receiving updates for some time.

Do you want to continue? [y/N]
yMaintenance mode already enabled
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 https://packages.sury.org/php bookworm InRelease
Hit:5 http://archive.raspberrypi.org/debian bookworm InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package 'libc-dev-bin' is not installed, so not removed
                                                       0 upgraded, 0 newly installed, 0 to remove and 32 not upgraded.
                                      10 not fully installed or removed.
                                                                        After this operation, 0 B of additional disk space will be used.
                                                        Setting up libc-l10n (2.36-9+rpt2+deb12u9) ...
Setting up firmware-atheros (1:20230625-2+rpt3) ...
Setting up firmware-misc-nonfree (1:20230625-2+rpt3) ...
Setting up locales (2.36-9+rpt2+deb12u9) ...
Generating locales (this might take a while)...
  en_GB.UTF-8... done
Generation complete.
Setting up php8.1 (8.1.31-1+0~20241121.67+debian12~1.gbp9e3dc4) ...
Setting up firmware-brcm80211 (1:20230625-2+rpt3) ...
Setting up firmware-realtek (1:20230625-2+rpt3) ...
Setting up firmware-libertas (1:20230625-2+rpt3) ...
Setting up initramfs-tools-core (0.142+rpt2+deb12u1) ...
Installing new version of config file /etc/initramfs-tools/initramfs.conf ...
Setting up initramfs-tools (0.142+rpt2+deb12u1) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for initramfs-tools (0.142+rpt2+deb12u1) ...
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages have been kept back:
  alsa-utils console-setup console-setup-linux dpkg keyboard-configuration
  libdpkg-perl libgd3 openssl php-common php8.1-bcmath php8.1-bz2 php8.1-cli
  php8.1-common php8.1-curl php8.1-fpm php8.1-gd php8.1-gmp php8.1-intl
  php8.1-ldap php8.1-mbstring php8.1-mysql php8.1-opcache php8.1-readline
  php8.1-redis php8.1-xml php8.1-zip raspberrypi-net-mods raspberrypi-sys-mods
  raspi-config raspinfo rpi-eeprom
The following packages will be upgraded:
  dphys-swapfile
dpkg-deb: error: archive '/var/cache/apt/archives/dphys-swapfile_20100506-7.1+rpt3_all.deb' uses unknown compression for member 'control.tar.zst', giving up
Traceback (most recent call last):
  File "/usr/share/apt-listchanges/DebianFiles.py", line 124, in readdeb
    output = subprocess.check_output(command)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dpkg-deb', '-f', '/var/cache/apt/archives/dphys-swapfile_20100506-7.1+rpt3_all.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/apt-listchanges", line 323, in <module>
    main(config)
  File "/usr/bin/apt-listchanges", line 104, in main
    pkg = DebianFiles.Package(deb)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 358, in __init__
    parser.readdeb(self.path)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 127, in readdeb
    raise RuntimeError(_("Error processing '%(what)s': %(errmsg)s") %
RuntimeError: Error processing '/var/cache/apt/archives/dphys-swapfile_20100506-7.1+rpt3_all.deb': Command '['dpkg-deb', '-f', '/var/cache/apt/archives/dphys-swapfile_20100506-7.1+rpt3_all.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.
apt-listchanges: Reading changelogs...
1 upgraded, 0 newly installed, 0 to remove and 31 not upgraded.
                                                               Need to get 0 B/22.6 kB of archives.
                   After this operation, 2,048 B of additional disk space will be used.
       dpkg-deb: error: archive '/var/cache/apt/archives/dphys-swapfile_20100506-7.1+rpt3_all.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /var/cache/apt/archives/dphys-swapfile_20100506-7.1+rpt3_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/dphys-swapfile_20100506-7.1+rpt3_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@nextcloudpi:/home/pi#

**Comment by qasamppa** [comment]
pi@nextcloudpi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
pi@nextcloudpi:~ $ sudo apt-get install zstd
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
zstd is already the newest version (1.4.8+dfsg-2.1).
0 upgraded, 0 newly installed, 0 to remove and 28 not upgraded.
pi@nextcloudpi:~ $
