### ISSUE TITLE
No Access Again!

### ISSUE THREAD

**Issue by deljones** [nextcloud/nextcloudpi#335]
Hi all..

I don't tinker aroind or play with my NC instance, if its running I leave it and use it. However there has been an auto update, again, and now I have no access...

Here is the output of:  systemctl status nc-automount-links

NextCloudPi v0.43.1 is up to date
pi@raspberrypi:~ $ systemctl status nc-automount-links
● nc-automount-links.service - Monitor /media for mountpoints and create USBdriv
   Loaded: loaded (/usr/lib/systemd/system/nc-automount-links.service; enabled;
   Active: active (running) since Tue 2017-12-26 23:59:49 UTC; 11h ago
 Main PID: 436 (nc-automount-li)
   CGroup: /system.slice/nc-automount-links.service
           ├─436 /bin/bash /usr/local/etc/nc-automount-links-mon
           ├─464 inotifywait --monitor --event create --event delete --format %f
           ├─465 grep --line-buffered ISDIR
           └─466 /bin/bash /usr/local/etc/nc-automount-links-mon

Dec 26 23:59:49 raspberrypi systemd[1]: Started Monitor /media for mountpoints a
Dec 26 23:59:49 raspberrypi nc-automount-links-mon[436]: Setting up watches.
Dec 26 23:59:49 raspberrypi nc-automount-links-mon[436]: Watches established.
Dec 26 23:59:54 raspberrypi nc-automount-links-mon[436]: ncbackup1 DELETE,ISDIR
Dec 26 23:59:54 raspberrypi nc-automount-links-mon[436]: myCloudDrive1 DELETE,IS
Dec 26 23:59:55 raspberrypi nc-automount-links-mon[436]: myCloudDrive1 CREATE,IS
Dec 26 23:59:55 raspberrypi nc-automount-links-mon[436]: ncbackup1 CREATE,ISDIR

I can see all the diretories on my HDD on USB
sudo ncp-report give the following:

NextCloudPi v0.43.1 is up to date
pi@raspberrypi:~ $ sudo ncp-report
<--! Paste this in GitHub report -->

<details>
<summary>NextCloudPi diagnostics</summary>

```

NextCloudPi version  v0.43.1
NextCloudPi image    NextCloudPi_09-12-17
distribution         Raspbian GNU/Linux 9 \n \l
automount            yes
USB devices          sda sdb
datadir              /media/USBdrive/ncdata (doesn't exist)
rootfs usage         1.9G/2.7G
Nextcloud check      error
HTTPD service        up
PHP service          up
MariaDB service      down
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   192.168.0.11
gateway              192.168.0.1
interface            eth0
certificates         digitalcarnage.webhop.me
certs due            69 days
NAT loopback         no
uptime               1:06

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /var/www/nextcloud/lib/private/DB/Connection.php:61
Stack trace:
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/nextcloud/lib/private/DB/Connection.php(148): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/nextcloud/lib/private/DB/ConnectionFactory.php(150): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /var/www/nextcloud/lib/private/Server.php(588): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('OCP\\IDBConnecti...')
#10 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IDBConnecti...')
#11 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\ServerContainer->query('OCP\\IDBConnecti...')
#12 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#13 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('DatabaseConnect...')
#14 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#15 /var/www/nextcloud/lib/private/Server.php(1345): OC\ServerContainer->query('DatabaseConnect...')
#16 /var/www/nextcloud/lib/private/Server.php(309): OC\Server->getDatabaseConnection()
#17 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#18 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('OC\\Authenticati...')
#19 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#20 /var/www/nextcloud/lib/private/Server.php(313): OC\ServerContainer->query('OC\\Authenticati...')
#21 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#22 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('OC\\Authenticati...')
#23 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#24 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\ServerContainer->query('OC\\Authenticati...')
#25 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#26 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('OC\\Authenticati...')
#27 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#28 /var/www/nextcloud/lib/private/Server.php(329): OC\ServerContainer->query('OC\\Authenticati...')
#29 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#30 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('OCP\\IUserSessio...')
#31 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IUserSessio...')
#32 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\ServerContainer->query('OCP\\IUserSessio...')
#33 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#34 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('UserSession')
#35 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('UserSession')
#36 /var/www/nextcloud/lib/private/Server.php(1220): OC\ServerContainer->query('UserSession')
#37 /var/www/nextcloud/lib/private/Server.php(939): OC\Server->getSession()
#38 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#39 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('OC\\Security\\CSR...')
#40 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Security\\CSR...')
#41 /var/www/nextcloud/lib/private/Server.php(935): OC\ServerContainer->query('OC\\Security\\CSR...')
#42 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#43 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('CsrfTokenManage...')
#44 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('CsrfTokenManage...')
#45 /var/www/nextcloud/lib/private/Server.php(1693): OC\ServerContainer->query('CsrfTokenManage...')
#46 /var/www/nextcloud/lib/private/Server.php(769): OC\Server->getCsrfTokenManager()
#47 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#48 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('OCP\\IRequest')
#49 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IRequest')
#50 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\ServerContainer->query('OCP\\IRequest')
#51 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#52 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('Request')
#53 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('Request')
#54 /var/www/nextcloud/lib/private/Server.php(1087): OC\ServerContainer->query('Request')
#55 /var/www/nextcloud/lib/private/Server.php(416): OC\Server->getRequest()
#56 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#57 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('OCP\\L10N\\IFacto...')
#58 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\L10N\\IFacto...')
#59 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\ServerContainer->query('OCP\\L10N\\IFacto...')
#60 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#61 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('L10NFactory')
#62 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('L10NFactory')
#63 /var/www/nextcloud/lib/private/Server.php(1274): OC\ServerContainer->query('L10NFactory')
#64 /var/www/nextcloud/lib/private/Server.php(1285): OC\Server->getL10NFactory()
#65 /var/www/nextcloud/lib/base.php(225): OC\Server->getL10N('lib')
#66 /var/www/nextcloud/lib/base.php(678): OC::checkConfig()
#67 /var/www/nextcloud/lib/base.php(1086): OC::init()
#68 /var/www/nextcloud/console.php(56): require_once('/var/www/nextcl...')
#69 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#70 {main}
```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Tue Dec 26 23:59:57.759799 2017] [ssl:warn] [pid 705:tid 1992429568] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Dec 26 23:59:58.053328 2017] [ssl:warn] [pid 989:tid 1992429568] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Dec 26 23:59:59.003048 2017] [mpm_event:notice] [pid 989:tid 1992429568] AH00489: Apache/2.4.25 (Raspbian) OpenSSL/1.0.2l configured -- resuming normal operations
[Tue Dec 26 23:59:59.003182 2017] [core:notice] [pid 989:tid 1992429568] AH00094: Command line: '/usr/sbin/apache2'

```
</details>

<details>
<summary>Database logs</summary>

```

tail: cannot open '/var/log/mysql/*.log' for reading: No such file or directory

```
</details>

<details>
<summary>Nextcloud logs</summary>

```

tail: cannot open '/media/USBdrive/ncdata/nextcloud.log' for reading: No such file or directory

```
</details>

It reports that it can't see ncdata but I have no idea how this has happend. I can SSH into the pi, run ncp on SSH as well as ncp-web.

Can anyone help?

Del

**Comment by ovpc** [comment]
Thanks for reporting.
Sorry to hear you're having issues.
My NCP is also up to date v0.43.1, but not having issues at all.
Nacho usually fixes this kind of issue really fast.

**Comment by nachoparker** [comment]
Hi, 

There hasn't been an update for over a week now. 

What I see is that you have two USB drives, and you use the link name `/media/USBdrive` for ncdatadir and probably also for nc-database.

If you have two drives, it is _random_ which drive will take `/media/USBdrive` and which one `/media/USBdrive1`. The idea of using `/media/USBdrive` is for a basic setup with one HDD for people that don't know their drives' labels. My guess is that this is what's happening. Did it stop working after reboot?

So that is one thing I would improve

- turn the pi off
- unplug the backup drive
- turn on again, it should be working again
- in ncp-web, re-run nc-datadir and nc-database (and anything else where it shows USBdrive), and replace `USBdrive` for `myCloudDrive1`
- if everything is working now, you can plug in the second USB drive.

We can also see (before doing all that) what happened to the database

```
systemctl status mysqld
```

Some people have reported that the database can go down if they move it to the drive. For most people it works fine, but if this happens again, you can consider moving it back to the SD

Hope it helps.

**Comment by deljones** [comment]
Hi

The update(s) is not the nextcloudpi update. If I log in as admin I get a notice that there has been unattended updates which, I have now turned off. These updates are .libc files and such like. Everything was ok until one day I was notified of an unattended update had taken place. I rebooted and that was it... Nothing!

I am back up again all is well... I just made another SD image, imported my ncp-config. I have unplugged the second drive that was acting as my backup which I will get back on again soon.

what I have noticed is that the NextCloud login takes an age to get logged in... Much much much longer than I remember. Once in its fine. Is there anywhere I can look to see why it takes so long to log in?

Otherwise all good. Again

Many thanks... Happy New Year

Del

**Comment by nachoparker** [comment]
Well, thankfully it is getting easier to migrate to a new instance with nc-import-ncp and nc-backup ;)

It sounds weird to me that an unattended upgrade messed up automount in any way. Still, i recommend that you use label names instead of `/media/USBdrive`

Always it takes a long time to login the first time, and then after that the PHP code is cached and it is much faster.

Well, hopefully it won't happen again! If it happens, tell us so we can discover what happened. If it happens to anyone else please reopen.

Happy New year
