### ISSUE TITLE
letsencrypt timeout issue

### ISSUE THREAD

**Issue by brotonmail** [nextcloud/nextcloudpi#404]
My letsencrypt cert recently expired. I was surprised that it didn't autorenew so I tried to do it myself. Here is the error I received:

Launching letsencrypt
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for xxx
Using the webroot path /var/www/nextcloud for all unmatched domains.
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. xxx (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://xxx/.well-known/acme-challenge/HulZw-NjvOOBx7ctPVn1GkpLC7cRgDJ4Rfn6D8hi1jI: Timeout

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: xxx
   Type:   connection
   Detail: Fetching
   http://xxx/.well-known/acme-challenge/HulZw-NjvOOBx7ctPVn1GkpLC7cRgDJ4Rfn6D8hi1jI:
   Timeout

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
Done. Press any key...

I checked my Firewall and port 80 seems to be open and NATed. Any idea what causes this?

**Comment by theCalcaholic** [comment]
The domain name seems to be misconfigured. The output should contain `http://<your-domain-name>/well-known/acme-challenge/<token>`. In your case domain name appears to be blank. Is it correctly displayed in the DOMAIN field under letsencrypt in the web panel?

**Comment by brotonmail** [comment]
Yes sorry I had it as <xxx> so it didn't show up. Just changed.

**Comment by theCalcaholic** [comment]
What does `/var/log/letsencrypt/letsencrypt.log` read after the failed attempt?

**Comment by theCalcaholic** [comment]
What does `/var/log/letsencrypt/letsencrypt.log` read after the failed attempt?

**Comment by nachoparker** [comment]
are your ports open? please, always include the output of

```
sudo ncp-report
```
, or in ncp-web

```
nc-info
```

**Comment by brotonmail** [comment]
<--! Paste this in GitHub report -->

<details>
<summary>NextCloudPi diagnostics</summary>

```

Cannot load Zend OPcache - it was already loaded
NextCloudPi version  v0.46.6
NextCloudPi image    untagged
distribution         Raspbian GNU/Linux 9 \n \l
automount            yes
USB devices          none
datadir              /var/nextcloud/datadir
data in SD           yes
data filesystem      ext2/ext3
data disk usage      7.7G/15G
rootfs usage         7.7G/15G
swapfile             /var/swap
Nextcloud check      ok
Nextcloud version    12.0.0.29
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   10.0.0.2
gateway              10.0.0.1
interface            enxb827ebc2e8f5
certificates         xxx 
certs due            none
NAT loopback         no
uptime               1day

```
</details>


<details>
<summary>Nextcloud configuration</summary>

```

Cannot load Zend OPcache - it was already loaded
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "1": "10.0.0.2",
            "2": "xxx",
            "4": "xxx"
        },
        "datadirectory": "\/var\/nextcloud\/datadir",
        "overwrite.cli.url": "https:\/\/xxx",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "ocbx7lnvodo4",
        "loglevel": "2",
        "log_type": "file",
        "logfile": "\/var\/www\/nextcloud\/data\/nextcloud.log",
        "maintenance": false,
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "admin",
        "mail_domain": "ownyourbits.com",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        }
    }
}

```
</details>


<details>
<summary>HTTPd logs</summary>

```

[Sun Feb 11 06:25:03.000972 2018] [mpm_event:notice] [pid 812:tid 1992032256] AH00489: Apache/2.4.25 (Raspbian) OpenSSL/1.0.2l   configured -- resuming normal operations
[Sun Feb 11 06:25:03.001083 2018] [core:notice] [pid 812:tid 1992032256] AH00094: Command line: '/usr/sbin/apache2'

```
</details>


<details>
<summary>Database logs</summary>

```


```
</details>


<details>
<summary>Nextcloud logs</summary>

```

{"reqId":"WTsGUn8AAQEAAAQ4lJYAAA8W","level":2,"time":"2017-06-09T20:34:26+00:00","remoteAddr":"192.168.14.27","user":"admin","app":"core","method":"GET","url":"\/index.php\/settings\/users","message":"Login failed: 'admin' (Remote IP: '192.168.14.27')","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko\/20100101 Firefox\/53.0","version":"12.0.0.29"}
{"reqId":"WTwAGn8AAQEAAAZt100AAEwP","level":4,"time":"2017-06-10T14:20:21+00:00","remoteAddr":"79.253.39.136","user":"admin","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/addressbooks\/users\/admin\/contacts\/3b5d7e27-c493-404b-b8f2-2c0e509c80f5.vcf","message":"Exception: {\"Message\":\"HTTP\\\/1.1 415 This resource only supports valid vCard or jCard data. Parse error: End of document reached prematurely\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\UnsupportedMediaType\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(316): Sabre\\\\CardDAV\\\\Plugin->validateVCard('BEGIN:VCARD\\\\r\\\\nVE...', false)\\n#1 [internal function]: Sabre\\\\CardDAV\\\\Plugin->beforeCreateFile('addressbooks\\\/us...', 'BEGIN:VCARD\\\\r\\\\nVE...', Object(OCA\\\\DAV\\\\CardDAV\\\\AddressBook), false)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1093): Sabre\\\\Event\\\\EventEmitter->emit('beforeCreateFil...', Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('addressbooks\\\/us...', 'BEGIN:VCARD\\\\r\\\\nVE...', NULL)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(253): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/var\\\/www\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php\",\"Line\":356,\"User\":\"admin\"}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/59.0.3071.86 Safari\/537.36","version":"12.0.0.29"}
{"reqId":"WTxqin8AAQEAAAZlrbgAABMJ","level":4,"time":"2017-06-10T21:54:19+00:00","remoteAddr":"84.16.226.51","user":"lenard","app":"webdav","method":"MKCOL","url":"\/remote.php\/webdav\/Senior%20Year%20Memories\/Ethan","message":"Exception: {\"Message\":\"HTTP\\\/1.1 405 The resource you tried to create already exists\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\MethodNotAllowed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('Senior Year Mem...', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(71): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1180,\"User\":\"lenard\"}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/59.0.3071.86 Safari\/537.36","version":"12.0.0.29"}
{"reqId":"WTxuvH8AAQEAAAkzAScAAABX","level":4,"time":"2017-06-10T22:12:12+00:00","remoteAddr":"84.16.226.51","user":"lenard","app":"webdav","method":"MKCOL","url":"\/remote.php\/webdav\/Backup\/Backups\/Contacts%20-%2003.04.2017.abbu","message":"Exception: {\"Message\":\"HTTP\\\/1.1 405 The resource you tried to create already exists\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\MethodNotAllowed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('Backup\\\/Backups\\\/...', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(71): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1180,\"User\":\"lenard\"}","userAgent":"Mozilla\/5.0 (Macintosh) mirall\/2.2.4 (build 1) (Nextcloud)","version":"12.0.0.29"}
{"reqId":"WTxuvH8AAQEAAAZlrxkAAAAL","level":4,"time":"2017-06-10T22:12:12+00:00","remoteAddr":"84.16.226.51","user":"lenard","app":"webdav","method":"MKCOL","url":"\/remote.php\/webdav\/Backup\/Backups\/Contacts%20-%2003.04.2017.abbu\/Sources\/472AF74C-3630-4079-8590-63A8C631FD1E","message":"Exception: {\"Message\":\"HTTP\\\/1.1 405 The resource you tried to create already exists\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\MethodNotAllowed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('Backup\\\/Backups\\\/...', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(71): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1180,\"User\":\"lenard\"}","userAgent":"Mozilla\/5.0 (Macintosh) mirall\/2.2.4 (build 1) (Nextcloud)","version":"12.0.0.29"}
{"reqId":"WTxyr38AAQEAAAZlsOgAAAAF","level":3,"time":"2017-06-10T22:29:03+00:00","remoteAddr":"84.16.226.51","user":"lenard","app":"PHP","method":"MOVE","url":"\/remote.php\/webdav\/Senior%20Year%20Memories","message":"Undefined offset: 3 at \/var\/www\/nextcloud\/apps\/activity\/lib\/FilesHooks.php#620","userAgent":"Mozilla\/5.0 (Macintosh) mirall\/2.2.4 (build 1) (Nextcloud)","version":"12.0.0.29"}
{"reqId":"WTzntn8AAQEAAAkzBTYAAABL","level":2,"time":"2017-06-11T06:48:22+00:00","remoteAddr":"139.162.113.204","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"139.162.113.204\" tried to access using \"79.253.20.9\" as host.","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/50.0.2661.102 Safari\/537.36","version":"12.0.0.29"}
{"reqId":"WT0ZOn8AAQEAAAkzBTcAAABA","level":2,"time":"2017-06-11T10:19:39+00:00","remoteAddr":"74.82.47.2","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"74.82.47.2\" tried to access using \"79.253.20.9\" as host.","userAgent":"--","version":"12.0.0.29"}
{"reqId":"WT1EDX8AAQEAAARuOycAAABC","level":4,"time":"2017-06-11T13:22:38+00:00","remoteAddr":"79.253.20.9","user":"lenard","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/Senior%20Year\/Senior%20Year%20Memories\/Ethan\/ALAC\/02%20UP%20(Here%20Now).m4a-chunking-4286841549-2-1","message":"Exception: {\"Message\":\"HTTP\\\/1.1 500 Senior Year\\\/Senior Year Memories\\\/Ethan\\\/ALAC\\\/02 UP (Here Now).m4a not found while trying to get owner\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(107): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->convertToSabreException(Object(OCP\\\\Files\\\\NotFoundException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(151): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #11)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1095): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('02 UP (Here Now...', Resource id #11)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('Senior Year\\\/Sen...', Resource id #11, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(71): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":567,\"User\":\"lenard\"}","userAgent":"Mozilla\/5.0 (Macintosh) mirall\/2.2.4 (build 1) (Nextcloud)","version":"12.0.0.29"}
{"reqId":"WT1EaH8AAQEAAARuOzoAAABV","level":3,"time":"2017-06-11T13:23:53+00:00","remoteAddr":"79.253.20.9","user":"lenard","app":"PHP","method":"MOVE","url":"\/remote.php\/webdav\/02%20UP%20(Here%20Now).m4a","message":"Undefined offset: 3 at \/var\/www\/nextcloud\/apps\/activity\/lib\/FilesHooks.php#620","userAgent":"Mozilla\/5.0 (Macintosh) mirall\/2.2.4 (build 1) (Nextcloud)","version":"12.0.0.29"}
{"reqId":"WT1FMH8AAQEAAARuPCMAAABG","level":4,"time":"2017-06-11T13:27:13+00:00","remoteAddr":"79.253.20.9","user":"lenard","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/Senior%20Year\/Senior%20Year%20Important%20Documents\/MME%20F%2015\/Middle%20East%20Maps\/Location%20Of%20Oil%20Fields.docx.bc","message":"Exception: {\"Message\":\"HTTP\\\/1.1 500 An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\\\"files\\\\\\\/98050aaba65ba7f80d7c412112764e4d\\\", -1, 1497191233, \\\"files\\\\\\\/98050aaba65ba7f80d7c412112764e4d\\\"]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files\\\/98050aaba65ba7f80d7c412112764e4d' for key 'lock_key_index'\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(159): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->convertToSabreException(Object(Doctrine\\\\DBAL\\\\Exception\\\\UniqueConstraintViolationException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(151): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #11)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1095): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('Location Of Oil...', Resource id #11)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('Senior Year\\\/Sen...', Resource id #11, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(71): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":567,\"User\":\"lenard\"}","userAgent":"Mozilla\/5.0 (Macintosh) mirall\/2.2.4 (build 1) (Nextcloud)","version":"12.0.0.29"}
{"reqId":"WT1F7H8AAQEAAARuPLgAAABI","level":3,"time":"2017-06-11T13:30:21+00:00","remoteAddr":"79.253.20.9","user":"lenard","app":"PHP","method":"MOVE","url":"\/remote.php\/webdav\/Location%20Of%20Oil%20Fields.docx.bc","message":"Undefined offset: 3 at \/var\/www\/nextcloud\/apps\/activity\/lib\/FilesHooks.php#620","userAgent":"Mozilla\/5.0 (Macintosh) mirall\/2.2.4 (build 1) (Nextcloud)","version":"12.0.0.29"}

```
</details>

**Comment by theCalcaholic** [comment]
Are any requests to /.well-known/... documented in /var/log/apache2/error.log or in /var/log/apache2/access.log after the attempt?

If not, are you sure you configured dns correctly (can you reach your cloud under that domain) and are there definitely no typos in the url in the letsencrypt configuration?

**Comment by nachoparker** [comment]
your ports are open, so it must be a DDNS problem. What's your provider? no-ip? freeDNS?

I also wonder why you have that funky interface name :P

**Comment by brotonmail** [comment]
I've configured my DDNS with nsupdate.info. I checked the site and it seemed it was pointing to the same IP Address as I got when I entered "curl ipinfo.io". I'll try switching providers and if that doesn't work I'll try reinstalling on a fresh image.

**Comment by nachoparker** [comment]
that's weird. It's going to be one of

- network connectivity outside ( can you ping google from the pi? )
- DDNS config ( seems ok )
- port forwarding

about this last one, it's worth mentioning that we use an online service to check if the ports are open. This service *caches* the results, so if you now close the ports, the check will return a false positive.

Maybe your router configuration reseted, or was reseted by your ISP? It's worth checking.

If you know your public IP you can try accessing by IP from outside ( for instance, mobile phone not connected to wifi ).

Also, something that can happen is that your ISP internally changed you to be behind a CG-NAT. In that case you need to contact them and ask them to take you out of the CG-NAT range. Not all providers will do this for you.

**Comment by brotonmail** [comment]
Hey guys. Just double checked my Firewall. I had put in a rule allowing HTTP but hadn't NATed it properly. NextcloudPi was not at fault, it was my own stupidity :D Thank you for your great work!

**Comment by theCalcaholic** [comment]
Glad you could solve it. :D
