### ISSUE TITLE
Failing upgrade NextCloud 12.0.5 -> 13.0.0

### ISSUE THREAD

**Issue by MaralAfris** [nextcloud/nextcloudpi#422]
### QUESTIONS
Hi !

Upgrade from NextCloud 12.0.5 to 13.0.0 breaks NextCloudPi, I get a error 500 but apache and php seem running without problems...

Any idea what can cause the problem?

Here are some info:
ncp-diag
```
# ncp-diag
NextCloudPi version|v0.46.13
NextCloudPi image|untagged
distribution|Raspbian GNU/Linux 8 \n \l
automount|no
USB devices|none
datadir|/var/www/nextcloud/data
data in SD|yes
data filesystem|ext2/ext3
data disk usage|6.6G/29G
rootfs usage|6.6G/29G
swapfile|/var/swap
Cannot load Zend OPcache - it was already loaded
Nextcloud check|ok
Nextcloud version|13.0.0.14
HTTPD service|up
PHP service|up
MariaDB service|up
Redis service|up
Postfix service|up
internet check|ok
port check 80|open
port check 443|open
IP|192.168.0.11
gateway|192.168.0.1
interface|eth0
certificates|maralafris.ddns.net
certs due|89 days
NAT loopback|no
uptime|2:45
```

ncp-report
<details>
<summary>NextCloudPi diagnostics</summary>

```

Cannot load Zend OPcache - it was already loaded
NextCloudPi version  v0.46.13
NextCloudPi image    untagged
distribution         Raspbian GNU/Linux 8 \n \l
automount            no
USB devices          none
datadir              /var/www/nextcloud/data
data in SD           yes
data filesystem      ext2/ext3
data disk usage      6.6G/29G
rootfs usage         6.6G/29G
swapfile             /var/swap
Nextcloud check      ok
Nextcloud version    13.0.0.14
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   192.168.0.11
gateway              192.168.0.1
interface            eth0
certificates         maralafris.ddns.net
certs due            89 days
NAT loopback         no
uptime               2:49

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

Cannot load Zend OPcache - it was already loaded
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "192.168.0.11",
            "1": "192.168.0.11",
            "2": "maralafris.ddns.net",
            "4": "maralafris.ddns.net",
            "3": "maralafris.ddns.net"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/maralafris.ddns.net",
        "dbtype": "mysql",
        "version": "12.0.5.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": "2",
        "log_type": "file",
        "theme": "",
        "filelocking.enabled": "true",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Sun Feb 18 11:32:27.000370 2018] [core:notice] [pid 997] AH00094: Command line: '/usr/sbin/apache2'
[Sun Feb 18 12:00:10.557370 2018] [mpm_prefork:notice] [pid 997] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Sun Feb 18 12:00:11.000416 2018] [mpm_prefork:notice] [pid 997] AH00163: Apache/2.4.25 (Raspbian) OpenSSL/1.0.2l configured -- resuming normal operations
[Sun Feb 18 12:00:11.000481 2018] [core:notice] [pid 997] AH00094: Command line: '/usr/sbin/apache2'
[Sun Feb 18 12:12:49.767234 2018] [mpm_prefork:notice] [pid 997] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Sun Feb 18 12:12:50.000279 2018] [mpm_prefork:notice] [pid 997] AH00163: Apache/2.4.25 (Raspbian) OpenSSL/1.0.2l configured -- resuming normal operations
[Sun Feb 18 12:12:50.000317 2018] [core:notice] [pid 997] AH00094: Command line: '/usr/sbin/apache2'
[Sun Feb 18 12:14:18.523072 2018] [mpm_prefork:notice] [pid 997] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Sun Feb 18 12:14:18.663140 2018] [ssl:warn] [pid 997] AH01909: 127.0.1.1:4443:0 server certificate does NOT include an ID which matches the server name
[Sun Feb 18 12:14:19.000329 2018] [mpm_prefork:notice] [pid 997] AH00163: Apache/2.4.25 (Raspbian) OpenSSL/1.0.2l configured -- resuming normal operations
[Sun Feb 18 12:14:19.000367 2018] [core:notice] [pid 997] AH00094: Command line: '/usr/sbin/apache2'
[Sun Feb 18 14:09:43.685265 2018] [core:notice] [pid 997] AH00052: child pid 8614 exit signal Segmentation fault (11)
[Sun Feb 18 14:09:43.999124 2018] [mpm_prefork:notice] [pid 997] AH00169: caught SIGTERM, shutting down
[Sun Feb 18 14:09:57.035525 2018] [ssl:warn] [pid 12472] AH01909: 127.0.1.1:4443:0 server certificate does NOT include an ID which matches the server name
[Sun Feb 18 14:09:58.172825 2018] [ssl:warn] [pid 12473] AH01909: 127.0.1.1:4443:0 server certificate does NOT include an ID which matches the server name
[Sun Feb 18 14:09:59.009762 2018] [mpm_prefork:notice] [pid 12473] AH00163: Apache/2.4.25 (Raspbian) OpenSSL/1.0.2l configured -- resuming normal operations
[Sun Feb 18 14:09:59.009883 2018] [core:notice] [pid 12473] AH00094: Command line: '/usr/sbin/apache2'

```
</details>

<details>
<summary>Database logs</summary>

```

tail: cannot open '/var/log/mysql/*.log' for reading: No such file or directory

```
</details>

<details>
<summary>Nextcloud logs</summary>

```

{"reqId":"WoldIn8AAQEAABkWEAoAAAQA","level":3,"time":"2018-02-18T11:01:54+00:00","remoteAddr":"192.168.0.1","user":"maralafris","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"file_get_contents(\/var\/www\/nextcloud\/data\/appdata_oc7szhvfrqle\/css\/files\/6902d7affe37f63b3e384d36152bbd49-merged.css.deps): failed to open stream: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#209","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"WoldIn8AAQEAABkWEAoAAAQA","level":3,"time":"2018-02-18T11:01:54+00:00","remoteAddr":"192.168.0.1","user":"maralafris","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"Invalid argument supplied for foreach() at \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php#151","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"WoldaH8AAQEAABkU6zQAAAMA","level":3,"time":"2018-02-18T11:03:04+00:00","remoteAddr":"192.168.0.1","user":"maralafris","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"file_get_contents(\/var\/www\/nextcloud\/data\/appdata_oc7szhvfrqle\/css\/files\/6902d7affe37f63b3e384d36152bbd49-merged.css.deps): failed to open stream: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#209","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"WoldaH8AAQEAABkU6zQAAAMA","level":3,"time":"2018-02-18T11:03:04+00:00","remoteAddr":"192.168.0.1","user":"maralafris","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"Invalid argument supplied for foreach() at \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php#151","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"Wolddn8AAQEAABkWEBQAAAQA","level":3,"time":"2018-02-18T11:03:18+00:00","remoteAddr":"192.168.0.1","user":"maralafris","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"file_get_contents(\/var\/www\/nextcloud\/data\/appdata_oc7szhvfrqle\/css\/files\/6902d7affe37f63b3e384d36152bbd49-merged.css.deps): failed to open stream: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#209","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"Wolddn8AAQEAABkWEBQAAAQA","level":3,"time":"2018-02-18T11:03:18+00:00","remoteAddr":"192.168.0.1","user":"maralafris","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"Invalid argument supplied for foreach() at \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php#151","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"WoldfH8AAQEAABkWECIAAAQA","level":3,"time":"2018-02-18T11:03:26+00:00","remoteAddr":"192.168.0.1","user":"maralafris","app":"no app in context","method":"GET","url":"\/data\/.ocdata?t=1518951804725","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"theming.Theming.getLogo\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(339): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('theming.Theming...', Array, 1)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(77): OC\\\\Route\\\\Router->generate('theming.Theming...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/ThemingDefaults.php(165): OC\\\\URLGenerator->linkToRoute('theming.Theming...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/Defaults.php(186): OCA\\\\Theming\\\\ThemingDefaults->getLogo(true)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/core\\\/templates\\\/layout.guest.php(45): OCP\\\\Defaults->getLogo()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(176): include('\\\/var\\\/www\\\/nextcl...')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(151): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/nextcl...', NULL)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(202): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(224): OC_Template->fetchPage()\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#10 \\\/var\\\/www\\\/nextcloud\\\/core\\\/templates\\\/403.php(7): OC\\\\Template\\\\Base->printPage()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"Wolh6H8AAQEAACGsHYUAAAQA","level":3,"time":"2018-02-18T11:22:18+00:00","remoteAddr":"192.168.0.1","user":"maralafris","app":"no app in context","method":"GET","url":"\/data\/.ocdata?t=1518952936713","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"theming.Theming.getLogo\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(339): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('theming.Theming...', Array, 1)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(77): OC\\\\Route\\\\Router->generate('theming.Theming...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/ThemingDefaults.php(165): OC\\\\URLGenerator->linkToRoute('theming.Theming...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/Defaults.php(186): OCA\\\\Theming\\\\ThemingDefaults->getLogo(true)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/core\\\/templates\\\/layout.guest.php(45): OCP\\\\Defaults->getLogo()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(176): include('\\\/var\\\/www\\\/nextcl...')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(151): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/nextcl...', NULL)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(202): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(224): OC_Template->fetchPage()\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#10 \\\/var\\\/www\\\/nextcloud\\\/core\\\/templates\\\/403.php(7): OC\\\\Template\\\\Base->printPage()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"Wolh7H8AAQEAACGsHYgAAAQA","level":3,"time":"2018-02-18T11:22:21+00:00","remoteAddr":"192.168.0.1","user":"maralafris","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"file_get_contents(\/var\/www\/nextcloud\/data\/appdata_oc7szhvfrqle\/css\/files\/6902d7affe37f63b3e384d36152bbd49-merged.css.deps): failed to open stream: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#209","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"Wolh7H8AAQEAACGsHYgAAAQA","level":3,"time":"2018-02-18T11:22:21+00:00","remoteAddr":"192.168.0.1","user":"maralafris","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"Invalid argument supplied for foreach() at \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php#151","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"Wolh8n8AAQEAACGsHZYAAAQA","level":3,"time":"2018-02-18T11:22:28+00:00","remoteAddr":"192.168.0.1","user":"maralafris","app":"no app in context","method":"GET","url":"\/data\/.ocdata?t=1518952946644","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"theming.Theming.getLogo\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(339): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('theming.Theming...', Array, 1)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(77): OC\\\\Route\\\\Router->generate('theming.Theming...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/ThemingDefaults.php(165): OC\\\\URLGenerator->linkToRoute('theming.Theming...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/Defaults.php(186): OCA\\\\Theming\\\\ThemingDefaults->getLogo(true)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/core\\\/templates\\\/layout.guest.php(45): OCP\\\\Defaults->getLogo()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(176): include('\\\/var\\\/www\\\/nextcl...')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(151): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/nextcl...', NULL)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(202): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(224): OC_Template->fetchPage()\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#10 \\\/var\\\/www\\\/nextcloud\\\/core\\\/templates\\\/403.php(7): OC\\\\Template\\\\Base->printPage()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"WolvY38AAQEAACGkLjkAAAAA","level":2,"time":"2018-02-18T12:19:47+00:00","remoteAddr":"184.105.247.194","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"184.105.247.194\" tried to access using \"213.136.57.165\" as host.","userAgent":"--","version":"12.0.5.3"}
{"reqId":"Wol4dX8AAQEAACGkLj8AAAAA","level":3,"time":"2018-02-18T12:58:29+00:00","remoteAddr":"192.168.0.1","user":"maralafris","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"file_get_contents(\/var\/www\/nextcloud\/data\/appdata_oc7szhvfrqle\/css\/files\/6902d7affe37f63b3e384d36152bbd49-merged.css.deps): failed to open stream: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#209","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"Wol4dX8AAQEAACGkLj8AAAAA","level":3,"time":"2018-02-18T12:58:29+00:00","remoteAddr":"192.168.0.1","user":"maralafris","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"Invalid argument supplied for foreach() at \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php#151","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"Wol4e38AAQEAACGkLlAAAAAA","level":3,"time":"2018-02-18T12:58:36+00:00","remoteAddr":"192.168.0.1","user":"maralafris","app":"no app in context","method":"GET","url":"\/data\/.ocdata?t=1518958715261","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"theming.Theming.getLogo\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(339): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('theming.Theming...', Array, 1)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(77): OC\\\\Route\\\\Router->generate('theming.Theming...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/ThemingDefaults.php(165): OC\\\\URLGenerator->linkToRoute('theming.Theming...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/Defaults.php(186): OCA\\\\Theming\\\\ThemingDefaults->getLogo(true)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/core\\\/templates\\\/layout.guest.php(45): OCP\\\\Defaults->getLogo()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(176): include('\\\/var\\\/www\\\/nextcl...')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(151): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/nextcl...', NULL)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(202): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(224): OC_Template->fetchPage()\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#10 \\\/var\\\/www\\\/nextcloud\\\/core\\\/templates\\\/403.php(7): OC\\\\Template\\\\Base->printPage()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"Wol5u38AAQEAACGkLloAAAAA","level":3,"time":"2018-02-18T13:03:56+00:00","remoteAddr":"192.168.0.1","user":"maralafris","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"file_get_contents(\/var\/www\/nextcloud\/data\/appdata_oc7szhvfrqle\/css\/files\/6902d7affe37f63b3e384d36152bbd49-merged.css.deps): failed to open stream: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#209","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"Wol5u38AAQEAACGkLloAAAAA","level":3,"time":"2018-02-18T13:03:56+00:00","remoteAddr":"192.168.0.1","user":"maralafris","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"Invalid argument supplied for foreach() at \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php#151","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"Wol5wH8AAQEAACGkLmgAAAAA","level":3,"time":"2018-02-18T13:04:02+00:00","remoteAddr":"192.168.0.1","user":"maralafris","app":"no app in context","method":"GET","url":"\/data\/.ocdata?t=1518959040808","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"theming.Theming.getLogo\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(339): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('theming.Theming...', Array, 1)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(77): OC\\\\Route\\\\Router->generate('theming.Theming...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/ThemingDefaults.php(165): OC\\\\URLGenerator->linkToRoute('theming.Theming...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/Defaults.php(186): OCA\\\\Theming\\\\ThemingDefaults->getLogo(true)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/core\\\/templates\\\/layout.guest.php(45): OCP\\\\Defaults->getLogo()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(176): include('\\\/var\\\/www\\\/nextcl...')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(151): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/nextcl...', NULL)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(202): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(224): OC_Template->fetchPage()\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#10 \\\/var\\\/www\\\/nextcloud\\\/core\\\/templates\\\/403.php(7): OC\\\\Template\\\\Base->printPage()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"Wol6@X8AAQEAACGkLm0AAAAA","level":3,"time":"2018-02-18T13:09:14+00:00","remoteAddr":"192.168.0.1","user":"--","app":"PHP","method":"GET","url":"\/","message":"Declaration of OCA\\FilesAccessControl\\StorageWrapper::copyFromStorage(OCP\\Files\\Storage $sourceStorage, $sourceInternalPath, $targetInternalPath) must be compatible with OCP\\Files\\Storage::copyFromStorage(OCP\\Files\\Storage\\IStorage $sourceStorage, $sourceInternalPath, $targetInternalPath) at \/var\/www\/nextcloud\/apps\/files_accesscontrol\/lib\/StorageWrapper.php#0","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}
{"reqId":"Wol7mn8AAQEAADDzbC4AAAQA","level":3,"time":"2018-02-18T13:11:55+00:00","remoteAddr":"192.168.0.1","user":"--","app":"PHP","method":"GET","url":"\/","message":"Declaration of OCA\\FilesAccessControl\\StorageWrapper::copyFromStorage(OCP\\Files\\Storage $sourceStorage, $sourceInternalPath, $targetInternalPath) must be compatible with OCP\\Files\\Storage::copyFromStorage(OCP\\Files\\Storage\\IStorage $sourceStorage, $sourceInternalPath, $targetInternalPath) at \/var\/www\/nextcloud\/apps\/files_accesscontrol\/lib\/StorageWrapper.php#0","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.167 Safari\/537.36","version":"12.0.5.3"}

```
</details>

**Comment by theCalcaholic** [comment]
According to your nextcloud logs, there are files missing. Probably something went wrong during the update. You're best option would be to restore a backup and retry the update.

If you don't have a recent backup (which should *always* be created before updating) you could try the following:
1. Rename (move) the current nextcloud installation folder, e. g. `sudo mv /var/www/nextcloud /var/www/nextcloud_bk`
2. download the latest version of nextcloud: `wget https://download.nextcloud.com/server/releases/nextcloud-13.0.0.tar.bz2`
3. extract it to /var/www : `sudo tar xf nextcloud-latest.zip /var/www/nextcloud`)
4. move your config.php and data directory from the backup to the new installation:
```sh
mv /var/www/nextcloud_bk/config/config.php /var/www/nextcloud/config/
mv /var/www/nextcloud_bk/data /var/www/nextcloud/
```

Note however, that this is probably not related to NextcloudPi, but rather to nextcloud in general.
