### ISSUE TITLE
Can't find datadir

### ISSUE THREAD

**Issue by datenbrei** [nextcloud/nextcloudpi#481]
My older setup of Nextcloudpi was running pretty well, but one day I just got an empty page. The Admin panel is running pretty well, though.

My data dir is on an internal USB-SSD with 1 TB and btrfs. formatted.

I checked the automounts under /media, but everything is well, consistant and permissions seem to be ok. Also I checked redis, it also seems to be ok. 

The datadir seems to be basic for all other things, like performing a backup and so on. 

Today I would do the setup different, but for doing a backup I first would like to get my setup going. All system parts should be on latest versions.

In the logs there seems to be a mysql login issue, but I'm able to login to mysql using the credentials from /root/.my.cnf.

I kindly ask for help now. Here my details from ncp-report:

<details>
<summary>NextCloudPi diagnostics</summary>

```

Cannot load Zend OPcache - it was already loaded
NextCloudPi version  v0.53.27
NextCloudPi image    NextCloudPi_10-03-17
distribution         Raspbian GNU/Linux 9 \n \l
automount            yes
USB devices          sda
datadir              /media/ncdata/ncdata
data in SD           no
data filesystem      btrfs
data disk usage      246G/928G
rootfs usage         4,4G/30G
swapfile             none
Nextcloud check      error
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   192.168.178.62
gateway              192.168.178.1
interface            eth0
certificates         none
NAT loopback         no
uptime               1:06

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

Cannot load Zend OPcache - it was already loaded
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'ncadmin'@'localhost' (using password: YES) in /var/www/nextcloud/lib/private/DB/Connection.php:64
Stack trace:
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/nextcloud/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/nextcloud/lib/private/DB/ConnectionFactory.php(152): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /var/www/nextcloud/lib/private/Server.php(618): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OCP\\IDBConnecti...')
#10 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IDBConnecti...')
#11 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(164): OC\ServerContainer->query('OCP\\IDBConnecti...')
#12 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#13 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('DatabaseConnect...')
#14 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#15 /var/www/nextcloud/lib/private/Server.php(1490): OC\ServerContainer->query('DatabaseConnect...')
#16 /var/www/nextcloud/lib/private/Server.php(331): OC\Server->getDatabaseConnection()
#17 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#18 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OC\\Authenticati...')
#19 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#20 /var/www/nextcloud/lib/private/Server.php(335): OC\ServerContainer->query('OC\\Authenticati...')
#21 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#22 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OC\\Authenticati...')
#23 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#24 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(164): OC\ServerContainer->query('OC\\Authenticati...')
#25 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#26 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OC\\Authenticati...')
#27 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#28 /var/www/nextcloud/lib/private/Server.php(351): OC\ServerContainer->query('OC\\Authenticati...')
#29 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#30 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OCP\\IUserSessio...')
#31 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IUserSessio...')
#32 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(164): OC\ServerContainer->query('OCP\\IUserSessio...')
#33 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#34 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('UserSession')
#35 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('UserSession')
#36 /var/www/nextcloud/lib/private/Server.php(1359): OC\ServerContainer->query('UserSession')
#37 /var/www/nextcloud/lib/private/Server.php(678): OC\Server->getUserSession()
#38 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#39 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OC\\App\\AppManag...')
#40 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\App\\AppManag...')
#41 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(164): OC\ServerContainer->query('OC\\App\\AppManag...')
#42 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#43 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('AppManager')
#44 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#45 /var/www/nextcloud/lib/private/Server.php(1663): OC\ServerContainer->query('AppManager')
#46 /var/www/nextcloud/lib/private/legacy/app.php(330): OC\Server->getAppManager()
#47 /var/www/nextcloud/lib/private/legacy/app.php(113): OC_App::getEnabledApps()
#48 /var/www/nextcloud/lib/base.php(661): OC_App::loadApps(Array)
#49 /var/www/nextcloud/lib/base.php(1080): OC::init()
#50 /var/www/nextcloud/console.php(46): require_once('/var/www/nextcl...')
#51 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#52 {main}
```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Sun Apr 15 12:13:46.005105 2018] [mpm_event:notice] [pid 794:tid 1992241152] AH00489: Apache/2.4.25 (Raspbian) OpenSSL/1.0.2l configured -- resuming normal operations
[Sun Apr 15 12:13:46.005344 2018] [core:notice] [pid 794:tid 1992241152] AH00094: Command line: '/usr/sbin/apache2'
[Sun Apr 15 12:13:53.187011 2018] [proxy_fcgi:error] [pid 864:tid 1985365040] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  touch(): Utime failed: Permission denied in /var/www/ncp-web/ncp-output.php on line 81\n'
[Sun Apr 15 12:13:53.199885 2018] [proxy_fcgi:error] [pid 864:tid 1784038448] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  touch(): Utime failed: Permission denied in /var/www/ncp-web/ncp-output.php on line 81\n'
[Sun Apr 15 12:18:06.174265 2018] [proxy_fcgi:error] [pid 864:tid 1960199216] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 163\n'
[Sun Apr 15 12:18:07.286970 2018] [proxy_fcgi:error] [pid 864:tid 1851147312] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  touch(): Utime failed: Permission denied in /var/www/ncp-web/ncp-output.php on line 81\n'
[Sun Apr 15 12:18:09.951983 2018] [proxy_fcgi:error] [pid 864:tid 1842758704] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 163\n'
[Sun Apr 15 12:18:11.761894 2018] [proxy_fcgi:error] [pid 864:tid 1834370096] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 163\n'
[Sun Apr 15 12:18:41.405371 2018] [proxy_fcgi:error] [pid 864:tid 1825981488] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 163\n'
[Sun Apr 15 12:18:57.341642 2018] [proxy_fcgi:error] [pid 864:tid 1809204272] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 163\n'
[Sun Apr 15 12:25:09.466520 2018] [proxy_fcgi:error] [pid 864:tid 1792427056] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 163\n'
[Sun Apr 15 12:25:10.651345 2018] [proxy_fcgi:error] [pid 864:tid 1901478960] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  touch(): Utime failed: Permission denied in /var/www/ncp-web/ncp-output.php on line 81\n'
[Sun Apr 15 12:25:13.156156 2018] [proxy_fcgi:error] [pid 864:tid 1893090352] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 163\n'
[Sun Apr 15 12:25:15.012328 2018] [proxy_fcgi:error] [pid 864:tid 1884701744] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 163\n'
[Sun Apr 15 12:25:20.260066 2018] [proxy_fcgi:error] [pid 864:tid 1867924528] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 163\n'
[Sun Apr 15 12:25:35.706519 2018] [proxy_fcgi:error] [pid 864:tid 1859535920] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 163\n'
[Sun Apr 15 12:27:03.940084 2018] [proxy_fcgi:error] [pid 864:tid 1834370096] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 163\n'
[Sun Apr 15 12:27:06.504819 2018] [proxy_fcgi:error] [pid 864:tid 1825981488] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 163\n'
[Sun Apr 15 12:38:36.164381 2018] [proxy_fcgi:error] [pid 864:tid 1817592880] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 163\n'
[Sun Apr 15 12:38:49.549907 2018] [proxy_fcgi:error] [pid 864:tid 1809204272] [client 192.168.178.46:61844] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 163\n'

```
</details>

<details>
<summary>Database logs</summary>

```

2018-04-15 12:13:27 1639035712 [Note] /usr/sbin/mysqld: Shutdown complete

2018-04-15 12:14:14 1989058560 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2018-04-15 12:14:14 1989058560 [Note] InnoDB: The InnoDB memory heap is disabled
2018-04-15 12:14:14 1989058560 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-04-15 12:14:14 1989058560 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2018-04-15 12:14:14 1989058560 [Note] InnoDB: Compressed tables use zlib 1.2.8
2018-04-15 12:14:14 1989058560 [Note] InnoDB: Using Linux native AIO
2018-04-15 12:14:14 1989058560 [Note] InnoDB: Using generic crc32 instructions
2018-04-15 12:14:14 1989058560 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2018-04-15 12:14:14 1989058560 [Note] InnoDB: Completed initialization of buffer pool
2018-04-15 12:14:14 1989058560 [Note] InnoDB: Highest supported file format is Barracuda.
2018-04-15 12:14:15 1989058560 [Note] InnoDB: 128 rollback segment(s) are active.
2018-04-15 12:14:15 1989058560 [Note] InnoDB: Waiting for purge to start
2018-04-15 12:14:15 1989058560 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.35-80.0 started; log sequence number 1758350525
2018-04-15 12:14:15 1447031616 [Note] InnoDB: Dumping buffer pool(s) not yet started
2018-04-15 12:14:15 1989058560 [Note] Plugin 'FEEDBACK' is disabled.
2018-04-15 12:14:15 1989058560 [Note] Server socket created on IP: '127.0.0.1'.
2018-04-15 12:14:15 1989058560 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.1.23-MariaDB-9+deb9u1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Raspbian 9.0

```
</details>

<details>
<summary>Nextcloud logs</summary>

```

{"reqId":"WoLp7n8AAQEAAExOEnoAAFYV","level":1,"time":"2018-02-13T13:37:33+00:00","remoteAddr":"192.168.178.46","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=2Q1cDtnU9aXnQ2CK%2BIXc6uTolxWl8Ofi65I0Pr241ro%3D%3Al2QJVKiFgJW1BSyhz7O%2BhYzdwWX8tsigpv5gctCXh9A%3D","message":"\\OC\\Repair::info: Repair info: .step-previous-update removed","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}
{"reqId":"WoLp7n8AAQEAAExOEnoAAFYV","level":1,"time":"2018-02-13T13:37:33+00:00","remoteAddr":"192.168.178.46","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=2Q1cDtnU9aXnQ2CK%2BIXc6uTolxWl8Ofi65I0Pr241ro%3D%3Al2QJVKiFgJW1BSyhz7O%2BhYzdwWX8tsigpv5gctCXh9A%3D","message":"\\OC\\Repair::info: Repair info: .step file moved to .step-previous-update","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}
{"reqId":"WoLp7n8AAQEAAExOEnoAAFYV","level":1,"time":"2018-02-13T13:37:33+00:00","remoteAddr":"192.168.178.46","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=2Q1cDtnU9aXnQ2CK%2BIXc6uTolxWl8Ofi65I0Pr241ro%3D%3Al2QJVKiFgJW1BSyhz7O%2BhYzdwWX8tsigpv5gctCXh9A%3D","message":"\\OC\\Repair::step: Repair step: Add move avatar background job","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}
{"reqId":"WoLp7n8AAQEAAExOEnoAAFYV","level":1,"time":"2018-02-13T13:37:33+00:00","remoteAddr":"192.168.178.46","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=2Q1cDtnU9aXnQ2CK%2BIXc6uTolxWl8Ofi65I0Pr241ro%3D%3Al2QJVKiFgJW1BSyhz7O%2BhYzdwWX8tsigpv5gctCXh9A%3D","message":"\\OC\\Repair::info: Repair info: Repair step already executed","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}
{"reqId":"WoLp7n8AAQEAAExOEnoAAFYV","level":1,"time":"2018-02-13T13:37:33+00:00","remoteAddr":"192.168.178.46","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=2Q1cDtnU9aXnQ2CK%2BIXc6uTolxWl8Ofi65I0Pr241ro%3D%3Al2QJVKiFgJW1BSyhz7O%2BhYzdwWX8tsigpv5gctCXh9A%3D","message":"\\OC\\Repair::step: Repair step: Add preview cleanup background jobs","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}
{"reqId":"WoLp7n8AAQEAAExOEnoAAFYV","level":1,"time":"2018-02-13T13:37:33+00:00","remoteAddr":"192.168.178.46","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=2Q1cDtnU9aXnQ2CK%2BIXc6uTolxWl8Ofi65I0Pr241ro%3D%3Al2QJVKiFgJW1BSyhz7O%2BhYzdwWX8tsigpv5gctCXh9A%3D","message":"\\OC\\Repair::step: Repair step: Fix potential broken mount points","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}
{"reqId":"WoLp7n8AAQEAAExOEnoAAFYV","level":1,"time":"2018-02-13T13:37:33+00:00","remoteAddr":"192.168.178.46","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=2Q1cDtnU9aXnQ2CK%2BIXc6uTolxWl8Ofi65I0Pr241ro%3D%3Al2QJVKiFgJW1BSyhz7O%2BhYzdwWX8tsigpv5gctCXh9A%3D","message":"\\OC\\Repair::info: Repair info: No mounts updated","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}
{"reqId":"WoLp7n8AAQEAAExOEnoAAFYV","level":1,"time":"2018-02-13T13:37:33+00:00","remoteAddr":"192.168.178.46","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=2Q1cDtnU9aXnQ2CK%2BIXc6uTolxWl8Ofi65I0Pr241ro%3D%3Al2QJVKiFgJW1BSyhz7O%2BhYzdwWX8tsigpv5gctCXh9A%3D","message":"\\OC\\Repair::step: Repair step: Repair language codes","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}
{"reqId":"WoLp7n8AAQEAAExOEnoAAFYV","level":1,"time":"2018-02-13T13:37:33+00:00","remoteAddr":"192.168.178.46","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=2Q1cDtnU9aXnQ2CK%2BIXc6uTolxWl8Ofi65I0Pr241ro%3D%3Al2QJVKiFgJW1BSyhz7O%2BhYzdwWX8tsigpv5gctCXh9A%3D","message":"\\OC\\Repair::step: Repair step: Install new core bundle components","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}
{"reqId":"WoLp7n8AAQEAAExOEnoAAFYV","level":1,"time":"2018-02-13T13:37:33+00:00","remoteAddr":"192.168.178.46","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=2Q1cDtnU9aXnQ2CK%2BIXc6uTolxWl8Ofi65I0Pr241ro%3D%3Al2QJVKiFgJW1BSyhz7O%2BhYzdwWX8tsigpv5gctCXh9A%3D","message":"\\OC\\Repair::step: Repair step: Repair invalid paths in file cache","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}
{"reqId":"WoLp7n8AAQEAAExOEnoAAFYV","level":1,"time":"2018-02-13T13:37:33+00:00","remoteAddr":"192.168.178.46","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=2Q1cDtnU9aXnQ2CK%2BIXc6uTolxWl8Ofi65I0Pr241ro%3D%3Al2QJVKiFgJW1BSyhz7O%2BhYzdwWX8tsigpv5gctCXh9A%3D","message":"\\OC\\Repair::step: Repair step: Rename folder with user specific keys","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}
{"reqId":"WoLp7n8AAQEAAExOEnoAAFYV","level":1,"time":"2018-02-13T13:37:33+00:00","remoteAddr":"192.168.178.46","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=2Q1cDtnU9aXnQ2CK%2BIXc6uTolxWl8Ofi65I0Pr241ro%3D%3Al2QJVKiFgJW1BSyhz7O%2BhYzdwWX8tsigpv5gctCXh9A%3D","message":"\\OC\\Repair::step: Repair step: Add log rotate job","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}
{"reqId":"WoLp7n8AAQEAAExOEnoAAFYV","level":1,"time":"2018-02-13T13:37:33+00:00","remoteAddr":"192.168.178.46","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=2Q1cDtnU9aXnQ2CK%2BIXc6uTolxWl8Ofi65I0Pr241ro%3D%3Al2QJVKiFgJW1BSyhz7O%2BhYzdwWX8tsigpv5gctCXh9A%3D","message":"\\OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}
{"reqId":"WoLp7n8AAQEAAExOEnoAAFYV","level":1,"time":"2018-02-13T13:37:56+00:00","remoteAddr":"192.168.178.46","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=2Q1cDtnU9aXnQ2CK%2BIXc6uTolxWl8Ofi65I0Pr241ro%3D%3Al2QJVKiFgJW1BSyhz7O%2BhYzdwWX8tsigpv5gctCXh9A%3D","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}
{"reqId":"WoLp7n8AAQEAAExOEnoAAFYV","level":1,"time":"2018-02-13T13:37:56+00:00","remoteAddr":"192.168.178.46","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=2Q1cDtnU9aXnQ2CK%2BIXc6uTolxWl8Ofi65I0Pr241ro%3D%3Al2QJVKiFgJW1BSyhz7O%2BhYzdwWX8tsigpv5gctCXh9A%3D","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"WoLp7n8AAQEAAExOEnoAAFYV","level":1,"time":"2018-02-13T13:37:56+00:00","remoteAddr":"192.168.178.46","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=2Q1cDtnU9aXnQ2CK%2BIXc6uTolxWl8Ofi65I0Pr241ro%3D%3Al2QJVKiFgJW1BSyhz7O%2BhYzdwWX8tsigpv5gctCXh9A%3D","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"WoLp7n8AAQEAAExOEnoAAFYV","level":1,"time":"2018-02-13T13:37:56+00:00","remoteAddr":"192.168.178.46","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=2Q1cDtnU9aXnQ2CK%2BIXc6uTolxWl8Ofi65I0Pr241ro%3D%3Al2QJVKiFgJW1BSyhz7O%2BhYzdwWX8tsigpv5gctCXh9A%3D","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"WpLieX8AAQEAAF1rPYYAAAUL","level":3,"time":"2018-02-25T16:21:18+00:00","remoteAddr":"192.168.178.46","user":"martin","app":"PHP","method":"GET","url":"\/index.php\/core\/preview.png?file=%2FKultur%2FTexte%2FAntifragilit%C3%A4t.txt&c=1519640258&x=45&y=45&forceIcon=0","message":"touch(): Unable to create file \/media\/ncdata\/ncdata\/appdata_ocfe6u02waok\/preview\/64596\/64-64-crop.png because No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#204","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"WpLjwn8AAQEAAF1rPcQAAAEK","level":3,"time":"2018-02-25T16:26:42+00:00","remoteAddr":"192.168.178.46","user":"martin","app":"files_texteditor","method":"PUT","url":"\/index.php\/apps\/files_texteditor\/ajax\/savefile","message":"File: \/Kultur\/Texte\/Antifragilit\u00e4t.txt modified since opening.","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"Wp0qan8AAQEAAEcx6@cAAAED","level":2,"time":"2018-03-05T11:30:51+00:00","remoteAddr":"192.168.178.46","user":"--","app":"core","method":"POST","url":"\/index.php\/login","message":"Login failed: 'video' (Remote IP: '192.168.178.46')","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}

```
</details>

**Comment by datenbrei** [comment]
Sone additional informations: 

```
$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    0 931,5G  0 disk
├─sda1        8:1    0     4G  0 part
└─sda2        8:2    0 927,5G  0 part /media/ncdata
mmcblk0     179:0    0  29,7G  0 disk
├─mmcblk0p1 179:1    0  41,8M  0 part /boot
└─mmcblk0p2 179:2    0  29,7G  0 part /
```

```
$ ls -la /media
insgesamt 24
drwxr-xr-x  3 root root 4096 Apr 15 12:13 .
drwxr-xr-x 22 root root 4096 Apr 15 11:32 ..
drwxr-xr-x  1 root root   60 Apr 15 11:41 ncdata
lrwxrwxrwx  1 root root   13 Apr 15 12:13 USBdrive -> /media/ncdata
```

```
root@nextcloudpi:/media# grep datadir /var/www/nextcloud/config/config.php
  'datadirectory' => '/media/ncdata/ncdata',
```

**Comment by datenbrei** [comment]
I did a reinstall, so this issue gets closed now.
