### ISSUE TITLE
after v0.56.6 update no connection to NCP

### ISSUE THREAD

**Issue by derdershat** [nextcloud/nextcloudpi#513]
Hi Nacho, 

I have some problems after last update and see some errors like in NCP report but have no clue how to fix this... what`s the problem here? did an update from v0.56.4 to v0.56.6 and after reboot of my PI (with raspbian stretch + NCP by the way) I have no access.

I changed my DNS address here in NCP report - isn`t it too a sensitive value? 

would be really nice to have some help  

<--! Paste this in GitHub report -->

<details>
<summary>NextCloudPlus diagnostics</summary>

```

NextCloudPlus version  v0.56.6
distribution           Raspbian GNU/Linux 9 \n \l
automount              no
USB devices            none
datadir                /media/CLOUDDATA/NEXTCLOUDFILES
data in SD             no
data filesystem        ext2/ext3
data disk usage        15G/17G
rootfs usage           3,3G/13G
swapfile               /var/swap
Nextcloud check        ok
Nextcloud version      13.0.2.1
HTTPD service          down
PHP service            up
MariaDB service        up
Redis service          up
Postfix service        up
internet check         ok
port check 80          closed
port check 443         closed
IP                     192.168.78.25
gateway                192.168.78.1
interface              eth0
certificates           myname.spdns.de
NAT loopback           yes
uptime                 2min

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "1": "192.168.78.25",
            "5": "nextcloudpi.local",
            "2": "myname.spdns.de",
            "4": "myname.spdns.de"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/myname.spdns.de",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "loglevel": "2",
        "log_type": "file",
        "maintenance": false,
        "theme": "",
        "updater.release.channel": "stable"
    }
}

```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Tue May 22 14:40:59.468113 2018] [authz_host:error] [pid 8255:tid 1968649264] [client 192.168.78.2:3641] AH01753: access check of 'localhost' to /minified.js failed, reason: unable to get the remote host name
[Tue May 22 14:40:59.767799 2018] [authz_host:error] [pid 8255:tid 1926706224] [client 192.168.78.2:3641] AH01753: access check of 'localhost' to /img/poweroff.svg failed, reason: unable to get the remote host name
[Tue May 22 14:40:59.768213 2018] [authz_host:error] [pid 8255:tid 1926706224] [client 192.168.78.2:3641] AH01753: access check of 'localhost' to /img/reboot.svg failed, reason: unable to get the remote host name
[Tue May 22 14:40:59.985098 2018] [authz_host:error] [pid 8255:tid 1909929008] [client 192.168.78.2:3641] AH01753: access check of 'localhost' to /ncp-output.php failed, reason: unable to get the remote host name
[Tue May 22 14:40:59.986359 2018] [authz_host:error] [pid 8255:tid 1901540400] [client 192.168.78.2:3641] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Tue May 22 14:40:59.986458 2018] [authz_host:error] [pid 8255:tid 1893151792] [client 192.168.78.2:3641] AH01753: access check of 'localhost' to /core/img/actions/triangle-s.svg failed, reason: unable to get the remote host name
[Tue May 22 14:40:59.987058 2018] [authz_host:error] [pid 8255:tid 1893151792] [client 192.168.78.2:3641] AH01753: access check of 'localhost' to /img/nc-button.svg failed, reason: unable to get the remote host name
[Tue May 22 14:40:59.987672 2018] [authz_host:error] [pid 8255:tid 1884763184] [client 192.168.78.2:3641] AH01753: access check of 'localhost' to /img/dashboard.svg failed, reason: unable to get the remote host name
[Tue May 22 14:40:59.987731 2018] [authz_host:error] [pid 8255:tid 1893151792] [client 192.168.78.2:3641] AH01753: access check of 'localhost' to /img/settings-white.svg failed, reason: unable to get the remote host name
[Tue May 22 14:40:59.989619 2018] [authz_host:error] [pid 8255:tid 1893151792] [client 192.168.78.2:3641] AH01753: access check of 'localhost' to /img/wizard.svg failed, reason: unable to get the remote host name
[Tue May 22 14:40:59.989686 2018] [authz_host:error] [pid 8255:tid 1884763184] [client 192.168.78.2:3641] AH01753: access check of 'localhost' to /img/info-white.svg failed, reason: unable to get the remote host name
[Tue May 22 14:41:00.642317 2018] [proxy_fcgi:error] [pid 8255:tid 1909929008] [client 192.168.78.2:3641] AH01071: Got error 'PHP message: PHP Warning:  touch(): Utime failed: Permission denied in /var/www/ncp-web/ncp-output.php on line 81\n'
[Tue May 22 14:41:04.818584 2018] [proxy_fcgi:error] [pid 8255:tid 1901540400] [client 192.168.78.2:3641] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 163\n'
[Tue May 22 14:41:04.889279 2018] [authz_host:error] [pid 8255:tid 1867969584] [client 192.168.78.2:3641] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Tue May 22 14:41:06.926443 2018] [proxy_fcgi:error] [pid 8255:tid 1867969584] [client 192.168.78.2:3641] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 163\n'
[Tue May 22 14:59:43.511519 2018] [authz_host:error] [pid 8255:tid 1859572784] [client 192.168.78.2:3641] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Tue May 22 14:59:43.545760 2018] [proxy_fcgi:error] [pid 8255:tid 1859572784] [client 192.168.78.2:3641] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 163\n'
[Tue May 22 14:59:45.925881 2018] [proxy_fcgi:error] [pid 8255:tid 1909929008] [client 192.168.78.2:3641] AH01067: Failed to read FastCGI header
[Tue May 22 14:59:45.973900 2018] [proxy_fcgi:error] [pid 8255:tid 1909929008] (104)Connection reset by peer: [client 192.168.78.2:3641] AH01075: Error dispatching request to :4443:
[Tue May 22 14:59:47.276420 2018] [mpm_event:notice] [pid 787:tid 1996374016] AH00491: caught SIGTERM, shutting down

```
</details>

<details>
<summary>Database logs</summary>

```

2018-05-22 16:34:04 1639236416 [Note] /usr/sbin/mysqld: Shutdown complete

2018-05-22 16:34:33 1995927552 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2018-05-22 16:34:33 1995927552 [Note] InnoDB: The InnoDB memory heap is disabled
2018-05-22 16:34:33 1995927552 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-05-22 16:34:33 1995927552 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2018-05-22 16:34:33 1995927552 [Note] InnoDB: Compressed tables use zlib 1.2.8
2018-05-22 16:34:33 1995927552 [Note] InnoDB: Using Linux native AIO
2018-05-22 16:34:33 1995927552 [Note] InnoDB: Using generic crc32 instructions
2018-05-22 16:34:33 1995927552 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2018-05-22 16:34:33 1995927552 [Note] InnoDB: Completed initialization of buffer pool
2018-05-22 16:34:33 1995927552 [Note] InnoDB: Highest supported file format is Barracuda.
2018-05-22 16:34:34 1995927552 [Note] InnoDB: 128 rollback segment(s) are active.
2018-05-22 16:34:34 1995927552 [Note] InnoDB: Waiting for purge to start
2018-05-22 16:34:34 1995927552 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.35-80.0 started; log sequence number 1027575516
2018-05-22 16:34:34 1447031616 [Note] InnoDB: Dumping buffer pool(s) not yet started
2018-05-22 16:34:34 1995927552 [Note] Plugin 'FEEDBACK' is disabled.
2018-05-22 16:34:34 1995927552 [Note] Server socket created on IP: '127.0.0.1'.
2018-05-22 16:34:34 1995927552 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.1.23-MariaDB-9+deb9u1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Raspbian 9.0

```
</details>

<details>
<summary>Nextcloud logs</summary>

```

{"reqId":"WwLxjn8AAQEAAAPNgKgAAABM","level":4,"time":"2018-05-21T16:19:26+00:00","remoteAddr":"93.239.148.241","user":"Steph","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/files\/Steph\/EberStephCloud\/STUFF\/PSTools\/PsExec.exe","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"expected filesize 396480 got 81920\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(151): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #22)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1096): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('PsExec.exe', Resource id #22)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('files\\\/Steph\\\/Ebe...', Resource id #22, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/nextcloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/nextcl...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":180}","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.3 (build 1) (Nextcloud)","version":"13.0.2.1"}
{"reqId":"WwM6y38AAQEAAANzATIAAAAD","level":2,"time":"2018-05-21T21:31:56+00:00","remoteAddr":"212.129.17.23","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"212.129.17.23\" tried to access using \"93.239.148.241\" as host.","userAgent":"--","version":"13.0.2.1"}
{"reqId":"WwNkkn8AAQEAAAN082IAAABD","level":2,"time":"2018-05-22T00:30:10+00:00","remoteAddr":"54.179.153.41","user":"--","app":"core","method":"GET","url":"\/admin\/config.php","message":"Trusted domain error. \"54.179.153.41\" tried to access using \"93.239.148.241\" as host.","userAgent":"curl\/7.35.0","version":"13.0.2.1"}
{"reqId":"WwN0en8AAQEAAAN08@MAAABJ","level":2,"time":"2018-05-22T01:38:02+00:00","remoteAddr":"62.233.65.182","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"62.233.65.182\" tried to access using \"93.239.148.241\" as host.","userAgent":"--","version":"13.0.2.1"}
{"reqId":"WwODnn8AAQEAAAN08-4AAABQ","level":2,"time":"2018-05-22T02:42:39+00:00","remoteAddr":"106.75.50.37","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"106.75.50.37\" tried to access using \"93.239.148.241:443\" as host.","userAgent":"--","version":"13.0.2.1"}
{"reqId":"WwODoH8AAQEAAAN08-8AAABM","level":2,"time":"2018-05-22T02:42:40+00:00","remoteAddr":"106.75.2.81","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"106.75.2.81\" tried to access using \"93.239.148.241\" as host.","userAgent":"Mozilla\/5.0 (Windows NT 6.1) AppleWebKit\/537.1 (KHTML, like Gecko) Chrome\/21.0.1180.89 Safari\/537.1","version":"13.0.2.1"}
{"reqId":"WwOuRX8AAQEAACA-SnsAAAAY","level":2,"time":"2018-05-22T05:44:38+00:00","remoteAddr":"80.82.77.33","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"80.82.77.33\" tried to access using \"93.239.148.241\" as host.","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/34.0.1847.137 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"WwOuTX8AAQEAACA-Sn0AAAAM","level":2,"time":"2018-05-22T05:44:45+00:00","remoteAddr":"80.82.77.33","user":"--","app":"core","method":"GET","url":"\/sitemap.xml","message":"Trusted domain error. \"80.82.77.33\" tried to access using \"93.239.148.241\" as host.","userAgent":"--","version":"13.0.2.1"}
{"reqId":"WwOuTX8AAQEAACA-Sn4AAAAG","level":2,"time":"2018-05-22T05:44:46+00:00","remoteAddr":"80.82.77.33","user":"--","app":"core","method":"GET","url":"\/.well-known\/security.txt","message":"Trusted domain error. \"80.82.77.33\" tried to access using \"93.239.148.241\" as host.","userAgent":"--","version":"13.0.2.1"}
{"reqId":"WwOuUH8AAQEAACA-Sn8AAAAK","level":2,"time":"2018-05-22T05:44:48+00:00","remoteAddr":"80.82.77.33","user":"--","app":"core","method":"GET","url":"\/favicon.ico","message":"Trusted domain error. \"80.82.77.33\" tried to access using \"93.239.148.241\" as host.","userAgent":"python-requests\/2.13.0","version":"13.0.2.1"}
{"reqId":"WwO9zn8AAQEAACA-SocAAAAE","level":2,"time":"2018-05-22T06:50:55+00:00","remoteAddr":"217.61.97.37","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"217.61.97.37\" tried to access using \"93.239.148.241\" as host.","userAgent":"--","version":"13.0.2.1"}
{"reqId":"WwPQ038AAQEAACBACWcAAABM","level":2,"time":"2018-05-22T08:12:03+00:00","remoteAddr":"54.80.60.4","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"54.80.60.4\" tried to access using \"93.239.148.241:443\" as host.","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/50.0.2661.102 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"WwPuwH8AAQEAACA-Sv4AAAAB","level":2,"time":"2018-05-22T10:19:44+00:00","remoteAddr":"212.129.17.23","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"212.129.17.23\" tried to access using \"93.239.148.241\" as host.","userAgent":"Mozilla\/5.0 (Windows NT 5.1; rv:9.0.1) Gecko\/20100101 Firefox\/9.0.1","version":"13.0.2.1"}
{"reqId":"WwPuwH8AAQEAACBACewAAABF","level":2,"time":"2018-05-22T10:19:44+00:00","remoteAddr":"212.129.17.23","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"212.129.17.23\" tried to access using \"93.239.148.241\" as host.","userAgent":"Mozilla\/5.0 (Windows NT 5.1; rv:9.0.1) Gecko\/20100101 Firefox\/9.0.1","version":"13.0.2.1"}
{"reqId":"WwPuwX8AAQEAACBACe0AAABE","level":2,"time":"2018-05-22T10:19:45+00:00","remoteAddr":"212.129.17.23","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"212.129.17.23\" tried to access using \"93.239.148.241\" as host.","userAgent":"Mozilla\/5.0 (Windows NT 5.1; rv:9.0.1) Gecko\/20100101 Firefox\/9.0.1","version":"13.0.2.1"}
{"reqId":"WwPuwX8AAQEAACA-Sv8AAAAJ","level":2,"time":"2018-05-22T10:19:45+00:00","remoteAddr":"212.129.17.23","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"212.129.17.23\" tried to access using \"93.239.148.241\" as host.","userAgent":"Mozilla\/5.0 (Windows NT 5.1; rv:9.0.1) Gecko\/20100101 Firefox\/9.0.1","version":"13.0.2.1"}
{"reqId":"WwPuwX8AAQEAACBACe4AAABG","level":2,"time":"2018-05-22T10:19:45+00:00","remoteAddr":"212.129.17.23","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"212.129.17.23\" tried to access using \"93.239.148.241\" as host.","userAgent":"Mozilla\/5.0 (Windows NT 5.1; rv:9.0.1) Gecko\/20100101 Firefox\/9.0.1","version":"13.0.2.1"}
{"reqId":"WwPuwn8AAQEAACBACe8AAABD","level":2,"time":"2018-05-22T10:19:46+00:00","remoteAddr":"212.129.17.23","user":"--","app":"core","method":"GET","url":"\/HNAP1\/","message":"Trusted domain error. \"212.129.17.23\" tried to access using \"93.239.148.241\" as host.","userAgent":"Mozilla\/5.0 (Windows NT 5.1; rv:9.0.1) Gecko\/20100101 Firefox\/9.0.1","version":"13.0.2.1"}
{"reqId":"WwPuwn8AAQEAACA-SwAAAAAL","level":2,"time":"2018-05-22T10:19:46+00:00","remoteAddr":"212.129.17.23","user":"--","app":"core","method":"GET","url":"\/HNAP1\/","message":"Trusted domain error. \"212.129.17.23\" tried to access using \"93.239.148.241\" as host.","userAgent":"Mozilla\/5.0 (Windows NT 5.1; rv:9.0.1) Gecko\/20100101 Firefox\/9.0.1","version":"13.0.2.1"}
{"reqId":"WwPuw38AAQEAACA-SwEAAAAH","level":2,"time":"2018-05-22T10:19:47+00:00","remoteAddr":"212.129.17.23","user":"--","app":"core","method":"GET","url":"\/HNAP1\/","message":"Trusted domain error. \"212.129.17.23\" tried to access using \"93.239.148.241\" as host.","userAgent":"Mozilla\/5.0 (Windows NT 5.1; rv:9.0.1) Gecko\/20100101 Firefox\/9.0.1","version":"13.0.2.1"}

```
</details>

**Comment by derdershat** [comment]
superb! this fixed it 

thank you very much Nacho 

greats
derdershat
