### ISSUE TITLE
Blank page on https but webui accessible

### ISSUE THREAD

**Issue by Olivl** [nextcloud/nextcloudpi#524]
### PROBLEMS

Hello,
After the last upgrade, i've problems with nextcloudpi, i get an error 500 in the browser but i can access to the web-ui (443).
mysql is running, apache2 too.

My data and database is in an usbdrive

When i run a nc-backup i have error "access denied for user ncadmin"
The password is correct in config and mysql

When i try to run a fix-permission, it return me "data dir not found"

Can you help me to find how to resolve this problem?

<details>
<summary>NextCloudPi diagnostics</summary>

```

NextCloudPi version  v0.56.16
NextCloudPi image    NextCloudPi_02-06-18
distribution         Raspbian GNU/Linux 9 \n \l
automount            yes
USB devices          sda 
datadir              /media/USBdrive/ncdata
data in SD           no
data filesystem      btrfs
data disk usage      12G/448G
rootfs usage         1,8G/15G
swapfile             /var/swap
Nextcloud check      error
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   192.168.1.89
gateway              192.168.1.1
interface            eth0
certificates         cloud.****************.com
NAT loopback         no
uptime               29min

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'ncadmin'@'localhost' (using password: YES) in /var/www/nextcloud/lib/private/DB/Connection.php:64
Stack trace:
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/nextcloud/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/nextcloud/lib/private/DB/ConnectionFactory.php(152): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /var/www/nextcloud/lib/private/Server.php(618): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OCP\\IDBConnecti...')
#10 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IDBConnecti...')
#11 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(164): OC\ServerContainer->query('OCP\\IDBConnecti...')
#12 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#13 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('DatabaseConnect...')
#14 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#15 /var/www/nextcloud/lib/private/Server.php(1490): OC\ServerContainer->query('DatabaseConnect...')
#16 /var/www/nextcloud/lib/private/Server.php(331): OC\Server->getDatabaseConnection()
#17 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#18 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OC\\Authenticati...')
#19 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#20 /var/www/nextcloud/lib/private/Server.php(335): OC\ServerContainer->query('OC\\Authenticati...')
#21 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#22 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OC\\Authenticati...')
#23 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#24 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(164): OC\ServerContainer->query('OC\\Authenticati...')
#25 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#26 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OC\\Authenticati...')
#27 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#28 /var/www/nextcloud/lib/private/Server.php(351): OC\ServerContainer->query('OC\\Authenticati...')
#29 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#30 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OCP\\IUserSessio...')
#31 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IUserSessio...')
#32 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(164): OC\ServerContainer->query('OCP\\IUserSessio...')
#33 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#34 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('UserSession')
#35 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('UserSession')
#36 /var/www/nextcloud/lib/private/Server.php(1359): OC\ServerContainer->query('UserSession')
#37 /var/www/nextcloud/lib/private/Server.php(678): OC\Server->getUserSession()
#38 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#39 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OC\\App\\AppManag...')
#40 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\App\\AppManag...')
#41 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(164): OC\ServerContainer->query('OC\\App\\AppManag...')
#42 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#43 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('AppManager')
#44 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#45 /var/www/nextcloud/lib/private/Server.php(1663): OC\ServerContainer->query('AppManager')
#46 /var/www/nextcloud/lib/private/legacy/app.php(330): OC\Server->getAppManager()
#47 /var/www/nextcloud/lib/private/legacy/app.php(113): OC_App::getEnabledApps()
#48 /var/www/nextcloud/lib/base.php(661): OC_App::loadApps(Array)
#49 /var/www/nextcloud/lib/base.php(1080): OC::init()
#50 /var/www/nextcloud/console.php(46): require_once('/var/www/nextcl...')
#51 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#52 {main}
```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Sat Jun 02 15:33:25.303698 2018] [proxy_fcgi:error] [pid 849:tid 1792910384] [client 192.168.1.34:62423] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'
[Sat Jun 02 15:33:29.309842 2018] [proxy_fcgi:error] [pid 849:tid 1784521776] [client 192.168.1.34:62423] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'
[Sat Jun 02 15:33:37.117005 2018] [proxy_fcgi:error] [pid 849:tid 1985848368] [client 192.168.1.34:62423] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'
[Sat Jun 02 15:33:55.569682 2018] [proxy_fcgi:error] [pid 849:tid 1977459760] [client 192.168.1.34:62423] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'
[Sat Jun 02 15:34:04.837584 2018] [proxy_fcgi:error] [pid 849:tid 1969071152] [client 192.168.1.34:62423] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'
[Sat Jun 02 15:34:06.574051 2018] [proxy_fcgi:error] [pid 849:tid 1910350896] [client 192.168.1.34:62486] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'
[Sat Jun 02 15:34:06.645257 2018] [proxy_fcgi:error] [pid 849:tid 1960682544] [client 192.168.1.34:62486] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'
[Sat Jun 02 15:34:07.664043 2018] [proxy_fcgi:error] [pid 849:tid 1834853424] [client 192.168.1.34:62486] AH01071: Got error 'PHP message: PHP Warning:  touch(): Utime failed: Permission denied in /var/www/ncp-web/ncp-output.php on line 81\n'
[Sat Jun 02 15:34:11.328918 2018] [proxy_fcgi:error] [pid 849:tid 1818076208] [client 192.168.1.34:62486] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'
[Sat Jun 02 15:34:12.945715 2018] [proxy_fcgi:error] [pid 849:tid 1809687600] [client 192.168.1.34:62486] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'
[Sat Jun 02 15:34:28.189943 2018] [proxy_fcgi:error] [pid 849:tid 1792910384] [client 192.168.1.34:62486] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'
[Sat Jun 02 15:34:46.726215 2018] [proxy_fcgi:error] [pid 849:tid 1985848368] [client 192.168.1.34:62486] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'
[Sat Jun 02 15:34:51.892322 2018] [proxy_fcgi:error] [pid 849:tid 1977459760] [client 192.168.1.34:62486] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'
[Sat Jun 02 15:34:52.770877 2018] [proxy_fcgi:error] [pid 848:tid 1977459760] [client 192.168.1.34:62492] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'
[Sat Jun 02 15:34:53.771840 2018] [proxy_fcgi:error] [pid 848:tid 1860019248] [client 192.168.1.34:62492] AH01071: Got error 'PHP message: PHP Warning:  touch(): Utime failed: Permission denied in /var/www/ncp-web/ncp-output.php on line 81\n'
[Sat Jun 02 15:34:57.418666 2018] [proxy_fcgi:error] [pid 848:tid 1851630640] [client 192.168.1.34:62492] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'
[Sat Jun 02 15:34:58.903486 2018] [proxy_fcgi:error] [pid 848:tid 1843242032] [client 192.168.1.34:62492] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'
[Sat Jun 02 15:35:18.691462 2018] [proxy_fcgi:error] [pid 848:tid 1834853424] [client 192.168.1.34:62492] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'
[Sat Jun 02 15:35:22.481469 2018] [proxy_fcgi:error] [pid 848:tid 1818076208] [client 192.168.1.34:62492] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'
[Sat Jun 02 15:36:08.065565 2018] [proxy_fcgi:error] [pid 848:tid 1801298992] [client 192.168.1.34:62492] AH01071: Got error 'PHP message: PHP Warning:  fclose(): supplied resource is not a valid stream resource in /var/www/ncp-web/L10N.php on line 166\n'

```
</details>

<details>
<summary>Database logs</summary>

```

2018-06-01 19:37:11 1978807104 [Note] /usr/sbin/mysqld: Shutdown complete

2018-06-02 15:25:18 1989001216 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2018-06-02 15:25:18 1989001216 [Note] InnoDB: The InnoDB memory heap is disabled
2018-06-02 15:25:18 1989001216 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-06-02 15:25:18 1989001216 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2018-06-02 15:25:18 1989001216 [Note] InnoDB: Compressed tables use zlib 1.2.8
2018-06-02 15:25:18 1989001216 [Note] InnoDB: Using Linux native AIO
2018-06-02 15:25:18 1989001216 [Note] InnoDB: Using generic crc32 instructions
2018-06-02 15:25:18 1989001216 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2018-06-02 15:25:18 1989001216 [Note] InnoDB: Completed initialization of buffer pool
2018-06-02 15:25:18 1989001216 [Note] InnoDB: Highest supported file format is Barracuda.
2018-06-02 15:25:19 1989001216 [Note] InnoDB: 128 rollback segment(s) are active.
2018-06-02 15:25:19 1989001216 [Note] InnoDB: Waiting for purge to start
2018-06-02 15:25:19 1989001216 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.35-80.0 started; log sequence number 471505872
2018-06-02 15:25:19 1447031616 [Note] InnoDB: Dumping buffer pool(s) not yet started
2018-06-02 15:25:19 1989001216 [Note] Plugin 'FEEDBACK' is disabled.
2018-06-02 15:25:19 1989001216 [Note] Server socket created on IP: '127.0.0.1'.
2018-06-02 15:25:19 1989001216 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.1.23-MariaDB-9+deb9u1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Raspbian 9.0

```
</details>

<details>
<summary>Nextcloud logs</summary>

```

```
</details>

**Comment by nachoparker** [comment]
what is the output of 

```
systemctl status nc-provisioning
```

**Comment by Olivl** [comment]
Hi,

Here is the output : 

`● nc-provisioning.service - Randomize passwords on first boot
   Loaded: loaded (/usr/lib/systemd/system/nc-provisioning.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Mon 2018-06-04 16:20:23 CEST; 20min ago
  Process: 1296 ExecStart=/bin/bash /usr/local/bin/ncp-provisioning.sh (code=exited, status=0/SUCCESS)
 Main PID: 1296 (code=exited, status=0/SUCCESS)

juin 04 16:20:23 nextcloudpi systemd[1]: Started Randomize passwords on first boot.
juin 04 16:20:23 nextcloudpi bash[1296]: Updating NextCloud config with Redis password
juin 04 16:20:23 nextcloudpi bash[1296]: Updating NextCloud config with MariaDB password`

**Comment by BatPio** [comment]
@Olivl 

Have you found the solution? I have the same problem.

**Comment by nachoparker** [comment]
For whatever reason, your database access is not right. What happens if you run

```
systemctl start nc-provisioning
systemctl status nc-provisioning
cat /root/.my.cnf
cat /var/www/nextcloud/config/config.php
```

Does it still not work? Can you share the output?

**Comment by BatPio** [comment]
Strange, it looks that update changed ncadmin password or config.php .
I changed ncadmin password to same as is set in /root/.my.cnf and now it work.

**Comment by nachoparker** [comment]
does it still work after a reboot?

**Comment by BatPio** [comment]
Yes, I restarted my raspberry and nc still works_
