### ISSUE TITLE
Testing update to 14.0.3 - v0.64

### ISSUE THREAD

**Issue by Iolaum** [nextcloud/nextcloudpi#681]
While trying to update from master (v0.62.6) I had this problem:

```
$ sudo ncp-update devel
INFO: updating to development branch 'devel'
Downloading updates
Performing updates
./update.sh: line 291: syntax error near unexpected token `||'
./update.sh: line 291: `      [[ -f /etc/rsyslog.d/20-ufw.conf ]] && { grep -q "^\& stop" /etc/rsyslog.d/20-ufw.conf &> ||  echo "& stop" >> /etc/rsyslog.d/20-ufw.conf; }'
```

Reverting back to master worked successfully:

```
$ sudo ncp-update master
Downloading updates
Performing updates
Installing nc-backup
Installing nc-restore
previewgenerator already installed
previewgenerator enabled
Activating nc-autoupdate-nc
automatic Nextcloud updates enabled
System config value trusted_domains => 7 set to string nextcloudpi
System config value trusted_domains => 8 set to string nextcloudpi.lan
NextCloudPi updated to version v0.62.6
```

### NCP report (after failed update):

<details>
<summary>NextCloudPi diagnostics</summary>

```

NextCloudPi version  v0.62.6
NextCloudPi image    NextCloudPi_12-04-17
distribution         Raspbian GNU/Linux 9 \n \l
automount            yes
USB devices          sda 
datadir              /media/USBdrive/ncdata
data in SD           no
data filesystem      ext2/ext3
data disk usage      388G/917G
rootfs usage         1.9G/3.6G
swapfile             /media/wd1/swap
dbdir                /media/USBdrive/ncdatabase
Nextcloud check      ok
Nextcloud version    14.0.1.1
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         yes
uptime               4min

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "$WEBSITE:443",
            "1": "192.168.1.20",
            "4": "$WEBSITE",
            "2": "$WEBSITE",
            "3": "$WEBSITE",
            "7": "nextcloudpi",
            "8": "nextcloudpi.lan"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/$WEBSITE\/",
        "dbtype": "mysql",
        "version": "14.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "maintenance": false,
        "loglevel": "2",
        "logfile": "\/media\/wd1\/ncdata\/nextcloud.log",
        "log_type": "file",
        "theme": "",
        "updater.release.channel": "stable"
    }
}

```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Fri Oct 12 06:25:05.002213 2018] [mpm_event:notice] [pid 900:tid 1996336400] AH00489: Apache/2.4.25 (Raspbian) OpenSSL/1.0.2l   configured -- resuming normal operations
[Fri Oct 12 06:25:05.002312 2018] [core:notice] [pid 900:tid 1996336400] AH00094: Command line: '/usr/sbin/apache2'
[Fri Oct 12 16:27:06.683471 2018] [mpm_event:notice] [pid 900:tid 1996336400] AH00491: caught SIGTERM, shutting down
[Fri Oct 12 16:27:31.000985 2018] [:notice] [pid 622:tid 1996037392] ModSecurity for Apache/2.9.1 (http://www.modsecurity.org/) configured.
[Fri Oct 12 16:27:31.001258 2018] [:notice] [pid 622:tid 1996037392] ModSecurity: APR compiled version="1.5.2"; loaded version="1.5.2"
[Fri Oct 12 16:27:31.001288 2018] [:notice] [pid 622:tid 1996037392] ModSecurity: PCRE compiled version="8.39 "; loaded version="8.39 2016-06-14"
[Fri Oct 12 16:27:31.001308 2018] [:notice] [pid 622:tid 1996037392] ModSecurity: LUA compiled version="Lua 5.1"
[Fri Oct 12 16:27:31.001323 2018] [:notice] [pid 622:tid 1996037392] ModSecurity: YAJL compiled version="2.1.0"
[Fri Oct 12 16:27:31.001339 2018] [:notice] [pid 622:tid 1996037392] ModSecurity: LIBXML compiled version="2.9.4"
[Fri Oct 12 16:27:31.001354 2018] [:notice] [pid 622:tid 1996037392] ModSecurity: Original server signature: Apache
[Fri Oct 12 16:27:31.001586 2018] [:notice] [pid 622:tid 1996037392] ModSecurity: StatusEngine call: "2.9.1,Apache,1.5.2/1.5.2,8.39/8.39 2016-06-14,Lua 5.1,2.9.4,e4"
[Fri Oct 12 16:27:31.419414 2018] [:notice] [pid 622:tid 1996037392] ModSecurity: StatusEngine call successfully sent. For more information visit: http://status.modsecurity.org/
[Fri Oct 12 16:27:32.021313 2018] [mpm_event:notice] [pid 968:tid 1996037392] AH00489: Apache/2.4.25 (Raspbian) OpenSSL/1.0.2l   configured -- resuming normal operations
[Fri Oct 12 16:27:32.021636 2018] [core:notice] [pid 968:tid 1996037392] AH00094: Command line: '/usr/sbin/apache2'

```
</details>

<details>
<summary>Database logs</summary>

```

2018-10-12 16:27:08 1953104688 [Note] /usr/sbin/mysqld: Shutdown complete

2018-10-12 16:28:08 1995906384 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2018-10-12 16:28:08 1995906384 [Note] InnoDB: The InnoDB memory heap is disabled
2018-10-12 16:28:08 1995906384 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-10-12 16:28:08 1995906384 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2018-10-12 16:28:08 1995906384 [Note] InnoDB: Compressed tables use zlib 1.2.8
2018-10-12 16:28:08 1995906384 [Note] InnoDB: Using Linux native AIO
2018-10-12 16:28:08 1995906384 [Note] InnoDB: Using generic crc32 instructions
2018-10-12 16:28:08 1995906384 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2018-10-12 16:28:08 1995906384 [Note] InnoDB: Completed initialization of buffer pool
2018-10-12 16:28:09 1995906384 [Note] InnoDB: Highest supported file format is Barracuda.
2018-10-12 16:28:10 1995906384 [Note] InnoDB: 128 rollback segment(s) are active.
2018-10-12 16:28:10 1995906384 [Note] InnoDB: Waiting for purge to start
2018-10-12 16:28:10 1995906384 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.35-80.0 started; log sequence number 6991582843
2018-10-12 16:28:10 1426047792 [Note] InnoDB: Dumping buffer pool(s) not yet started
2018-10-12 16:28:10 1995906384 [Note] Plugin 'FEEDBACK' is disabled.
2018-10-12 16:28:11 1995906384 [Note] Server socket created on IP: '127.0.0.1'.
2018-10-12 16:28:11 1995906384 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.1.23-MariaDB-9+deb9u1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Raspbian 9.0

```
</details>

<details>
<summary>Nextcloud logs</summary>

```

{"reqId":"bduQDTVVASfo32m79Mc5","level":1,"time":"2018-10-03T06:41:00+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"bduQDTVVASfo32m79Mc5","level":1,"time":"2018-10-03T06:41:37+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"--","version":"13.0.6.1"}
{"reqId":"bduQDTVVASfo32m79Mc5","level":1,"time":"2018-10-03T06:41:37+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"--","version":"14.0.1.1"}
{"reqId":"bduQDTVVASfo32m79Mc5","level":1,"time":"2018-10-03T06:41:37+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"--","version":"14.0.1.1"}
{"reqId":"bduQDTVVASfo32m79Mc5","level":1,"time":"2018-10-03T06:41:37+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"--","version":"14.0.1.1"}
{"reqId":"WOW1LNsJ07y2Ih4qxtAa","level":3,"time":"2018-10-03T06:42:41+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"file_get_contents(\/var\/www\/nextcloud\/apps\/news\/appinfo\/signature.json): failed to open stream: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/IntegrityCheck\/Helpers\/FileAccessHelper.php#41","userAgent":"--","version":"14.0.1.1"}
{"reqId":"hJrvca5t2pJ6CoodXt9l","level":3,"time":"2018-10-03T23:35:24+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"file_get_contents(\/var\/www\/nextcloud\/apps\/news\/appinfo\/signature.json): failed to open stream: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/IntegrityCheck\/Helpers\/FileAccessHelper.php#41","userAgent":"--","version":"14.0.1.1"}
{"reqId":"NkXxocHTVdYD3Jt5FgMb","level":3,"time":"2018-10-03T23:46:12+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"file_get_contents(\/var\/www\/nextcloud\/apps\/news\/appinfo\/signature.json): failed to open stream: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/IntegrityCheck\/Helpers\/FileAccessHelper.php#41","userAgent":"--","version":"14.0.1.1"}
{"reqId":"gytpcsMVrBF5o4yiownd","level":3,"time":"2018-10-04T00:12:34+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"hash_file(\/var\/www\/nextcloud\/.user.ini-bk): failed to open stream: Permission denied at \/var\/www\/nextcloud\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"14.0.1.1"}
{"reqId":"LS0uOjPKxgorktbrn3zh","level":3,"time":"2018-10-04T00:23:54+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"copy(\/var\/www\/nextcloud\/.user.ini): failed to open stream: Permission denied at \/var\/www\/nextcloud\/lib\/private\/IntegrityCheck\/Checker.php#194","userAgent":"--","version":"14.0.1.1"}
{"reqId":"LS0uOjPKxgorktbrn3zh","level":2,"time":"2018-10-04T00:23:54+00:00","remoteAddr":"","user":"--","app":"files","method":"","url":"--","message":"Can't write upload limit to \/media\/wd1\/ncdata\/tmp\/oc_tmp_ovcjx0-folder\/.user.ini. Please check the file permissions","userAgent":"--","version":"14.0.1.1"}
{"reqId":"LS0uOjPKxgorktbrn3zh","level":3,"time":"2018-10-04T00:24:03+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"copy(\/var\/www\/nextcloud\/.user.ini): failed to open stream: Permission denied at \/var\/www\/nextcloud\/lib\/private\/IntegrityCheck\/Checker.php#194","userAgent":"--","version":"14.0.1.1"}
{"reqId":"LS0uOjPKxgorktbrn3zh","level":2,"time":"2018-10-04T00:24:03+00:00","remoteAddr":"","user":"--","app":"files","method":"","url":"--","message":"Can't write upload limit to \/media\/wd1\/ncdata\/tmp\/oc_tmp_FTWdqM-folder\/.user.ini. Please check the file permissions","userAgent":"--","version":"14.0.1.1"}
{"reqId":"LS0uOjPKxgorktbrn3zh","level":3,"time":"2018-10-04T00:24:03+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"file_get_contents(\/media\/wd1\/ncdata\/tmp\/oc_tmp_FTWdqM-folder\/.user.ini): failed to open stream: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/IntegrityCheck\/Checker.php#208","userAgent":"--","version":"14.0.1.1"}
{"reqId":"r4wSYq9UKdce03xmVejy","level":3,"time":"2018-10-04T00:24:43+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"copy(\/var\/www\/nextcloud\/.user.ini): failed to open stream: Permission denied at \/var\/www\/nextcloud\/lib\/private\/IntegrityCheck\/Checker.php#194","userAgent":"--","version":"14.0.1.1"}
{"reqId":"r4wSYq9UKdce03xmVejy","level":2,"time":"2018-10-04T00:24:43+00:00","remoteAddr":"","user":"--","app":"files","method":"","url":"--","message":"Can't write upload limit to \/media\/wd1\/ncdata\/tmp\/oc_tmp_1oPSh2-folder\/.user.ini. Please check the file permissions","userAgent":"--","version":"14.0.1.1"}
{"reqId":"r4wSYq9UKdce03xmVejy","level":3,"time":"2018-10-04T00:24:50+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"copy(\/var\/www\/nextcloud\/.user.ini): failed to open stream: Permission denied at \/var\/www\/nextcloud\/lib\/private\/IntegrityCheck\/Checker.php#194","userAgent":"--","version":"14.0.1.1"}
{"reqId":"r4wSYq9UKdce03xmVejy","level":2,"time":"2018-10-04T00:24:50+00:00","remoteAddr":"","user":"--","app":"files","method":"","url":"--","message":"Can't write upload limit to \/media\/wd1\/ncdata\/tmp\/oc_tmp_9dSbWJ-folder\/.user.ini. Please check the file permissions","userAgent":"--","version":"14.0.1.1"}
{"reqId":"r4wSYq9UKdce03xmVejy","level":3,"time":"2018-10-04T00:24:50+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"file_get_contents(\/media\/wd1\/ncdata\/tmp\/oc_tmp_9dSbWJ-folder\/.user.ini): failed to open stream: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/IntegrityCheck\/Checker.php#208","userAgent":"--","version":"14.0.1.1"}
{"reqId":"W7fK1X8AAQEAAAPVDswAAAAA","level":3,"time":"2018-10-05T20:34:36+00:00","remoteAddr":"192.168.1.7","user":"--","app":"remote","method":"GET","url":"\/status.php","message":{"Exception":"RedisException","Message":"Redis server went away","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/Memcache\/Redis.php","line":54,"function":"get","class":"Redis","type":"->","args":["9a9901303c6f66209a03e7b9bf32718b\/core.appinfo\/var\/www\/nextcloud\/apps\/files\/appinfo\/info.xml1537857389"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/App\/InfoParser.php","line":57,"function":"get","class":"OC\\Memcache\\Redis","type":"->","args":["\/var\/www\/nextcloud\/apps\/files\/appinfo\/info.xml1537857389"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/App\/AppManager.php","line":380,"function":"parse","class":"OC\\App\\InfoParser","type":"->","args":["\/var\/www\/nextcloud\/apps\/files\/appinfo\/info.xml"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/app.php","line":551,"function":"getAppInfo","class":"OC\\App\\AppManager","type":"->","args":["files",false,null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":65,"function":"getAppInfo","class":"OC_App","type":"::","args":["files"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/app.php","line":236,"function":"buildAppNamespace","class":"OC\\AppFramework\\App","type":"::","args":["files"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/app.php","line":119,"function":"registerAutoloading","class":"OC_App","type":"::","args":["files","\/var\/www\/nextcloud\/apps\/files"]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":654,"function":"loadApps","class":"OC_App","type":"::","args":[["session"]]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/nextcloud\/status.php","line":36,"args":["\/var\/www\/nextcloud\/lib\/base.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/lib\/private\/Memcache\/Redis.php","Line":54,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"14.0.1.1"}

```
</details>

**Comment by ovpc** [comment]
rpi3B+ running berryboot latest ncp image:
sudo ncp-update devel
INFO: updating to development branch 'devel'
Downloading updates
Performing updates
Installing DDNS_spDYN
Installing nc-backup
Installing nc-restore
An unhandled exception has been thrown:
ParseError: syntax error, unexpected '5' (T_LNUMBER), expecting ')' in /var/www/nextcloud/config/config.php:10
Stack trace:
#0 /var/www/nextcloud/lib/private/Config.php(63): OC\Config->readData()
#1 /var/www/nextcloud/lib/base.php(140): OC\Config->__construct('/var/www/nextcl...')
#2 /var/www/nextcloud/lib/base.php(591): OC::initPaths()
#3 /var/www/nextcloud/lib/base.php(1068): OC::init()
#4 /var/www/nextcloud/console.php(46): require_once('/var/www/nextcl...')
#5 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#6 {main}An unhandled exception has been thrown:
ParseError: syntax error, unexpected '5' (T_LNUMBER), expecting ')' in /var/www/nextcloud/config/config.php:10
Stack trace:
#0 /var/www/nextcloud/lib/private/Config.php(63): OC\Config->readData()
#1 /var/www/nextcloud/lib/base.php(140): OC\Config->__construct('/var/www/nextcl...')
#2 /var/www/nextcloud/lib/base.php(591): OC::initPaths()
#3 /var/www/nextcloud/lib/base.php(1068): OC::init()
#4 /var/www/nextcloud/console.php(46): require_once('/var/www/nextcl...')
#5 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#6 {main}Activating nc-autoupdate-nc
automatic Nextcloud updates enabled
An unhandled exception has been thrown:
ParseError: syntax error, unexpected '5' (T_LNUMBER), expecting ')' in /var/www/nextcloud/config/config.php:10
Stack trace:
#0 /var/www/nextcloud/lib/private/Config.php(63): OC\Config->readData()
#1 /var/www/nextcloud/lib/base.php(140): OC\Config->__construct('/var/www/nextcl...')
#2 /var/www/nextcloud/lib/base.php(591): OC::initPaths()
#3 /var/www/nextcloud/lib/base.php(1068): OC::init()
#4 /var/www/nextcloud/console.php(46): require_once('/var/www/nextcl...')
#5 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#6 {main}An unhandled exception has been thrown:
ParseError: syntax error, unexpected '5' (T_LNUMBER), expecting ')' in /var/www/nextcloud/config/config.php:10
Stack trace:
#0 /var/www/nextcloud/lib/private/Config.php(63): OC\Config->readData()
#1 /var/www/nextcloud/lib/base.php(140): OC\Config->__construct('/var/www/nextcl...')
#2 /var/www/nextcloud/lib/base.php(591): OC::initPaths()
#3 /var/www/nextcloud/lib/base.php(1068): OC::init()
#4 /var/www/nextcloud/console.php(46): require_once('/var/www/nextcl...')
#5 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#6 {main}An unhandled exception has been thrown:
ParseError: syntax error, unexpected '5' (T_LNUMBER), expecting ')' in /var/www/nextcloud/config/config.php:10
Stack trace:
#0 /var/www/nextcloud/lib/private/Config.php(63): OC\Config->readData()
#1 /var/www/nextcloud/lib/base.php(140): OC\Config->__construct('/var/www/nextcl...')
#2 /var/www/nextcloud/lib/base.php(591): OC::initPaths()
#3 /var/www/nextcloud/lib/base.php(1068): OC::init()
#4 /var/www/nextcloud/console.php(46): require_once('/var/www/nextcl...')
#5 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#6 {main}NextCloudPi updated to version v0.64.0

**Comment by Iolaum** [comment]
Update fixed the issue:

```
$ sudo ncp-update devel
INFO: updating to development branch 'devel'
Downloading updates
Performing updates
Installing DDNS_spDYN
Installing nc-backup
Installing nc-restore
previewgenerator already installed
previewgenerator enabled
Activating nc-autoupdate-nc
automatic Nextcloud updates enabled
System config value trusted_domains => 7 set to string nextcloudpi
System config value trusted_domains => 8 set to string nextcloudpi.lan
NextCloudPi updated to version v0.64.0
```

**Comment by nachoparker** [comment]
thanks for the help!

**Comment by ovpc** [comment]
![ncupdate1403-screenshot at 2018-10-13 08-49-51](https://user-images.githubusercontent.com/8775469/46902395-1fab4f80-cec5-11e8-8046-c3cb2e71965a.png)
This morning found that the test rpi3b+ (NCP updated to devel 64.0 yesterday) was in process of updating NC. (as expected)
It had created a backup, moved nextcloud to nextcloud-old and created a new nextcloud folder. 
I am asuming it will run ./occ upgrade, and I do not need to take any action, except grab coffee and wait ;-)

**Comment by ovpc** [comment]
![ncupdated14 0 3-screenshot at 2018-10-13 09-12-25](https://user-images.githubusercontent.com/8775469/46902589-343d1700-cec8-11e8-934e-b68c71fdd328.png)
That seemed to have worked fine. Nice job, thank you.

**Comment by nachoparker** [comment]
Awesome, thanks guys!
