### ISSUE TITLE
Redis failing with latest nextcloudpi-armhf Docker image

### ISSUE THREAD

**Issue by fkelbert** [nextcloud/nextcloudpi#783]
Using the most recent nextcloudpi-armhf Docker image, redis fails to start within the container.  The issue seems to be a wrong redis `memory` setting:

Within the container:

`$ cat /var/log/ncp.log`:
```
[ nc-limits ]
Using 4 PHP threads
Stopping redis-server: redis-server.
Starting redis-server: 
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 1053
>>> 'maxmemory'
Bad directive or wrong number of arguments
failed
```

`$ tail /etc/redis/redis.conf`:
```
# a good idea. Most users should use the default of 10 and raise this up to
# 100 only in environments where very low latency is required.
hz 10

# When a child rewrites the AOF file, if the following option is enabled
# the file will be fsync-ed every 32 MB of data generated. This is useful
# in order to commit the file to the disk more incrementally and avoid
# big latency spikes.
aof-rewrite-incremental-fsync yes
maxmemory
```

Happy about any suggestions on how to fix this. Also, please let me know if further information is required.

**Comment by nachoparker** [comment]
Output of `cat /usr/local/etc/ncp-config.d/nc-limits.cfg`?

**Comment by fkelbert** [comment]
```
$ cat /usr/local/etc/ncp-config.d/nc-limits.cfg
cat: /usr/local/etc/ncp-config.d/nc-limits.cfg: No such file or directory
```

File `nc-limits.cfg` does not exist anywhere within the Docker container

**Comment by nachoparker** [comment]
You seem to have an outdated container. Output of `sudo ncp-report`?

**Comment by fkelbert** [comment]
Hm, the image has been updated just yesterday :-/

<details>
<summary>NextCloudPi diagnostics</summary>

```

NextCloudPi version  v1.4.1
NextCloudPi image    NextCloudPi_docker_01-18-19
distribution         Debian GNU/Linux 9 \n \l
automount            no
USB devices          sda 
datadir              /data/app/data
data in SD           yes
data filesystem      ext2/ext3
data disk usage      477G/917G
rootfs usage         477G/917G
swapfile             /var/swap
dbdir                /data/database
Nextcloud check      error
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        closed
port check 443       closed
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
uptime               3:26

```
</details>


<details>
<summary>Nextcloud configuration</summary>

```

An unhandled exception has been thrown:
RedisException: NOAUTH Authentication required. in /data/app/lib/private/Memcache/Redis.php:54
Stack trace:
#0 /data/app/lib/private/Memcache/Redis.php(54): Redis->get('857448e505b30bd...')
#1 /data/app/lib/autoloader.php(150): OC\Memcache\Redis->get('OC_User')
#2 [internal function]: OC\Autoloader->load('OC_User')
#3 /data/app/lib/private/User/Session.php(223): spl_autoload_call('OC_User')
#4 /data/app/lib/private/legacy/app.php(346): OC\User\Session->getUser()
#5 /data/app/lib/private/legacy/app.php(113): OC_App::getEnabledApps()
#6 /data/app/lib/base.php(654): OC_App::loadApps(Array)
#7 /data/app/lib/base.php(1068): OC::init()
#8 /data/app/console.php(46): require_once('/data/app/lib/b...')
#9 /data/app/occ(11): require_once('/data/app/conso...')
#10 {main}
```
</details>


<details>
<summary>HTTPd logs</summary>

```

[Wed Jan 23 10:20:11.654864 2019] [ssl:warn] [pid 76:tid 1995829248] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Wed Jan 23 10:20:12.099891 2019] [ssl:warn] [pid 77:tid 1995829248] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Wed Jan 23 10:20:13.006208 2019] [mpm_event:notice] [pid 77:tid 1995829248] AH00489: Apache/2.4.25 (Debian) OpenSSL/1.0.2q configured -- resuming normal operations
[Wed Jan 23 10:20:13.006482 2019] [core:notice] [pid 77:tid 1995829248] AH00094: Command line: '/usr/sbin/apache2'

```
</details>


<details>
<summary>Database logs</summary>

```

2019-01-23 10:20:12 1995694080 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.

2019-01-23 10:20:12 1995694080 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2019-01-23 10:20:12 1995694080 [Note] InnoDB: The InnoDB memory heap is disabled
2019-01-23 10:20:12 1995694080 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2019-01-23 10:20:12 1995694080 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2019-01-23 10:20:12 1995694080 [Note] InnoDB: Compressed tables use zlib 1.2.8
2019-01-23 10:20:12 1995694080 [Note] InnoDB: Using Linux native AIO
2019-01-23 10:20:12 1995694080 [Note] InnoDB: Using generic crc32 instructions
2019-01-23 10:20:12 1995694080 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2019-01-23 10:20:12 1995694080 [Note] InnoDB: Completed initialization of buffer pool
2019-01-23 10:20:12 1995694080 [Note] InnoDB: Highest supported file format is Barracuda.
2019-01-23 10:20:12 1995694080 [Note] InnoDB: 128 rollback segment(s) are active.
2019-01-23 10:20:12 1995694080 [Note] InnoDB: Waiting for purge to start
2019-01-23 10:20:12 1995694080 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.41-84.1 started; log sequence number 91723145
2019-01-23 10:20:12 1396699968 [Note] InnoDB: Dumping buffer pool(s) not yet started
2019-01-23 10:20:12 1995694080 [Note] Plugin 'FEEDBACK' is disabled.
2019-01-23 10:20:12 1995694080 [Note] Server socket created on IP: '127.0.0.1'.
2019-01-23 10:20:12 1995694080 [Note] mysqld: ready for connections.
Version: '10.1.37-MariaDB-0+deb9u1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Debian 9.6

```
</details>

**Comment by nachoparker** [comment]
that's weird, try moving `/data/ncp` to `/data/ncp.copy` and restarting the container

**Comment by necopinus** [comment]
Something like this totally happened to me the first time I pulled a new docker container. I had to log into the container using `docker exec -it nextcloudpi /bin/bash`, manually run `ncp-update` _twice_ (the first time took an error at the very end), and then restart the container. YMMV though (and it's possible my memory's off... I didn't take notes about this).

**Comment by nachoparker** [comment]
@necopinus do you mean pull the container while you already had a running instance?

**Comment by fkelbert** [comment]
Thanks for all your help. Tbh, I had switched to running Nextcloud natively just before you @nachoparker posted the proposal to create a brand new data directory. I can try and see if the solution works once I find some time.
