### ISSUE TITLE
Apache wont start after ncp-update

### ISSUE THREAD

**Issue by fosBHY** [nextcloud/nextcloudpi#791]
Hello.
I installed nextcloudpi via the install skript yesterday evening.

At first it didn't work because I had nginx running, after stopping nginx and starting apache2 it worked. 
I went through the configuration in the ncp-webUI and everything went fine. At the end I noticed that ncp version in top left corner said 0.0.0 - so I clicked on update ncp. The web-UI gave some output as usual, saying that it now updated.
After that the services were not reachable.

Apache stopped.

**APACHE ERRORS**

```
sudo systemctl status apache2.service

● apache2.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-01-29 10:17:14 CET; 8min ago
  Process: 18433 ExecStart=/usr/sbin/apachectl start (code=exited, status=1/FAILURE)

systemd[1]: Starting The Apache HTTP Server...
apachectl[18433]: AH00526: Syntax error on line 1 of /etc/apache2/mods-enabled/authnz_external.load:
apachectl[18433]: Invalid command 'L\xefa$Module', perhaps misspelled or defined by a module not included in the server configuration
apachectl[18433]: Action 'start' failed.
apachectl[18433]: The Apache error log may have more information.
systemd[1]: apache2.service: Control process exited, code=exited status=1
systemd[1]: Failed to start The Apache HTTP Server.
systemd[1]: apache2.service: Unit entered failed state.
systemd[1]: apache2.service: Failed with result 'exit-code'.
```

**/etc/apache2/mods-enabled/authnz_external.load is saying**
`Lïa$Module authnz_external_module /usr/lib/apakhe2/modules/mod_authnz_ezternal.so`

**are these --three-- typos of ncp?**
I corrected to 
`LoadModule authnz_external_module /usr/lib/apache2/modules/mod_authnz_external.so`
 
Now apache throws me a apachectl[5618]: Segmentation fault

I will look further into it but I have very limited knowledge of this computermagic. 

I don't want to start troubleshooting apache2 here, but this was surely caused by ncp or the way the script set things up.
 I would also like to have it fixed (and help with it) as I want to start using nextcloud, preferably with ncp and without completely reinstalling everything.

**NCP-REPORT** as it was asked for

<details>
<summary>NextCloudPi diagnostics</summary>

```

NextCloudPi version  v1.4.11
distribution         Raspbian GNU/Linux 9 \n \l
automount            no
USB devices          sda 
datadir              /mnt/DATEN/nextcloud/data
data in SD           no
data filesystem      btrfs
data disk usage      9.7G/59G
rootfs usage         5.3G/15G
swapfile             /var/swap
dbdir                /mnt/DATEN/nextcloud/database
Nextcloud check      error
HTTPD service        down
PHP service          up
MariaDB service      down
Redis service        up
Postfix service      up
internet check       ok
port check 80        closed
port check 443       closed
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
uptime               9:52

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /var/www/nextcloud/lib/private/DB/Connection.php:64
Stack trace:
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/nextcloud/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/nextcloud/lib/private/DB/ConnectionFactory.php(158): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /var/www/nextcloud/lib/private/Server.php(641): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OCP\\IDBConnecti...')
#10 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IDBConnecti...')
#11 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OCP\\IDBConnecti...')
#12 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#13 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('DatabaseConnect...')
#14 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#15 /var/www/nextcloud/lib/private/Server.php(1552): OC\ServerContainer->query('DatabaseConnect...')
#16 /var/www/nextcloud/lib/private/Server.php(360): OC\Server->getDatabaseConnection()
#17 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#18 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OC\\Authenticati...')
#19 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#20 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(68): OC\ServerContainer->query('OC\\Authenticati...')
#21 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(98): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#22 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(119): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Authenticati...')
#23 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#24 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(68): OC\ServerContainer->query('OC\\Authenticati...')
#25 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(98): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#26 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(119): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Authenticati...')
#27 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#28 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OC\\Authenticati...')
#29 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#30 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OC\\Authenticati...')
#31 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#32 /var/www/nextcloud/lib/private/Server.php(372): OC\ServerContainer->query('OC\\Authenticati...')
#33 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#34 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OC\\User\\Session')
#35 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\User\\Session')
#36 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OC\\User\\Session')
#37 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#38 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('UserSession')
#39 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('UserSession')
#40 /var/www/nextcloud/lib/private/Server.php(1435): OC\ServerContainer->query('UserSession')
#41 /var/www/nextcloud/lib/private/Server.php(1035): OC\Server->getSession()
#42 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#43 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OC\\Security\\CSR...')
#44 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Security\\CSR...')
#45 /var/www/nextcloud/lib/private/Server.php(1031): OC\ServerContainer->query('OC\\Security\\CSR...')
#46 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#47 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('CsrfTokenManage...')
#48 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('CsrfTokenManage...')
#49 /var/www/nextcloud/lib/private/Server.php(1898): OC\ServerContainer->query('CsrfTokenManage...')
#50 /var/www/nextcloud/lib/private/Server.php(827): OC\Server->getCsrfTokenManager()
#51 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#52 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OCP\\IRequest')
#53 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IRequest')
#54 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OCP\\IRequest')
#55 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#56 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('Request')
#57 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('Request')
#58 /var/www/nextcloud/lib/private/Server.php(1302): OC\ServerContainer->query('Request')
#59 /var/www/nextcloud/lib/private/Server.php(463): OC\Server->getRequest()
#60 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#61 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OCP\\L10N\\IFacto...')
#62 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\L10N\\IFacto...')
#63 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OCP\\L10N\\IFacto...')
#64 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#65 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('L10NFactory')
#66 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('L10NFactory')
#67 /var/www/nextcloud/lib/private/Server.php(1488): OC\ServerContainer->query('L10NFactory')
#68 /var/www/nextcloud/lib/private/Server.php(1499): OC\Server->getL10NFactory()
#69 /var/www/nextcloud/lib/base.php(234): OC\Server->getL10N('lib')
#70 /var/www/nextcloud/lib/base.php(659): OC::checkConfig()
#71 /var/www/nextcloud/lib/base.php(1068): OC::init()
#72 /var/www/nextcloud/console.php(46): require_once('/var/www/nextcl...')
#73 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#74 {main}
```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Tue Jan 29 00:10:09.191919 2019] [authz_host:error] [pid 8488:tid 1681568816] [client 192.168.125.153:60248] AH01753: access check of 'localhost' to /js/minified.js failed, reason: unable to get the remote host name
[Tue Jan 29 00:10:09.192562 2019] [authz_host:error] [pid 8488:tid 1706734640] [client 192.168.125.153:60248] AH01753: access check of 'localhost' to /img/ncp-logo.svg failed, reason: unable to get the remote host name
[Tue Jan 29 00:10:09.192546 2019] [authz_host:error] [pid 8488:tid 1748677680] [client 192.168.125.153:60248] AH01753: access check of 'localhost' to /js/ncp.js failed, reason: unable to get the remote host name
[Tue Jan 29 00:10:09.192983 2019] [authz_host:error] [pid 8488:tid 1757066288] [client 192.168.125.153:60248] AH01753: access check of 'localhost' to /css/ncp.css failed, reason: unable to get the remote host name
[Tue Jan 29 00:10:09.193679 2019] [authz_host:error] [pid 8488:tid 1689957424] [client 192.168.125.153:60248] AH01753: access check of 'localhost' to /img/loading-small.gif failed, reason: unable to get the remote host name
[Tue Jan 29 00:14:31.109951 2019] [ssl:warn] [pid 14401:tid 1991847936] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Jan 29 00:14:31.110243 2019] [ssl:error] [pid 14401:tid 1991847936] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=pi / issuer: CN=pi / serial: C49F2100662C57F6 / notbefore: Jan 28 19:40:58 2019 GMT / notafter: Jan 25 19:40:58 2029 GMT]
[Tue Jan 29 00:14:31.110268 2019] [ssl:error] [pid 14401:tid 1991847936] AH02604: Unable to configure certificate localhost:4443:0 for stapling
[Tue Jan 29 00:14:31.112943 2019] [unique_id:alert] [pid 14401:tid 1991847936] (EAI 2)Name or service not known: AH01564: unable to find IPv4 address of "pi"
AH00016: Configuration Failed
[Tue Jan 29 00:18:50.802502 2019] [ssl:warn] [pid 14676:tid 1991979008] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Jan 29 00:18:50.802758 2019] [ssl:error] [pid 14676:tid 1991979008] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=pi / issuer: CN=pi / serial: C49F2100662C57F6 / notbefore: Jan 28 19:40:58 2019 GMT / notafter: Jan 25 19:40:58 2029 GMT]
[Tue Jan 29 00:18:50.802778 2019] [ssl:error] [pid 14676:tid 1991979008] AH02604: Unable to configure certificate localhost:4443:0 for stapling
[Tue Jan 29 00:18:50.805789 2019] [unique_id:alert] [pid 14676:tid 1991979008] (EAI 2)Name or service not known: AH01564: unable to find IPv4 address of "pi"
AH00016: Configuration Failed
[Tue Jan 29 00:20:24.239280 2019] [ssl:warn] [pid 14869:tid 1992839168] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Jan 29 00:20:24.239527 2019] [ssl:error] [pid 14869:tid 1992839168] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=pi / issuer: CN=pi / serial: C49F2100662C57F6 / notbefore: Jan 28 19:40:58 2019 GMT / notafter: Jan 25 19:40:58 2029 GMT]
[Tue Jan 29 00:20:24.239547 2019] [ssl:error] [pid 14869:tid 1992839168] AH02604: Unable to configure certificate localhost:4443:0 for stapling
[Tue Jan 29 00:20:24.242472 2019] [unique_id:alert] [pid 14869:tid 1992839168] (EAI 2)Name or service not known: AH01564: unable to find IPv4 address of "pi"
AH00016: Configuration Failed

```
</details>

<details>
<summary>Database logs</summary>

```

2019-01-28 23:32:10 1989165056 [Note] InnoDB: Using generic crc32 instructions
2019-01-28 23:32:10 1989165056 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2019-01-28 23:32:10 1989165056 [Note] InnoDB: Completed initialization of buffer pool
2019-01-28 23:32:10 1989165056 [Note] InnoDB: Highest supported file format is Barracuda.
2019-01-28 23:32:10 1989165056 [Note] InnoDB: 128 rollback segment(s) are active.
2019-01-28 23:32:10 1989165056 [Note] InnoDB: Waiting for purge to start
2019-01-28 23:32:10 1989165056 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.41-84.1 started; log sequence number 4301164
2019-01-28 23:32:10 1409282880 [Note] InnoDB: Dumping buffer pool(s) not yet started
2019-01-28 23:32:10 1989165056 [Note] Plugin 'FEEDBACK' is disabled.
2019-01-28 23:32:10 1989165056 [Note] Server socket created on IP: '127.0.0.1'.
2019-01-28 23:32:10 1989165056 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.1.37-MariaDB-0+deb9u1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Raspbian 9.0
2019-01-29  0:25:22 1639437120 [Note] /usr/sbin/mysqld: Normal shutdown
2019-01-29  0:25:23 1639437120 [Note] Event Scheduler: Purging the queue. 0 events
2019-01-29  0:25:24 1463808832 [Note] InnoDB: FTS optimize thread exiting.
2019-01-29  0:25:24 1639437120 [Note] InnoDB: Starting shutdown...
2019-01-29  0:25:25 1639437120 [Note] InnoDB: Waiting for page_cleaner to finish flushing of buffer pool
2019-01-29  0:25:27 1639437120 [Note] InnoDB: Shutdown completed; log sequence number 4379520
2019-01-29  0:25:27 1639437120 [Note] /usr/sbin/mysqld: Shutdown complete


```
</details>

<details>
<summary>Nextcloud logs</summary>

```

{"reqId":"nvbuAfPT7EUjUCYrYU7b","level":3,"time":"2019-01-28T20:00:09+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":660,"function":"checkInstalled","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/nextcloud\/cron.php","line":41,"args":["\/var\/www\/nextcloud\/lib\/base.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/lib\/base.php","Line":277,"CustomMessage":"--"},"userAgent":"--","version":""}
{"reqId":"g26OTHLTgAA8c0UDRaHk","level":3,"time":"2019-01-28T20:16:00+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":660,"function":"checkInstalled","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/nextcloud\/cron.php","line":41,"args":["\/var\/www\/nextcloud\/lib\/base.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/lib\/base.php","Line":277,"CustomMessage":"--"},"userAgent":"--","version":""}
{"reqId":"cLA28swWtfpuUy3rTYoE","level":3,"time":"2019-01-28T20:30:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":660,"function":"checkInstalled","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/nextcloud\/cron.php","line":41,"args":["\/var\/www\/nextcloud\/lib\/base.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/lib\/base.php","Line":277,"CustomMessage":"--"},"userAgent":"--","version":"15.0.2.0"}

```
</details>

**Comment by fosBHY** [comment]
Might be something with the automatic setup of https ?

this was when it stopped working:

```
[Tue Jan 29 00:10:06.678782 2019] [mpm_event:notice] [pid 3725:tid 1992093696] AH00493: SIGUSR1 received.  Doing graceful restart                                               │
[Tue Jan 29 00:10:06.739477 2019] [ssl:warn] [pid 3725:tid 1992093696] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name        │
[Tue Jan 29 00:10:06.739809 2019] [ssl:error] [pid 3725:tid 1992093696] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=pi / issuer: CN=pi / se│
[Tue Jan 29 00:10:06.739846 2019] [ssl:error] [pid 3725:tid 1992093696] AH02604: Unable to configure certificate localhost:4443:0 for stapling                                  │
[Tue Jan 29 00:10:06.746523 2019] [unique_id:alert] [pid 3725:tid 1992093696] (EAI 2)Name or service not known: AH01564: unable to find IPv4 address of "pi"                    │
[Tue Jan 29 00:10:06.747204 2019] [:emerg] [pid 3725:tid 1992093696] AH00020: Configuration Failed, exiting  
```

**Comment by ovpc** [comment]
Please use the [forum](https://help.nextcloud.com/tags/ncp) to ask questions and get help.  Thank you for including output of **ncp-report** and **cat /var/log/ncp.log** thru pastbin or similar and post link on forum, if you are looking for further assistance. (Github is for Devs, bugs and wiki discussions only)
For simple yes/no or short questions, and view/take part in discussions, you can also join the NCP's [telegram](https://t.me/NextCloudPi) group.

> Segmentation fault
Can be indication of corrupt sd card, or bad power source/cable

Suggest look at output of **dmesg** for more clues and paste output to https://lmddgtfy.net/ or forum

**Comment by fosBHY** [comment]
this is not a question, it is a bug, isn't it? At least to me it looks like the install script and/or ncp is screwing things up.

**Comment by nachoparker** [comment]
You seem to have some corrupted files. NCP doesn't touch those files at all. You would probably get more help in the forums, but I would consider replacing your SD card first.

Thanks for reporting
