### ISSUE TITLE
Doctrine\DBAL\DBALException: Failed to connect to the database

### ISSUE THREAD

**Issue by piexad** [nextcloud/nextcloudpi#812]
Hello, 

Three days ago I made some updates on my RPi and I remember that there was like 70 updates available (even if I update my RPi really often). 
Since this time, my NCP is down. When I try to connect to it I get a white page and HTTP 500 error with DAVx5 and NEWS app. 

The issue seems to be this : 
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1698] Access denied for user 'ncadmin'@'localhost' in /var/www/nextcloud/lib/private/DB/Connection.php:64

Unfortunately I really don't understand what it means...

Thank you for your help !

**System information**

<details>
<summary>NextCloudPi diagnostics</summary>

```

NextCloudPi version  v1.7.0
NextCloudPi image    NextCloudPi_02-06-18
distribution         Raspbian GNU/Linux 9 \n \l
automount            yes
USB devices          sda
datadir              /media/USBdrive/ncdata
data in SD           no
data filesystem      btrfs
data disk usage      304G/932G
rootfs usage         3.8G/30G
swapfile             /var/swap
dbdir                /media/USBdrive/ncdatabase
Nextcloud check      error
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            enxb827eb5031b9
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         yes
uptime               25min

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1698] Access denied for user 'ncadmin'@'localhost' in /var/www/nextcloud/lib/private/DB/Connection.php:64
Stack trace:
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/nextcloud/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/nextcloud/lib/private/DB/ConnectionFactory.php(158): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /var/www/nextcloud/lib/private/Server.php(641): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OCP\\IDBConnecti...')
#10 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IDBConnecti...')
#11 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OCP\\IDBConnecti...')
#12 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#13 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('DatabaseConnect...')
#14 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#15 /var/www/nextcloud/lib/private/Server.php(1552): OC\ServerContainer->query('DatabaseConnect...')
#16 /var/www/nextcloud/lib/private/Server.php(360): OC\Server->getDatabaseConnection()
#17 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#18 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OC\\Authenticati...')
#19 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#20 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(68): OC\ServerContainer->query('OC\\Authenticati...')
#21 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(98): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#22 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(119): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Authenticati...')
#23 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#24 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(68): OC\ServerContainer->query('OC\\Authenticati...')
#25 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(98): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#26 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(119): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Authenticati...')
#27 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#28 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OC\\Authenticati...')
#29 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#30 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OC\\Authenticati...')
#31 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#32 /var/www/nextcloud/lib/private/Server.php(372): OC\ServerContainer->query('OC\\Authenticati...')
#33 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#34 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OC\\User\\Session')
#35 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\User\\Session')
#36 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OC\\User\\Session')
#37 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#38 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('UserSession')
#39 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('UserSession')
#40 /var/www/nextcloud/lib/private/Server.php(1428): OC\ServerContainer->query('UserSession')
#41 /var/www/nextcloud/lib/private/Server.php(694): OC\Server->getUserSession()
#42 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#43 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OC\\App\\AppManag...')
#44 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\App\\AppManag...')
#45 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OC\\App\\AppManag...')
#46 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#47 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('AppManager')
#48 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#49 /var/www/nextcloud/lib/private/Server.php(1723): OC\ServerContainer->query('AppManager')
#50 /var/www/nextcloud/lib/private/legacy/app.php(342): OC\Server->getAppManager()
#51 /var/www/nextcloud/lib/private/legacy/app.php(113): OC_App::getEnabledApps()
#52 /var/www/nextcloud/lib/base.php(654): OC_App::loadApps(Array)
#53 /var/www/nextcloud/lib/base.php(1068): OC::init()
#54 /var/www/nextcloud/console.php(46): require_once('/var/www/nextcl...')
#55 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#56 {main}
```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Fri Feb 22 18:36:38.303012 2019] [authz_host:error] [pid 3099:tid 1717400608] [client 192.168.1.13:52540] AH01753: access check of 'localhost' to /img/loading-small.gif failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.448875 2019] [authz_host:error] [pid 3100:tid 1708999712] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /js/ncp.js failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.448982 2019] [authz_host:error] [pid 3100:tid 1683797024] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /css/ncp.css failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.449364 2019] [authz_host:error] [pid 3100:tid 1692197920] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /js/minified.js failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.507342 2019] [authz_host:error] [pid 3100:tid 1683797024] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /img/loading-small.gif failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.507342 2019] [authz_host:error] [pid 3100:tid 1708999712] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /img/defaults.svg failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.507342 2019] [authz_host:error] [pid 3100:tid 1692197920] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /img/toggle.svg failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.509554 2019] [authz_host:error] [pid 3100:tid 1708999712] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /img/poweroff.svg failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.512010 2019] [authz_host:error] [pid 3100:tid 1708999712] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /img/reboot.svg failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.678628 2019] [authz_host:error] [pid 3100:tid 1708999712] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /img/ncp-logo.svg failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.691773 2019] [authz_host:error] [pid 3100:tid 1692197920] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /img/dashboard.svg failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.691773 2019] [authz_host:error] [pid 3100:tid 1708999712] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /img/search.svg failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.691820 2019] [authz_host:error] [pid 3100:tid 1700598816] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /img/settings-white.svg failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.693379 2019] [authz_host:error] [pid 3100:tid 1692197920] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /img/info-white.svg failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.693640 2019] [authz_host:error] [pid 3100:tid 1717400608] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /img/wizard.svg failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.694315 2019] [authz_host:error] [pid 3100:tid 1683797024] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /img/nc-button.svg failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.694785 2019] [authz_host:error] [pid 3100:tid 1725801504] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /img/files.svg failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.822959 2019] [authz_host:error] [pid 3100:tid 1725801504] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /ncp-output.php failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:38.845317 2019] [authz_host:error] [pid 3100:tid 1683797024] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Fri Feb 22 18:36:43.038911 2019] [authz_host:error] [pid 3100:tid 1683797024] [client 192.168.1.13:52542] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name

```
</details>

<details>
<summary>Database logs</summary>

```

2019-02-22 18:30:36 1995881888 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.

2019-02-22 18:30:36 1995881888 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2019-02-22 18:30:36 1995881888 [Note] InnoDB: The InnoDB memory heap is disabled
2019-02-22 18:30:36 1995881888 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2019-02-22 18:30:36 1995881888 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2019-02-22 18:30:36 1995881888 [Note] InnoDB: Compressed tables use zlib 1.2.8
2019-02-22 18:30:36 1995881888 [Note] InnoDB: Using Linux native AIO
2019-02-22 18:30:36 1995881888 [Note] InnoDB: Using generic crc32 instructions
2019-02-22 18:30:36 1995881888 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2019-02-22 18:30:36 1995881888 [Note] InnoDB: Completed initialization of buffer pool
2019-02-22 18:30:36 1995881888 [Note] InnoDB: Highest supported file format is Barracuda.
2019-02-22 18:30:36 1995881888 [Note] InnoDB: 128 rollback segment(s) are active.
2019-02-22 18:30:36 1995881888 [Note] InnoDB: Waiting for purge to start
2019-02-22 18:30:36 1995881888 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.41-84.1 started; log sequence number 1616847
2019-02-22 18:30:36 1384117040 [Note] InnoDB: Dumping buffer pool(s) not yet started
2019-02-22 18:30:36 1995881888 [Note] Plugin 'FEEDBACK' is disabled.
2019-02-22 18:30:36 1995881888 [Note] Server socket created on IP: '127.0.0.1'.
2019-02-22 18:30:36 1995881888 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.1.37-MariaDB-0+deb9u1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Raspbian 9.0

```
</details>

<details>
<summary>Nextcloud logs</summary>

```

{"reqId":"XGugiX8AAQEAAD7U8i4AAAUF","level":0,"time":"2019-02-19T06:22:02+00:00","remoteAddr":"192.168.1.1","user":"--","app":"core","method":"GET","url":"\/index.php\/apps\/news\/api\/v1-2\/user","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/css-variables.scss, ignoring","userAgent":"okhttp\/3.8.0","version":"15.0.2.0"}
{"reqId":"XGugiX8AAQEAAD7U8i4AAAUF","level":0,"time":"2019-02-19T06:22:02+00:00","remoteAddr":"192.168.1.1","user":"--","app":"core","method":"GET","url":"\/index.php\/apps\/news\/api\/v1-2\/user","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"okhttp\/3.8.0","version":"15.0.2.0"}
{"reqId":"XGugiX8AAQEAAD7U8i4AAAUF","level":0,"time":"2019-02-19T06:22:02+00:00","remoteAddr":"192.168.1.1","user":"--","app":"core","method":"GET","url":"\/index.php\/apps\/news\/api\/v1-2\/user","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/search\/css\/results.scss, ignoring","userAgent":"okhttp\/3.8.0","version":"15.0.2.0"}
{"reqId":"XGugiX8AAQEAAD7V@KYAAEAE","level":0,"time":"2019-02-19T06:22:03+00:00","remoteAddr":"192.168.1.1","user":"--","app":"core","method":"GET","url":"\/index.php\/apps\/news\/api\/v1-2\/feeds","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"okhttp\/3.8.0","version":"15.0.2.0"}
{"reqId":"XGugiX8AAQEAAD7V@KYAAEAE","level":0,"time":"2019-02-19T06:22:03+00:00","remoteAddr":"192.168.1.1","user":"--","app":"core","method":"GET","url":"\/index.php\/apps\/news\/api\/v1-2\/feeds","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/server.scss, ignoring","userAgent":"okhttp\/3.8.0","version":"15.0.2.0"}
{"reqId":"XGugiX8AAQEAAD7V@KYAAEAE","level":0,"time":"2019-02-19T06:22:03+00:00","remoteAddr":"192.168.1.1","user":"--","app":"core","method":"GET","url":"\/index.php\/apps\/news\/api\/v1-2\/feeds","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/css-variables.scss, ignoring","userAgent":"okhttp\/3.8.0","version":"15.0.2.0"}
{"reqId":"XGugiX8AAQEAAD7V@KYAAEAE","level":0,"time":"2019-02-19T06:22:03+00:00","remoteAddr":"192.168.1.1","user":"--","app":"core","method":"GET","url":"\/index.php\/apps\/news\/api\/v1-2\/feeds","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"okhttp\/3.8.0","version":"15.0.2.0"}
{"reqId":"XGugiX8AAQEAAD7V@KYAAEAE","level":0,"time":"2019-02-19T06:22:03+00:00","remoteAddr":"192.168.1.1","user":"--","app":"core","method":"GET","url":"\/index.php\/apps\/news\/api\/v1-2\/feeds","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/search\/css\/results.scss, ignoring","userAgent":"okhttp\/3.8.0","version":"15.0.2.0"}
{"reqId":"XGugcX8AAQEAAD7U8iwAAA0g","level":1,"time":"2019-02-19T06:22:09+00:00","remoteAddr":"192.168.1.1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=DCHkmfw3qBlF8H0UDdcvdFmyO4%2FhK50tJCZvKdlfyGM%3D%3ASWzS3K4Hw3MdnS1QYPwaOTzodLetSs9JXnAHHLMUnSE%3D","message":"\\OC\\Repair::info: Repair info: JS cache cleared","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.2.0"}
{"reqId":"XGugcX8AAQEAAD7U8iwAAA0g","level":1,"time":"2019-02-19T06:22:09+00:00","remoteAddr":"192.168.1.1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=DCHkmfw3qBlF8H0UDdcvdFmyO4%2FhK50tJCZvKdlfyGM%3D%3ASWzS3K4Hw3MdnS1QYPwaOTzodLetSs9JXnAHHLMUnSE%3D","message":"\\OC\\Repair::step: Repair step: Clear every generated avatar on major updates","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.2.0"}
{"reqId":"XGugcX8AAQEAAD7U8iwAAA0g","level":1,"time":"2019-02-19T06:22:09+00:00","remoteAddr":"192.168.1.1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=DCHkmfw3qBlF8H0UDdcvdFmyO4%2FhK50tJCZvKdlfyGM%3D%3ASWzS3K4Hw3MdnS1QYPwaOTzodLetSs9JXnAHHLMUnSE%3D","message":"\\OC\\Repair::step: Repair step: Add preview background cleanup job","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.2.0"}
{"reqId":"XGugcX8AAQEAAD7U8iwAAA0g","level":1,"time":"2019-02-19T06:22:09+00:00","remoteAddr":"192.168.1.1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=DCHkmfw3qBlF8H0UDdcvdFmyO4%2FhK50tJCZvKdlfyGM%3D%3ASWzS3K4Hw3MdnS1QYPwaOTzodLetSs9JXnAHHLMUnSE%3D","message":"\\OC\\Repair::step: Repair step: Queue a one-time job to cleanup old backups of the updater","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.2.0"}
{"reqId":"XGugcX8AAQEAAD7U8iwAAA0g","level":1,"time":"2019-02-19T06:22:09+00:00","remoteAddr":"192.168.1.1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=DCHkmfw3qBlF8H0UDdcvdFmyO4%2FhK50tJCZvKdlfyGM%3D%3ASWzS3K4Hw3MdnS1QYPwaOTzodLetSs9JXnAHHLMUnSE%3D","message":"\\OC\\Repair::step: Repair step: Repair pending cron jobs","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.2.0"}
{"reqId":"XGugcX8AAQEAAD7U8iwAAA0g","level":1,"time":"2019-02-19T06:22:09+00:00","remoteAddr":"192.168.1.1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=DCHkmfw3qBlF8H0UDdcvdFmyO4%2FhK50tJCZvKdlfyGM%3D%3ASWzS3K4Hw3MdnS1QYPwaOTzodLetSs9JXnAHHLMUnSE%3D","message":"\\OC\\Repair::info: Repair info: No need to repair pending cron jobs.","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.2.0"}
{"reqId":"XGugcX8AAQEAAD7U8iwAAA0g","level":1,"time":"2019-02-19T06:22:09+00:00","remoteAddr":"192.168.1.1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=DCHkmfw3qBlF8H0UDdcvdFmyO4%2FhK50tJCZvKdlfyGM%3D%3ASWzS3K4Hw3MdnS1QYPwaOTzodLetSs9JXnAHHLMUnSE%3D","message":"\\OC\\Repair::step: Repair step: Extract the vcard uid and store it in the db","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.2.0"}
{"reqId":"XGugcX8AAQEAAD7U8iwAAA0g","level":1,"time":"2019-02-19T06:22:09+00:00","remoteAddr":"192.168.1.1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=DCHkmfw3qBlF8H0UDdcvdFmyO4%2FhK50tJCZvKdlfyGM%3D%3ASWzS3K4Hw3MdnS1QYPwaOTzodLetSs9JXnAHHLMUnSE%3D","message":"\\OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.2.0"}
{"reqId":"XGugcX8AAQEAAD7U8iwAAA0g","level":1,"time":"2019-02-19T06:22:39+00:00","remoteAddr":"192.168.1.1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=DCHkmfw3qBlF8H0UDdcvdFmyO4%2FhK50tJCZvKdlfyGM%3D%3ASWzS3K4Hw3MdnS1QYPwaOTzodLetSs9JXnAHHLMUnSE%3D","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.2.0"}
{"reqId":"XGugcX8AAQEAAD7U8iwAAA0g","level":1,"time":"2019-02-19T06:22:39+00:00","remoteAddr":"192.168.1.1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=DCHkmfw3qBlF8H0UDdcvdFmyO4%2FhK50tJCZvKdlfyGM%3D%3ASWzS3K4Hw3MdnS1QYPwaOTzodLetSs9JXnAHHLMUnSE%3D","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.4.0"}
{"reqId":"XGugcX8AAQEAAD7U8iwAAA0g","level":1,"time":"2019-02-19T06:22:39+00:00","remoteAddr":"192.168.1.1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=DCHkmfw3qBlF8H0UDdcvdFmyO4%2FhK50tJCZvKdlfyGM%3D%3ASWzS3K4Hw3MdnS1QYPwaOTzodLetSs9JXnAHHLMUnSE%3D","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.4.0"}
{"reqId":"XGugcX8AAQEAAD7U8iwAAA0g","level":1,"time":"2019-02-19T06:22:39+00:00","remoteAddr":"192.168.1.1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=DCHkmfw3qBlF8H0UDdcvdFmyO4%2FhK50tJCZvKdlfyGM%3D%3ASWzS3K4Hw3MdnS1QYPwaOTzodLetSs9JXnAHHLMUnSE%3D","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.4.0"}

```
</details>

**Comment by shadowstreik** [comment]
A link for support is available on the NextCloudPi Mastodon page...

https://mastodon.social/@NextCloudPi

Thank you.

**Comment by Medvosteri** [comment]
You mean going to mastodon, just to click on a link to go to the nextcloud/ncp [Forum](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm)?
