### ISSUE TITLE
update to 16.0.3 fails with RedisException

### ISSUE THREAD

**Issue by violoncelloCH** [nextcloud/nextcloudpi#956]
#### Steps to reproduce
1. run ncp-config as sudo
2. select update > ncp-update-nextcloud
3. let the update running, but after the backup has been generated, run in the error below

#### Description
Maybe this is just not yet supported, but when trying to update to 16.0.3 via `ncp-update-nextcloud` I get this:

```
backup /var/www//nextcloud-bkp_20190721_1563738083.tar.gz generated
An unhandled exception has been thrown:
RedisException: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error. in /var/www/nextcloud/lib/private/Memcache/Redis.php:64
Stack trace:
#0 /var/www/nextcloud/lib/private/Memcache/Redis.php(64): Redis->setex('860ecd96bcb3550...', 60, '["\\/var\\/www\\/n...')
#1 /var/www/nextcloud/lib/autoloader.php(168): OC\Memcache\Redis->set('OC_User', Array, 60)
#2 [internal function]: OC\Autoloader->load('OC_User')
#3 /var/www/nextcloud/lib/private/User/Session.php(223): spl_autoload_call('OC_User')
#4 /var/www/nextcloud/lib/private/L10N/Factory.php(168): OC\User\Session->getUser()
#5 /var/www/nextcloud/lib/private/L10N/Factory.php(127): OC\L10N\Factory->findLanguage('lib')
#6 /var/www/nextcloud/lib/private/Server.php(1507): OC\L10N\Factory->get('lib', NULL)
#7 /var/www/nextcloud/lib/base.php(234): OC\Server->getL10N('lib')
#8 /var/www/nextcloud/lib/base.php(645): OC::checkConfig()
#9 /var/www/nextcloud/lib/base.php(1056): OC::init()
#10 /var/www/nextcloud/console.php(46): require_once('/var/www/nextcl...')
#11 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#12 {main}Abort...
An unhandled exception has been thrown:
RedisException: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error. in /var/www/nextcloud/lib/private/Memcache/Redis.php:64
Stack trace:
#0 /var/www/nextcloud/lib/private/Memcache/Redis.php(64): Redis->setex('860ecd96bcb3550...', 60, '["\\/var\\/www\\/n...')
#1 /var/www/nextcloud/lib/autoloader.php(168): OC\Memcache\Redis->set('OC_User', Array, 60)
#2 [internal function]: OC\Autoloader->load('OC_User')
#3 /var/www/nextcloud/lib/private/User/Session.php(223): spl_autoload_call('OC_User')
#4 /var/www/nextcloud/lib/private/L10N/Factory.php(168): OC\User\Session->getUser()
#5 /var/www/nextcloud/lib/private/L10N/Factory.php(127): OC\L10N\Factory->findLanguage('lib')
#6 /var/www/nextcloud/lib/private/Server.php(1507): OC\L10N\Factory->get('lib', NULL)
#7 /var/www/nextcloud/lib/base.php(234): OC\Server->getL10N('lib')
#8 /var/www/nextcloud/lib/base.php(645): OC::checkConfig()
#9 /var/www/nextcloud/lib/base.php(1056): OC::init()
#10 /var/www/nextcloud/console.php(46): require_once('/var/www/nextcl...')
#11 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#12 {main}Error backing up
Clean up...
Done. Press any key...
```

Also, it cleaned up the backup automatically, but did keep the NC maintenance mode on. Turning it off manually gives me back the working 16.0.2 setup luckily :)

**System information**

<details>
<summary>NextCloudPi diagnostics</summary>

```

grep: /etc/mysql/mariadb.conf.d/90-ncp.cnf: No such file or directory
NextCloudPi version  v1.16.0
distribution         Debian GNU/Linux 10 \n \l
automount            no
USB devices          none
datadir              /var/www/nextcloud/data
data in SD           yes
data filesystem      ext2/ext3
data disk usage      386G/461G
rootfs usage         386G/461G
swapfile             /var/swap
dbdir                 (doesn't exist)
Nextcloud check      ok
Nextcloud version    16.0.2.1
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            enx1491823c17e8
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
uptime               32days

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "***REMOVED SENSITIVE VALUE***",
            "1": "***REMOVED SENSITIVE VALUE***",
            "2": "localhost",
            "3": "***REMOVED SENSITIVE VALUE***",
            "5": "***REMOVED SENSITIVE VALUE***",
            "4": "***REMOVED SENSITIVE VALUE***",
            "11": "***REMOVED SENSITIVE VALUE***"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "maintenance": false,
        "loglevel": "2",
        "theme": "",
        "log_type": "file",
        "htaccess.RewriteBase": "\/",
        "mail_sendmailmode": "smtp",
        "jpeg_quality": "60",
        "app_install_overwrite": [
            "nextcloudpi",
            "spgverein",
            "documents",
            "gluusso"
        ]
    }
}

```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Sun Jul 21 20:27:22.006493 2019] [:error] [pid 2648] avahi_entry_group_add_service_strlst("localhost") failed: Invalid host name
[Sun Jul 21 20:42:39.592411 2019] [mpm_prefork:notice] [pid 2629] AH00169: caught SIGTERM, shutting down
[Sun Jul 21 20:47:55.436342 2019] [ssl:warn] [pid 19762] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Sun Jul 21 20:47:55.443605 2019] [ssl:warn] [pid 19763] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Sun Jul 21 20:47:55.443789 2019] [http2:warn] [pid 19763] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Sun Jul 21 20:47:55.446382 2019] [mpm_prefork:notice] [pid 19763] AH00163: Apache/2.4.38 (Debian) OpenSSL/1.1.1c configured -- resuming normal operations
[Sun Jul 21 20:47:55.446415 2019] [core:notice] [pid 19763] AH00094: Command line: '/usr/sbin/apache2'
[Sun Jul 21 20:47:55.454932 2019] [:error] [pid 19765] avahi_entry_group_add_service_strlst("localhost") failed: Invalid host name
[Sun Jul 21 20:47:55.455972 2019] [:error] [pid 19765] avahi_entry_group_add_service_strlst("localhost") failed: Invalid host name
[Sun Jul 21 20:48:01.414009 2019] [:error] [pid 19765] avahi_entry_group_add_service_strlst("localhost") failed: Invalid host name
[Sun Jul 21 20:48:01.414954 2019] [:error] [pid 19765] avahi_entry_group_add_service_strlst("localhost") failed: Invalid host name
[Sun Jul 21 20:50:02.422421 2019] [mpm_prefork:notice] [pid 19763] AH00169: caught SIGTERM, shutting down
[Sun Jul 21 20:50:02.482424 2019] [ssl:warn] [pid 8167] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Sun Jul 21 20:50:02.490234 2019] [ssl:warn] [pid 8168] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Sun Jul 21 20:50:02.490419 2019] [http2:warn] [pid 8168] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Sun Jul 21 20:50:02.493022 2019] [mpm_prefork:notice] [pid 8168] AH00163: Apache/2.4.38 (Debian) OpenSSL/1.1.1c configured -- resuming normal operations
[Sun Jul 21 20:50:02.493051 2019] [core:notice] [pid 8168] AH00094: Command line: '/usr/sbin/apache2'
[Sun Jul 21 20:50:02.500613 2019] [:error] [pid 8172] avahi_entry_group_add_service_strlst("localhost") failed: Invalid host name
[Sun Jul 21 20:50:02.501630 2019] [:error] [pid 8172] avahi_entry_group_add_service_strlst("localhost") failed: Invalid host name
[Sun Jul 21 21:39:32.774037 2019] [core:notice] [pid 8168] AH00052: child pid 9116 exit signal Segmentation fault (11)

```
</details>

<details>
<summary>Database logs</summary>

```

2019-07-21 20:47:43 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2019-07-21 20:47:43 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2019-07-21 20:47:43 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2019-07-21 20:47:43 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2019-07-21 20:47:43 0 [Note] InnoDB: Waiting for purge to start
2019-07-21 20:47:43 0 [Note] InnoDB: 10.3.15 started; log sequence number 4620315447; transaction id 33352969
2019-07-21 20:47:43 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2019-07-21 20:47:43 0 [Note] Plugin 'FEEDBACK' is disabled.
2019-07-21 20:47:43 0 [Note] InnoDB: Buffer pool(s) load completed at 190721 20:47:43
2019-07-21 20:47:43 0 [Note] Server socket created on IP: '127.0.0.1'.
2019-07-21 20:47:43 0 [ERROR] Incorrect definition of table mysql.event: expected column 'sql_mode' at position 14 to have type set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','IGNORE_BAD_TABLE_OPTIONS','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_ALL_TABLES','NO_ZERO_IN_DATE','NO_ZERO_DATE','INVALID_DATES','ERROR_FOR_DIVISION_BY_ZERO','TRADITIONAL','NO_AUTO_CREATE_USER','HIGH_NOT_PRECEDENCE','NO_ENGINE_SUBSTITUTION','PAD_CHAR_TO_FULL_LENGTH','EMPTY_STRING_IS_NULL','SIMULTANEOUS_ASSIGNMENT'), found type set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','IGNORE_BAD_TABLE_OPTIONS','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALU
2019-07-21 20:47:43 0 [ERROR] mysqld: Event Scheduler: An error occurred when initializing system tables. Disabling the Event Scheduler.
2019-07-21 20:47:43 6 [Warning] InnoDB: Table mysql/innodb_table_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
2019-07-21 20:47:43 6 [Warning] InnoDB: Table mysql/innodb_index_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
2019-07-21 20:47:43 0 [Note] Reading of all Master_info entries succeded
2019-07-21 20:47:43 0 [Note] Added new Master_info '' to hash table
2019-07-21 20:47:43 0 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.3.15-MariaDB-1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Debian 10
2019-07-21 20:47:44 14 [Warning] InnoDB: Table mysql/innodb_table_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
2019-07-21 20:47:44 14 [Warning] InnoDB: Table mysql/innodb_table_stats has length mismatch in the column name table_name.  Please run mysql_upgrade

```
</details>

<details>
<summary>Nextcloud logs</summary>

```

{"reqId":"GQiKgAnJnfJbEZSdzAFp","level":1,"time":"2019-07-07T22:35:27+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Cleanup invalid photocache files for carddav","userAgent":"--","version":"16.0.1.1"}
{"reqId":"GQiKgAnJnfJbEZSdzAFp","level":1,"time":"2019-07-07T22:35:27+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Add background job to cleanup login flow v2 tokens","userAgent":"--","version":"16.0.1.1"}
{"reqId":"GQiKgAnJnfJbEZSdzAFp","level":1,"time":"2019-07-07T22:35:27+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Remove potentially over exposing share links","userAgent":"--","version":"16.0.1.1"}
{"reqId":"GQiKgAnJnfJbEZSdzAFp","level":1,"time":"2019-07-07T22:35:27+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: No need to remove link shares.","userAgent":"--","version":"16.0.1.1"}
{"reqId":"GQiKgAnJnfJbEZSdzAFp","level":1,"time":"2019-07-07T22:35:27+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAgent":"--","version":"16.0.1.1"}
{"reqId":"GQiKgAnJnfJbEZSdzAFp","level":1,"time":"2019-07-07T22:35:30+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"--","version":"16.0.1.1"}
{"reqId":"GQiKgAnJnfJbEZSdzAFp","level":1,"time":"2019-07-07T22:35:30+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"--","version":"16.0.2.1"}
{"reqId":"GQiKgAnJnfJbEZSdzAFp","level":1,"time":"2019-07-07T22:35:30+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"--","version":"16.0.2.1"}
{"reqId":"GQiKgAnJnfJbEZSdzAFp","level":1,"time":"2019-07-07T22:35:30+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"--","version":"16.0.2.1"}
{"reqId":"ZpR5jh2iVzDoc8IvDQAG","level":3,"time":"2019-07-08T02:15:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined variable: response at \/var\/www\/nextcloud\/apps\/dav\/lib\/CardDAV\/SyncService.php#107","userAgent":"--","version":"16.0.2.1"}
{"reqId":"ZpR5jh2iVzDoc8IvDQAG","level":3,"time":"2019-07-08T02:15:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Invalid argument supplied for foreach() at \/var\/www\/nextcloud\/apps\/dav\/lib\/CardDAV\/SyncService.php#107","userAgent":"--","version":"16.0.2.1"}
{"reqId":"ZpR5jh2iVzDoc8IvDQAG","level":3,"time":"2019-07-08T02:15:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined variable: response at \/var\/www\/nextcloud\/apps\/dav\/lib\/CardDAV\/SyncService.php#122","userAgent":"--","version":"16.0.2.1"}
{"reqId":"XSNkpn8AAQEAAHmeEj0AAAAH","level":3,"time":"2019-07-08T15:43:34+00:00","remoteAddr":"85.0.185.229","user":"--","app":"index","method":"GET","url":"\/apps\/files\/api\/v1\/showgridview","message":{"Exception":"TypeError","Message":"Argument 3 passed to OCA\\Files\\Service\\TagService::__construct() must be an instance of OCP\\ITags, null given, called in \/var\/www\/nextcloud\/apps\/files\/lib\/AppInfo\/Application.php on line 97","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/apps\/files\/lib\/AppInfo\/Application.php","line":97,"function":"__construct","class":"OCA\\Files\\Service\\TagService","type":"->","args":[{"__class__":"OC\\User\\Session"},{"__class__":"OC\\Activity\\Manager"},null,null,{"__class__":"Symfony\\Component\\EventDispatcher\\EventDispatcher"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":118,"function":"OCA\\Files\\AppInfo\\{closure}","class":"OCA\\Files\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":117,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["TagService"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":404,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["TagService"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":382,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["TagService"]},{"file":"\/var\/www\/nextcloud\/apps\/files\/lib\/AppInfo\/Application.php","line":54,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["TagService"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":118,"function":"OCA\\Files\\AppInfo\\{closure}","class":"OCA\\Files\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":117,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["APIController"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":404,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["APIController"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":382,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["APIController"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":97,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["APIController"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["APIController","getGridView","*** sensitive parameter replaced ***",{"_route":"files.API.getGridView"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"files.API.getGridView"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"files.API.getGridView"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/files\/api\/v1\/showgridview"]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/apps\/files\/lib\/Service\/TagService.php","Line":60,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.2.1"}
{"reqId":"XTJB2X8AAQEAAHmq120AAAAJ","level":3,"time":"2019-07-19T22:19:06+00:00","remoteAddr":"89.217.131.2","user":"--","app":"PHP","method":"GET","url":"\/index.php\/204","message":"unlink(\/var\/www\/nextcloud\/data\/appdata_ocj2z7xiag7t\/css\/core\/c354-30fb-server.css): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#228","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.0 RC3","version":"16.0.2.1"}
{"reqId":"XTJB2X8AAQEAAHmq120AAAAJ","level":3,"time":"2019-07-19T22:19:06+00:00","remoteAddr":"89.217.131.2","user":"--","app":"PHP","method":"GET","url":"\/index.php\/204","message":"unlink(\/var\/www\/nextcloud\/data\/appdata_ocj2z7xiag7t\/css\/icons\/icons-vars.css): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#228","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.0 RC3","version":"16.0.2.1"}
{"reqId":"XTJB2X8AAQEAAHmq120AAAAJ","level":3,"time":"2019-07-19T22:19:06+00:00","remoteAddr":"89.217.131.2","user":"--","app":"PHP","method":"GET","url":"\/index.php\/204","message":"unlink(\/var\/www\/nextcloud\/data\/appdata_ocj2z7xiag7t\/css\/notifications\/12a4-30fb-styles.css): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#228","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.0 RC3","version":"16.0.2.1"}
{"reqId":"XTJB2X8AAQEAAHmq120AAAAJ","level":3,"time":"2019-07-19T22:19:06+00:00","remoteAddr":"89.217.131.2","user":"--","app":"PHP","method":"GET","url":"\/index.php\/204","message":"unlink(\/var\/www\/nextcloud\/data\/appdata_ocj2z7xiag7t\/css\/notifications\/12a4-30fb-styles.css.deps): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#228","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.0 RC3","version":"16.0.2.1"}
{"reqId":"XTJB2X8AAQEAAHmq120AAAAJ","level":3,"time":"2019-07-19T22:19:06+00:00","remoteAddr":"89.217.131.2","user":"--","app":"PHP","method":"GET","url":"\/index.php\/204","message":"unlink(\/var\/www\/nextcloud\/data\/appdata_ocj2z7xiag7t\/css\/notifications\/12a4-30fb-styles.css.gzip): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#228","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.0 RC3","version":"16.0.2.1"}
{"reqId":"Nv5X2mZ1obT5jZHACpgh","level":3,"time":"2019-07-19T22:30:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"RedisException","Message":"MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/Memcache\/Redis.php","line":64,"function":"setex","class":"Redis","type":"->","args":["860ecd96bcb3550ddc7ce83d044fb1f1\/AutoloaderOC_Hook",60,"[\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/hook.php\"]"]},{"file":"\/var\/www\/nextcloud\/lib\/autoloader.php","line":168,"function":"set","class":"OC\\Memcache\\Redis","type":"->","args":["OC_Hook",["\/var\/www\/nextcloud\/lib\/private\/legacy\/hook.php"],60]},{"function":"load","class":"OC\\Autoloader","type":"->","args":["OC_Hook"]},{"file":"\/var\/www\/nextcloud\/lib\/public\/Util.php","line":327,"function":"spl_autoload_call","args":["OC_Hook"]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":702,"function":"connectHook","class":"OCP\\Util","type":"::","args":["\\OCA\\Files_Sharing\\API\\Server2Server","preLoginNameUsedAsUserName","\\OC\\User\\Database","preLoginNameUsedAsUserName"]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":1056,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/nextcloud\/cron.php","line":41,"args":["\/var\/www\/nextcloud\/lib\/base.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/lib\/private\/Memcache\/Redis.php","Line":64,"CustomMessage":"--"},"userAgent":"--","version":"16.0.2.1"}
{"reqId":"XTTBBjrkUESbB1meO@YM2QAAAAM","level":3,"time":"2019-07-21T19:46:14+00:00","remoteAddr":"89.217.131.2","user":"--","app":"PHP","method":"GET","url":"\/index.php\/204","message":"unlink(\/var\/www\/nextcloud\/data\/appdata_ocj2z7xiag7t\/css\/core\/c354-30fb-server.css.gzip): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#228","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.7.0 RC3","version":"16.0.2.1"}

```
</details>

**Comment by nachoparker** [comment]
Thanks for reporting. Looks like redis had some I/O problems? There is a ton of people that have run the upgrade command in the past year or two (including NC16.0.3) so I wonder what happened to you.

On a side note: even you are part of the nextcloud organization and have write access, please send your PRs against the `devel` branch so they can be reviewed before merge.

In your case it was a tiny typo so it's ok :)

**Comment by violoncelloCH** [comment]
hi @nachoparker 
thanks for your response!
In the meantime ncp tried to do the update again (autoupdate) and failed awfully.
I guess because of no remaining diskspace (because of the backups?):
at least the data seems to be still there and the DB as well... (I don't know why but under /var/www/ncp-data.K648Fa)
but in /var/www/nextcloud/ there is an empty config.php (and a CAN_INSTALL)
I can't find the original config.php anywhere :/ any idea where I could retrieve it from? (I would have expected it in the backup archives, but can't find it there (only the apps/ and data/ directory seem to be there); also it includes all the old backup archives there as well, what I don't understand why (so multiplying diskspace usage with every backup))...


---
̣
I'm sorry about that... I was just too lazy to do a PR for a one character change :see_no_evil: will do a proper PR next time of course :)

**Comment by nachoparker** [comment]
sounds like you need to free up some space before trying to upgrade?

if that's the case I'll close, but we can keep discussing and reopen if needed.
